import fs from "node:fs";
import path from "node:path";
import { listingSchema, type Listing } from "../lib/types";

const TODAY = "2026-09-14";
const ROOT = process.cwd();
const OUT = path.join(ROOT, "data", "listings", "surf");

type Seed = Omit<Listing, "genre" | "verified_at" | "status"> & {
  status?: Listing["status"];
  verified_at?: string;
};

const seeds: Seed[] = [
  // ============ POINTS ============
  {
    slug: "kizakihama",
    category: ["point"],
    area: "miyazaki-shi",
    name: { ja: "木崎浜", en: "Kizakihama" },
    address: { ja: "宮崎県宮崎市熊野2206-1", en: "2206-1 Kumano, Miyazaki-shi, Miyazaki 888-9215" },
    lat: null, lng: null,
    phone: "0985-21-1791",
    website: null,
    google_maps_url: null,
    hours: null,
    price: {
      ja: "温水シャワー200円、冷水シャワー無料",
      en: "Warm shower 200 yen, cold shower free",
    },
    description: {
      ja: "宮崎市南部のロングビーチ。駐車場は約300台。ソラシドエアサーフィンセンター木崎浜（2022年4月開設）にシャワー室・更衣室あり。",
      en: "Long beach south of central Miyazaki. Parking for about 300. Solaseed Air Surfing Center (opened April 2022) has showers and changing rooms.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/golf_surfing/1446"],
  },
  {
    slug: "aoshima",
    category: ["point"],
    area: "miyazaki-shi",
    name: { ja: "青島", en: "Aoshima" },
    address: { ja: "宮崎県宮崎市青島1-16-1", en: "1-16-1 Aoshima, Miyazaki-shi, Miyazaki 889-2162" },
    lat: null, lng: null,
    phone: "0985-65-1055",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "青島神社に隣接する海岸。南側は穏やか、北側は木崎浜方面へ広がる。青島ビーチセンターにロッカーと温水シャワーあり。",
      en: "Beach next to Aoshima Shrine. South side is calmer; the north side extends toward Kizakihama. Aoshima Beach Center has lockers and hot showers.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/golf_surfing/1447"],
  },
  {
    slug: "okuragahama",
    category: ["point"],
    area: "hyuga",
    name: { ja: "お倉ヶ浜", en: "Okuragahama" },
    address: { ja: "宮崎県日向市平岩12298-6", en: "12298-6 Hiraiwa, Hyuga-shi, Miyazaki 883-0022" },
    lat: null, lng: null,
    phone: "0982-66-1026",
    website: null,
    google_maps_url: null,
    hours: null,
    price: {
      ja: "温水・冷水シャワーあり",
      en: "Hot and cold showers on site",
    },
    description: {
      ja: "約4kmのロングビーチ。2017年 ISA ワールドジュニアサーフィン選手権の会場。マリンウェーブビーチハウスに駐車305台（無料）。",
      en: "About a 4 km beach. Venue for the 2017 ISA World Junior Surfing Championship. Marine Wave Beach House has 305 free parking spaces.",
    },
    tags: null,
    sources: [
      "https://www.kanko-miyazaki.jp/golf_surfing/1167",
      "https://hyuga.or.jp/app/spots/view/2",
    ],
  },
  {
    slug: "kanegahama",
    category: ["point"],
    area: "hyuga",
    name: { ja: "金ヶ浜", en: "Kanegahama" },
    address: { ja: "宮崎県日向市平岩2338-1", en: "2338-1 Hiraiwa, Hyuga-shi, Miyazaki 883-0022" },
    lat: null, lng: null,
    phone: "0982-66-1026",
    website: null,
    google_maps_url: null,
    hours: null,
    price: {
      ja: "温水シャワー200円",
      en: "Warm shower 200 yen",
    },
    description: {
      ja: "国道10号のすぐ脇にある海岸。近くに STAIRS OF THE SEA。",
      en: "Beach right off Route 10. STAIRS OF THE SEA complex is nearby.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/golf_surfing/1168"],
  },
  {
    slug: "isegahama",
    category: ["point"],
    area: "hyuga",
    name: { ja: "伊勢ヶ浜", en: "Isegahama" },
    address: { ja: "宮崎県日向市日知屋599-3", en: "599-3 Hichiya, Hyuga-shi, Miyazaki 883-0062" },
    lat: null, lng: null,
    phone: "0982-66-1026",
    website: null,
    google_maps_url: null,
    hours: null,
    price: {
      ja: "シャワー100円",
      en: "Shower 100 yen",
    },
    description: {
      ja: "日本の海水浴場100選に選ばれた海岸。無料駐車場82台。",
      en: "Selected among Japan's 100 Best Bathing Beaches. 82 free parking spaces.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/golf_surfing/1171"],
  },
  {
    slug: "ikurahama",
    category: ["point"],
    area: "kawaminami",
    name: { ja: "伊倉浜", en: "Ikurahama" },
    address: { ja: "宮崎県児湯郡川南町大字川南17661-1", en: "17661-1 Kawaminami, Kawaminami-cho, Miyazaki 889-1301" },
    lat: null, lng: null,
    phone: "0983-27-8011",
    website: null,
    google_maps_url: null,
    hours: null,
    price: {
      ja: "冷水シャワー無料",
      en: "Cold showers free",
    },
    description: {
      ja: "約9kmの海岸線。サーフセンターにシャワーとロッカーあり。",
      en: "About 9 km of coastline. Surf center has showers and lockers.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/golf_surfing/1164"],
  },
  {
    slug: "kaguchihama",
    category: ["point"],
    area: "takanabe",
    name: { ja: "蚊口浜", en: "Kaguchihama" },
    address: { ja: "宮崎県児湯郡高鍋町蚊口浦6259-1", en: "6259-1 Kaguchiura, Takanabe-cho, Miyazaki 884-0004" },
    lat: null, lng: null,
    phone: "0983-22-5588",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "ビーチブレイクの海岸。蚊口浜海浜公園キャンプ場が隣接。無料駐車場50台。",
      en: "Beach break. Kaguchihama Seaside Park campsite is adjacent. 50 free parking spaces.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/golf_surfing/1163"],
  },
  {
    slug: "kazatahama",
    category: ["point"],
    area: "nichinan",
    name: { ja: "風田浜", en: "Kazatahama" },
    address: { ja: "宮崎県日南市風田", en: "Kazata, Nichinan-shi, Miyazaki 887-0034" },
    lat: null, lng: null,
    phone: "0987-31-1134",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "大会が開かれる海岸。ウミガメの産卵地でもある。駐車場は約15台、トイレは近隣に無し。",
      en: "Beach that hosts competitions and is a sea turtle nesting site. About 15 parking spaces, no restrooms on site.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/golf_surfing/1165"],
  },
  {
    slug: "umegahama",
    category: ["point"],
    area: "nichinan",
    name: { ja: "梅ヶ浜", en: "Umegahama" },
    address: { ja: "宮崎県日南市平野 梅ケ浜", en: "Umegahama, Hirano, Nichinan-shi, Miyazaki 887-0017" },
    lat: null, lng: null,
    phone: "0987-31-1134",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "ライオン岩を目印にした上級者向けブレイク。近くには広渡川の河口ポイントもある。",
      en: "Advanced-level break with the Lion Rock landmark. The Hirowatari river mouth is also nearby.",
    },
    tags: null,
    sources: [
      "https://www.kanko-miyazaki.jp/golf_surfing/1166",
      "https://www.kankou-nichinan.jp/tourisms/1347/",
    ],
  },
  {
    slug: "koigaura",
    category: ["point"],
    area: "kushima",
    name: { ja: "恋ヶ浦", en: "Koigaura" },
    address: { ja: "宮崎県串間市大納", en: "Ono, Kushima-shi, Miyazaki 888-0221" },
    lat: null, lng: null,
    phone: "0987-55-1128",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "1年を通して波が立つポイント。左右のブレイクがある。無料駐車場は3台のみ。",
      en: "Waves throughout the year, with left and right breaks. Only three free parking spaces.",
    },
    tags: null,
    sources: [
      "https://www.kanko-miyazaki.jp/golf_surfing/1162",
      "https://kushima-city.jp/koi/",
    ],
  },

  // ============ SHOPS / SCHOOL / RENTAL ============
  {
    slug: "surf3",
    category: ["shop", "rental"],
    area: "miyazaki-shi",
    name: { ja: "サーフスリー", en: "Surf3" },
    address: { ja: "宮崎県宮崎市大字熊野2278-8", en: "2278-8 Kumano, Miyazaki-shi, Miyazaki 889-2151" },
    lat: null, lng: null,
    phone: "0985-58-5035",
    website: "https://www.surf3-sincere.com/",
    google_maps_url: null,
    hours: null,
    price: {
      ja: "ボードレンタル 3,000円/日、ウェットスーツ 2,000円",
      en: "Board rental 3,000 yen/day; wetsuit 2,000 yen",
    },
    description: {
      ja: "木崎浜近くのショップ。店内にウェットスーツ工場を併設。ブランド問わず修理を受け付ける。木曜定休。",
      en: "Shop near Kizakihama with an in-house wetsuit factory. Repairs boards from any brand. Closed Thursdays.",
    },
    tags: null,
    sources: ["https://www.miyazaki-city.tourism.or.jp/spot/11547"],
  },
  {
    slug: "rum-jungle",
    category: ["shop", "school", "rental"],
    area: "miyazaki-shi",
    name: { ja: "ラムジャングル", en: "Rum Jungle Surfshop" },
    address: { ja: "宮崎県宮崎市阿波岐原町前浜4276-399", en: "4276-399 Maehama, Awagigahara-cho, Miyazaki-shi, Miyazaki 880-0835" },
    lat: null, lng: null,
    phone: "090-4342-0004",
    website: "https://rumjungle-surf.shop/",
    google_maps_url: null,
    hours: null,
    price: {
      ja: "ガイド 7,000円〜、スクール 5,000円",
      en: "Guide from 7,000 yen; lesson 5,000 yen",
    },
    description: {
      ja: "一ツ葉エリアの老舗ショップ。スクール、レンタル、ガイドツアーを扱う。",
      en: "Long-established shop in the Hitotsuba area. Handles lessons, rentals, and guided tours.",
    },
    tags: null,
    sources: ["https://www.miyazaki-city.tourism.or.jp/spot/11562"],
  },
  {
    slug: "new-wave-surf",
    category: ["shop", "school", "rental"],
    area: "miyazaki-shi",
    name: { ja: "ニューウェーブ", en: "NEW WAVE SURF & SKATE" },
    address: { ja: "宮崎県宮崎市大字熊野1315-1", en: "1315-1 Kumano, Miyazaki-shi, Miyazaki 889-2151" },
    lat: null, lng: null,
    phone: "0985-58-2155",
    website: "https://newwavesurf.shop/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "木崎浜近くのショップ。スクール、レンタル、ガイドツアーを扱う。JPBA プロショップ。",
      en: "Shop near Kizakihama. Handles lessons, rentals, and guided tours. JPBA pro shop.",
    },
    tags: null,
    sources: ["https://newwavesurf.shop/"],
  },
  {
    slug: "high-surf",
    category: ["shop", "school", "rental"],
    area: "miyazaki-shi",
    name: { ja: "ハイサーフ", en: "HIGH SURF" },
    address: { ja: "宮崎県宮崎市大字加江田4710-13", en: "4710-13 Kaeda, Miyazaki-shi, Miyazaki 889-2161" },
    lat: null, lng: null,
    phone: "0985-75-0473",
    website: "https://www.highsurf-miyazaki.com/",
    google_maps_url: null,
    hours: null,
    price: {
      ja: "スクール 5,500円、SUP あり",
      en: "Lesson 5,500 yen; SUP available",
    },
    description: {
      ja: "加江田エリアのショップ。スクールと SUP を扱う。駐車場20台。",
      en: "Shop in the Kaeda area. Lessons and SUP available. 20 parking spaces.",
    },
    tags: null,
    sources: ["https://www.miyazaki-city.tourism.or.jp/spot/11561"],
  },
  {
    slug: "gakky-surf-shop",
    category: ["shop", "school", "rental"],
    area: "miyazaki-shi",
    name: { ja: "ガッキーサーフショップ", en: "GAKKY SURF SHOP" },
    address: { ja: "宮崎県宮崎市大字赤江262", en: "262 Akae, Miyazaki-shi, Miyazaki 880-0912" },
    lat: null, lng: null,
    phone: "0985-71-0214",
    website: "http://gakkysurfshop.blogspot.com/",
    google_maps_url: null,
    hours: null,
    price: {
      ja: "スクール 5,500円〜",
      en: "Lesson from 5,500 yen",
    },
    description: {
      ja: "宮崎空港から徒歩3分ほどのショップ。空港からの無料送迎あり。",
      en: "Shop about a 3-minute walk from Miyazaki Airport. Free airport shuttle available.",
    },
    tags: null,
    sources: ["https://www.miyazaki-city.tourism.or.jp/spot/11551"],
  },
  {
    slug: "see-u-surf",
    category: ["shop", "school", "rental"],
    area: "miyazaki-shi",
    name: { ja: "シーユー", en: "See u Surf Shop" },
    address: { ja: "宮崎県宮崎市青島1-4-10", en: "1-4-10 Aoshima, Miyazaki-shi, Miyazaki 889-2162" },
    lat: null, lng: null,
    phone: "0985-69-0697",
    website: "https://seeu-surf.shop/",
    google_maps_url: null,
    hours: null,
    price: {
      ja: "ソフトボードレンタル 2,500〜4,500円、スクール 5,000円",
      en: "Soft board rental 2,500–4,500 yen; lesson 5,000 yen",
    },
    description: {
      ja: "青島ビーチから徒歩約1分のショップ。JPSA プロの梅野航星が営む。",
      en: "About a one-minute walk from Aoshima Beach. Run by JPSA pro Kosei Umeno.",
    },
    tags: null,
    sources: ["https://www.miyazaki-city.tourism.or.jp/spot/11548"],
  },
  {
    slug: "nagisa-store",
    category: ["shop", "school", "rental"],
    area: "miyazaki-shi",
    name: { ja: "ナギサストア", en: "Nagisa Store" },
    address: { ja: "宮崎県宮崎市青島1-11-7", en: "1-11-7 Aoshima, Miyazaki-shi, Miyazaki 889-2162" },
    lat: null, lng: null,
    phone: "0985-65-1070",
    website: "http://www.nagisastore.com",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "青島ビーチから徒歩30秒のショップ。60本以上のボードを扱う。水曜定休。",
      en: "Shop 30 seconds' walk from Aoshima Beach. Stocks over 60 boards. Closed Wednesdays.",
    },
    tags: null,
    sources: ["https://www.miyazaki-city.tourism.or.jp/spot/11560"],
  },
  {
    slug: "glance-surfboards",
    category: ["shop"],
    area: "miyazaki-shi",
    name: { ja: "グランスサーフボード", en: "glance surfboards" },
    address: { ja: "宮崎県宮崎市大字熊野10314-6", en: "10314-6 Kumano, Miyazaki-shi, Miyazaki 889-2151" },
    lat: null, lng: null,
    phone: "0985-55-3818",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "ボード製造、カスタムエアブラシ、修理を扱うショップ。レンタルとスクールは無し。",
      en: "Shop that handles board manufacturing, custom airbrush, and repairs. No rentals or lessons.",
    },
    tags: null,
    sources: ["https://www.miyazaki-city.tourism.or.jp/spot/11553"],
  },
  {
    slug: "quest-surf",
    category: ["shop", "school", "rental"],
    area: "miyazaki-shi",
    name: { ja: "クエスト", en: "QUEST" },
    address: { ja: "宮崎県宮崎市恒久南2-1-4", en: "2-1-4 Tsunehisa-Minami, Miyazaki-shi, Miyazaki 880-0915" },
    lat: null, lng: null,
    phone: "0985-50-7227",
    website: "https://www.quest-surf.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "南宮崎駅から約300mのショップ。Firewire、Tokoro を扱う。修理、レンタル、スクールあり。",
      en: "Shop about 300 m from Minami-Miyazaki Station. Carries Firewire and Tokoro. Repairs, rentals, and lessons.",
    },
    tags: null,
    sources: ["https://www.miyazaki-city.tourism.or.jp/spot/11552"],
  },
  {
    slug: "first-trip",
    category: ["shop", "school", "rental"],
    area: "miyazaki-shi",
    name: { ja: "ファーストトリップ サーフ&ヴィンテージ", en: "First Trip Surf & Vintage" },
    address: { ja: "宮崎県宮崎市学園木花台桜1-15-6", en: "1-15-6 Gakuen Kibanadai Sakura, Miyazaki-shi, Miyazaki 889-2154" },
    lat: null, lng: null,
    phone: "0985-71-2694",
    website: "https://firsttrip-surfboard.stores.jp",
    google_maps_url: null,
    hours: null,
    price: {
      ja: "2泊3日レンタルパック 4,800円〜",
      en: "2-night/3-day rental pack from 4,800 yen",
    },
    description: {
      ja: "木崎浜から車で約5分のショップ。1対1レッスンとレンタルパックを扱う。",
      en: "Shop about a 5-minute drive from Kizakihama. Offers 1-on-1 lessons and rental packs.",
    },
    tags: null,
    sources: ["https://www.miyazaki-city.tourism.or.jp/spot/11549"],
  },
  {
    slug: "connect-journey",
    category: ["shop", "school", "rental"],
    area: "miyazaki-shi",
    name: { ja: "コネクトジャーニー", en: "CONNECT JOURNEY" },
    address: { ja: "宮崎県宮崎市田代町59-1 ハピネス田代501", en: "Happiness Tashiro 501, 59-1 Tashiro-cho, Miyazaki-shi, Miyazaki 880-0855" },
    lat: null, lng: null,
    phone: "090-1873-8344",
    website: "http://connect-journey.com",
    google_maps_url: null,
    hours: null,
    price: {
      ja: "スクール 7,000円、ガイド・レンタル 3,500円/日",
      en: "Lesson 7,000 yen; guide and rental 3,500 yen/day",
    },
    description: {
      ja: "プロサーファー秋元翔平のブランド。スクール、ガイド、レンタルを扱う。",
      en: "Brand run by pro surfer Shohei Akimoto. Lessons, guiding, and rentals.",
    },
    tags: null,
    sources: ["https://www.miyazaki-city.tourism.or.jp/spot/11554"],
  },
  {
    slug: "sunrise-surfshop",
    category: ["shop", "school", "rental"],
    area: "hyuga",
    name: { ja: "サンライズサーフショップ", en: "SUNRISE SURFSHOP" },
    address: { ja: "宮崎県日向市（お倉ヶ浜近く）", en: "Near Okuragahama, Hyuga-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-56-2609",
    website: "https://www.sunrise-surfshop.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "お倉ヶ浜のすぐそば。ゲストハウス OCEANSIDE お倉ヶ浜（2024年3月開業）に隣接する。",
      en: "Right next to Okuragahama. Adjacent to the OCEANSIDE Okuragahama guesthouse, which opened in March 2024.",
    },
    tags: null,
    sources: ["https://www.sunrise-surfshop.com/"],
  },
  {
    slug: "on-the-beach",
    category: ["shop", "school", "rental"],
    area: "hyuga",
    name: { ja: "オンザビーチ", en: "ON THE BEACH" },
    address: { ja: "宮崎県日向市平岩金ヶ浜2220-9", en: "2220-9 Hiraiwa Kanegahama, Hyuga-shi, Miyazaki 883-0022" },
    lat: null, lng: null,
    phone: "0982-57-2548",
    website: "https://onthebeach.jp/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "1996年創業。JPSA プロの久保田聡が営むショップ。カスタムボード・ウェットスーツ、オンラインコーチングあり。",
      en: "Established in 1996 and run by JPSA pro Satoshi Kubota. Custom boards and wetsuits, plus online coaching.",
    },
    tags: null,
    sources: ["https://onthebeach.jp/"],
  },
  {
    slug: "connection-nobeoka",
    category: ["shop", "school", "rental"],
    area: "nobeoka",
    name: { ja: "コネクション", en: "CONNECTION" },
    address: { ja: "宮崎県延岡市方財町64", en: "64 Hozai-cho, Nobeoka-shi, Miyazaki 882-0853" },
    lat: null, lng: null,
    phone: "0982-32-0517",
    website: "https://www.connection-nobeoka.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "フルカスタムボードを扱うショップ。BeMoLo シューズ取扱い。初心者体験とコーチングあり。木曜定休。",
      en: "Shop that handles fully custom boards. BeMoLo shoes dealer. Beginner sessions and coaching. Closed Thursdays.",
    },
    tags: null,
    sources: ["https://www.connection-nobeoka.com/"],
  },
  {
    slug: "freedom-nichinan",
    category: ["shop", "school"],
    area: "nichinan",
    name: { ja: "フリーダム", en: "Freedom Surf Shop" },
    address: { ja: "宮崎県日南市平山2318-2", en: "2318-2 Hirayama, Nichinan-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0987-23-6873",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "宮浦海岸を中心にスクールを行うショップ。生徒3人に対しインストラクター1人。3日前までに予約。",
      en: "Shop that runs lessons based at Miyaura Beach. Three students per instructor. Book at least three days in advance.",
    },
    tags: null,
    sources: ["https://www.kankou-nichinan.jp/tourisms/370/"],
  },
  {
    slug: "delight-surfing",
    category: ["shop", "school", "rental"],
    area: "miyakonojo",
    name: { ja: "ディライトサーフィンサービス", en: "Delight Surfing Service" },
    address: { ja: "宮崎県都城市広原町10-6", en: "10-6 Kobaru-cho, Miyakonojo-shi, Miyazaki 885-0036" },
    lat: null, lng: null,
    phone: "0986-21-1110",
    website: "https://www.delight-mjc.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "都城市内のショップ。ボード、ボディボード、ウェットスーツを扱い、カスタムボード製造（ヒロタサーフボードラボ）も行う。",
      en: "Shop in Miyakonojo. Handles boards, bodyboards, and wetsuits, and manufactures custom boards (Hirota Surfboards Lab).",
    },
    tags: null,
    sources: ["https://www.delight-mjc.com/"],
  },
  {
    slug: "killer-surf-miyazaki",
    category: ["school", "shop", "rental"],
    area: "miyazaki-shi",
    name: { ja: "キラーサーフ宮崎", en: "Killer Surf Miyazaki" },
    address: { ja: "宮崎県宮崎市加江田4877-1", en: "4877-1 Kaeda, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "090-1366-1365",
    website: "https://www.miyazaki-killersurfjapan.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "JPSA プロの川端太志が営むスクール。ガイド、レンタル、STAND ウェットスーツも扱う。",
      en: "School run by JPSA pro Taishi Kawabata. Guiding, rentals, and STAND wetsuits.",
    },
    tags: null,
    sources: ["https://www.miyazaki-killersurfjapan.com/"],
  },
  {
    slug: "surf-city-miyazaki",
    category: ["school", "rental"],
    area: "miyazaki-shi",
    name: { ja: "サーフシティ宮崎", en: "SURF CITY MIYAZAKI" },
    address: { ja: "宮崎県宮崎市青島2-1-11", en: "2-1-11 Aoshima, Miyazaki-shi, Miyazaki 889-2162" },
    lat: null, lng: null,
    phone: "050-3571-3238",
    website: "https://surfcity-miyazaki.jp/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "青島海浜公園に隣接。サーフ、SUP、ヨガ、キッズ放課後サーフを扱う。アソビューから予約可。",
      en: "Adjacent to Aoshima Beach Park. Surf, SUP, yoga, and after-school kids' surf. Bookable via Asoview.",
    },
    tags: null,
    sources: ["https://surfcity-miyazaki.jp/"],
  },
  {
    slug: "ekolu-miyazaki",
    category: ["school", "rental"],
    area: "miyazaki-shi",
    name: { ja: "エコル宮崎サーフガイド&レンタカー", en: "ekolu Surf Guide & Rent a Car" },
    address: { ja: "宮崎県宮崎市大字赤江74-1 レジデンスエアポート402", en: "Residence Airport 402, 74-1 Akae, Miyazaki-shi, Miyazaki 880-0912" },
    lat: null, lng: null,
    phone: "0985-56-1515",
    website: "https://ekolu-miyazaki.com",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "元 JPSA プロの水元光志が営む。空港近くでサーフガイドとサーファー向けレンタカーを扱う。",
      en: "Run by former JPSA pro Koshi Mizumoto. Offers surf guiding and surfer-focused rental cars near the airport.",
    },
    tags: null,
    sources: ["https://www.miyazaki-city.tourism.or.jp/spot/11545"],
  },
  {
    slug: "kengoria-surf",
    category: ["school", "rental"],
    area: "miyazaki-shi",
    name: { ja: "ケンゴリア", en: "KENGORIA" },
    address: { ja: "宮崎県宮崎市吉村町曽師中甲3104-6", en: "3104-6 Sojinaka-ko, Yoshimura-cho, Miyazaki-shi, Miyazaki 880-0841" },
    lat: null, lng: null,
    phone: "0985-71-0270",
    website: "https://www.kengoriasurf.com/",
    google_maps_url: null,
    hours: null,
    price: {
      ja: "スクール 6,600円〜、ガイド 14,700円〜、フォイル 13,750円",
      en: "Lesson from 6,600 yen; guide from 14,700 yen; foil 13,750 yen",
    },
    description: {
      ja: "サーフ、SUP、フォイルのレッスンとガイドを扱う。営業9:00〜18:00。",
      en: "Surf, SUP, and foil lessons and guiding. Open 9:00–18:00.",
    },
    tags: null,
    sources: [
      "https://www.miyazaki-city.tourism.or.jp/spot/11546",
      "https://www.kengoriasurf.com/",
    ],
  },
  {
    slug: "miyazaki-surf-guide",
    category: ["school", "rental"],
    area: "miyazaki-shi",
    name: { ja: "宮崎サーフガイド", en: "Miyazaki Surf Guide" },
    address: { ja: "宮崎県宮崎市青島1-16-1 ANAホリデイ・イン・リゾート宮崎アクティビティセンター内", en: "ANA Holiday Inn Resort Miyazaki Activity Center, 1-16-1 Aoshima, Miyazaki-shi, Miyazaki 889-2161" },
    lat: null, lng: null,
    phone: "050-6870-9992",
    website: "https://miyazakisurfguide.com",
    google_maps_url: null,
    hours: {
      ja: "9:00〜17:00（要予約）",
      en: "9:00–17:00 (reservation required)",
    },
    price: null,
    description: {
      ja: "初心者体験、レベルアップレッスン、プライベートサーフガイド、ボード・ウェットレンタルを扱う。温水シャワー、更衣室、タオル付き。英語対応あり。",
      en: "Beginner sessions, level-up lessons, private guiding, and board/wetsuit rental. Hot shower, changing room, and towels included. English support available.",
    },
    tags: null,
    sources: ["https://www.miyazaki-city.tourism.or.jp/spot/13152"],
  },
  {
    slug: "total-coordinate",
    category: ["school"],
    area: "miyazaki-shi",
    name: { ja: "トータルコーディネート", en: "Total Coordinate" },
    address: { ja: "宮崎県宮崎市小戸町27", en: "27 Ondo-cho, Miyazaki-shi, Miyazaki 880-0857" },
    lat: null, lng: null,
    phone: "0985-69-3999",
    website: "https://www.totalcoordinate-world.com/",
    google_maps_url: null,
    hours: {
      ja: "9:00〜19:00",
      en: "9:00–19:00",
    },
    price: null,
    description: {
      ja: "サーフィン指導25年のガイドが在籍。サーフ、SUP、SUPヨガ、ヨガ、コアトレーニングを扱う。宮崎駅からの送迎あり。駐車場7台。",
      en: "Guide with 25 years of surf instruction experience. Handles surf, SUP, SUP yoga, yoga, and core training. Pickup from Miyazaki Station. Parking for seven.",
    },
    tags: null,
    sources: ["https://www.miyazaki-city.tourism.or.jp/spot/11559"],
  },
  {
    slug: "himuka-kando-taiken",
    category: ["school"],
    area: "nobeoka",
    name: { ja: "NPO法人 ひむか感動体験ワールド", en: "NPO Himuka Kando Taiken World" },
    address: { ja: "宮崎県延岡市北川町川内7344", en: "7344 Kawachi, Kitakawa-cho, Nobeoka-shi, Miyazaki 889-0101" },
    lat: null, lng: null,
    phone: "0982-27-6322",
    website: null,
    google_maps_url: null,
    hours: {
      ja: "9:00〜18:00 水曜定休、12/29〜1/3 休み",
      en: "9:00–18:00, closed Wed and Dec 29–Jan 3",
    },
    price: {
      ja: "1人 7,000円（別途レンタル料）",
      en: "7,000 yen per person (rental fee extra)",
    },
    description: {
      ja: "初心者向けロングボードから上級者向けショートボードまで、プロが指導するサーフィン体験。延岡市北川町拠点。",
      en: "Surf sessions taught by a pro, from beginner longboard to advanced shortboard. Based in Kitakawa, Nobeoka.",
    },
    tags: null,
    sources: ["https://nobekan.jp/activity/index.php?p=620"],
  },
  {
    slug: "odotsu",
    category: ["point"],
    area: "nichinan",
    name: { ja: "大堂津", en: "Odotsu" },
    address: { ja: "宮崎県日南市大堂津", en: "Odotsu, Nichinan-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0987-31-1134",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "島に囲まれた湾のため、比較的波が穏やか。初心者向けのポイント。",
      en: "A bay ringed by islands, so the waves are relatively calm. A beginner-friendly break.",
    },
    tags: null,
    sources: ["https://www.kankou-nichinan.jp/tourisms/1352/"],
  },
  {
    slug: "minshuku-kaiyo-so",
    category: ["stay"],
    area: "kushima",
    name: { ja: "民宿海洋荘", en: "Minshuku Kaiyo-so" },
    address: { ja: "宮崎県串間市大納58", en: "58 Ono, Kushima-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0987-76-1354",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "恋ヶ浦のある大納エリアの民宿。",
      en: "Minshuku in the Ono district near Koigaura.",
    },
    tags: null,
    sources: ["https://kushima-city.jp/stay/"],
  },
  {
    slug: "minshuku-ogon-so",
    category: ["stay"],
    area: "kushima",
    name: { ja: "民宿黄金荘", en: "Minshuku Ogon-so" },
    address: { ja: "宮崎県串間市大納48-7", en: "48-7 Ono, Kushima-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0987-76-1029",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "恋ヶ浦のある大納エリアの民宿。",
      en: "Minshuku in the Ono district near Koigaura.",
    },
    tags: null,
    sources: ["https://kushima-city.jp/stay/"],
  },
  {
    slug: "surfguide-himawari",
    category: ["school"],
    area: "miyazaki-shi",
    name: { ja: "サーフガイドHIMAWARI", en: "Surf Guide HIMAWARI" },
    address: { ja: "宮崎県宮崎市青島西1-10-1", en: "1-10-1 Aoshima-Nishi, Miyazaki-shi, Miyazaki 889-2163" },
    lat: null, lng: null,
    phone: "0985-65-1138",
    website: "http://surfguide-himawari.net/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "1日1組限定のスクール。ボードロッカー、レンタルあり。要予約。",
      en: "Lessons for one group per day. Board lockers and rentals. Reservation required.",
    },
    tags: null,
    sources: ["https://www.miyazaki-city.tourism.or.jp/spot/11563"],
  },
  {
    slug: "aloha-rentacar",
    category: ["rental"],
    area: "miyazaki-shi",
    name: { ja: "アロハレンタカー", en: "Aloha Rentacar" },
    address: { ja: "宮崎県宮崎市大島町高崎416-1", en: "416-1 Takasaki, Oshima-cho, Miyazaki-shi, Miyazaki 880-0824" },
    lat: null, lng: null,
    phone: "070-7622-0039",
    website: "https://aloha-rentacar.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "サーファー向けのレンタカー。ポリタンクやハンガーなどの付属品は無料。",
      en: "Rental cars for surfers. Poly-tank and hangers included free.",
    },
    tags: null,
    sources: ["https://www.miyazaki-city.tourism.or.jp/spot/11550"],
  },
  {
    slug: "trip-rentacar-miyazaki",
    category: ["rental"],
    area: "miyazaki-shi",
    name: { ja: "トリップレンタカー宮崎", en: "SURF & TURF Trip Rent a Car MIYAZAKI" },
    address: { ja: "宮崎県宮崎市学園木花台南3-16-4", en: "3-16-4 Gakuen Kibanadai-Minami, Miyazaki-shi, Miyazaki 889-2153" },
    lat: null, lng: null,
    phone: "070-9005-1173",
    website: "https://www.trip-rent-a-car.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "宮崎空港の送迎付きレンタカー。サーフボードのレンタル込み。サーフトリップ向けの車両サイズ。",
      en: "Rental car service with airport pickup and surfboard rental included. Vehicles sized for surf trips.",
    },
    tags: null,
    sources: ["https://www.trip-rent-a-car.com/"],
  },

  // ============ STAYS ============
  {
    slug: "oceanside-okuragahama",
    category: ["stay"],
    area: "hyuga",
    name: { ja: "オーシャンサイド お倉ヶ浜 ゲストハウス", en: "OCEANSIDE Okuragahama Beach Garden" },
    address: { ja: "宮崎県日向市平岩10873-26", en: "10873-26 Hiraiwa, Hyuga-shi, Miyazaki 883-0022" },
    lat: null, lng: null,
    phone: "0982-56-2609",
    website: "https://oceansideokuragahama.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "お倉ヶ浜から徒歩5分のコンテナハウス型ゲストハウス。隣にサンライズサーフショップがある。",
      en: "Container-house guesthouse a five-minute walk from Okuragahama. Sunrise Surf Shop is next door.",
    },
    tags: null,
    sources: ["https://hyuga.or.jp/app/hotels"],
  },
  {
    slug: "minshuku-kanegahama",
    category: ["stay"],
    area: "hyuga",
    name: { ja: "民宿金ヶ浜", en: "Minshuku Kanegahama" },
    address: { ja: "宮崎県日向市平岩2221-1", en: "2221-1 Hiraiwa, Hyuga-shi, Miyazaki 883-0022" },
    lat: null, lng: null,
    phone: "0982-57-1550",
    website: "https://www.kanegahama.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "金ヶ浜の真向かいにある民宿。ボードロッカーと地魚を使った夕食あり。",
      en: "Minshuku directly opposite Kanegahama. Board lockers and dinner featuring local seafood.",
    },
    tags: null,
    sources: ["https://www.kanegahama.com/"],
  },
  {
    slug: "pleasant-hyuga",
    category: ["stay"],
    area: "hyuga",
    name: { ja: "プレザント日向", en: "Pleasant Hyuga" },
    address: { ja: "宮崎県日向市平岩64-1", en: "64-1 Hiraiwa, Hyuga-shi, Miyazaki 883-0022" },
    lat: null, lng: null,
    phone: "0982-57-2727",
    website: "https://pleasant-hyuga.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "お倉ヶ浜を見下ろす宿。サーファーとファミリー向け。",
      en: "Lodging overlooking Okuragahama, aimed at surfers and families.",
    },
    tags: null,
    sources: ["https://hyuga.or.jp/app/hotels"],
  },
  {
    slug: "swell-guesthouse-cafe",
    category: ["stay"],
    area: "hyuga",
    name: { ja: "SWELL Guesthouse & Cafe", en: "SWELL Guesthouse & Cafe" },
    address: { ja: "宮崎県日向市財光寺1848-2", en: "1848-2 Zaikoji, Hyuga-shi, Miyazaki 883-0021" },
    lat: null, lng: null,
    phone: "0982-66-6120",
    website: "https://swell-gh.co.jp/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "ゲストハウス併設のカフェ。屋外シャワーあり。",
      en: "Guesthouse with an attached cafe. Outdoor shower available.",
    },
    tags: null,
    sources: ["https://swell-gh.co.jp/"],
  },
  {
    slug: "guest-house-goofy",
    category: ["stay"],
    area: "hyuga",
    name: { ja: "ゲストハウスグーフィー", en: "Guest House Goofy" },
    address: { ja: "宮崎県日向市大字幸脇569番イ", en: "569-i Sachiwaki, Hyuga-shi, Miyazaki 889-1112" },
    lat: null, lng: null,
    phone: "090-3752-2149",
    website: "https://www.guest-house-goofy.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "金ヶ浜から350m、お倉ヶ浜まで車で5分。ボードスタンド、ウェットスーツ乾燥ラック、屋外シャワーあり。2019年営業開始。",
      en: "350 m from Kanegahama; five minutes by car to Okuragahama. Board stands, wetsuit-drying racks, and outdoor showers. Open since 2019.",
    },
    tags: null,
    sources: ["https://www.guest-house-goofy.com/"],
  },
  {
    slug: "pumping-surf",
    category: ["stay"],
    area: "hyuga",
    name: { ja: "ゲストハウス Pumping Surf", en: "Guest House Pumping Surf" },
    address: { ja: "宮崎県日向市平岩10876-15", en: "10876-15 Hiraiwa, Hyuga-shi, Miyazaki 883-0022" },
    lat: null, lng: null,
    phone: "0982-95-7311",
    website: "http://pumpingsurf.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "お倉ヶ浜まで徒歩3分。無料の自転車、BBQ、南日向駅からの無料送迎あり。",
      en: "Three-minute walk to Okuragahama. Free bikes, BBQ, and free shuttle from Minami-Hyuga Station.",
    },
    tags: null,
    sources: ["http://pumpingsurf.com/"],
  },
  {
    slug: "n-tribe",
    category: ["stay"],
    area: "nichinan",
    name: { ja: "n'tribe（フリーダム内）", en: "n'tribe (inside Freedom Surfshop)" },
    address: { ja: "宮崎県日南市平山2318-2", en: "2318-2 Hirayama, Nichinan-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0987-23-6873",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "フリーダムサーフショップ内のロッジ。8室、最大32名。素泊まり。",
      en: "Lodge inside Freedom Surf Shop. Eight rooms for up to 32 guests. Room-only.",
    },
    tags: null,
    sources: ["https://www.kankou-nichinan.jp/tourisms/711/"],
  },
  {
    slug: "minshuku-koigaura",
    category: ["stay"],
    area: "kushima",
    name: { ja: "民宿恋ヶ浦", en: "Minshuku Koigaura" },
    address: { ja: "宮崎県串間市大納2030", en: "2030 Ono, Kushima-shi, Miyazaki 888-0221" },
    lat: null, lng: null,
    phone: "0987-76-1631",
    website: "https://koigaurashokudo.wixsite.com/koigaura",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "恋ヶ浦の真向かいにある民宿。素泊まり。基本的なサーフ用品の販売とレンタルもあり。",
      en: "Minshuku directly opposite Koigaura. Room-only, with basic surf gear sales and rentals.",
    },
    tags: null,
    sources: ["https://koigaurashokudo.wixsite.com/koigaura"],
  },
  {
    slug: "minshuku-misakisou",
    category: ["stay"],
    area: "miyazaki-shi",
    name: { ja: "民宿みさき荘", en: "Minshuku Misaki-sou" },
    address: { ja: "宮崎県宮崎市青島1-5-4", en: "1-5-4 Aoshima, Miyazaki-shi, Miyazaki 889-2162" },
    lat: null, lng: null,
    phone: "0985-65-0038",
    website: "http://www.misakisou.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "こどものくに前のサーフブレイクの真ん前にある民宿。割引航空券付きのサーフトリップパックあり。",
      en: "Minshuku facing the Kodomo-no-Kuni surf break. Surf-trip packages with discounted airfare available.",
    },
    tags: null,
    sources: ["http://www.misakisou.com/index.html"],
  },
  {
    slug: "sea-dweller-aoshima",
    category: ["stay"],
    area: "miyazaki-shi",
    name: { ja: "お宿 海の居住者 SEA-DWELLER", en: "SEA-DWELLER Aoshima" },
    address: { ja: "宮崎県宮崎市青島6-8-13", en: "6-8-13 Aoshima, Miyazaki-shi, Miyazaki 889-2162" },
    lat: null, lng: null,
    phone: "0985-66-0740",
    website: "https://www.seadweller-aoshima.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "青島の宿。木崎浜サーフポイントをアクティビティとして紹介している。",
      en: "Lodging in Aoshima. The owners' site lists the Kizakihama surf point among activities.",
    },
    tags: null,
    sources: ["https://www.seadweller-aoshima.com/activity/446839.html"],
  },
  {
    slug: "ana-holiday-inn-resort-miyazaki",
    category: ["stay"],
    area: "miyazaki-shi",
    name: { ja: "ANA ホリデイ・イン リゾート 宮崎", en: "ANA Holiday Inn Resort MIYAZAKI" },
    address: { ja: "宮崎県宮崎市青島1-16-1", en: "1-16-1 Aoshima, Miyazaki-shi, Miyazaki 889-2162" },
    lat: null, lng: null,
    phone: "0985-65-1555",
    website: "https://www.anahirmiyazaki.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "青島ビーチから徒歩圏内のリゾートホテル。館内にムラサキスポーツ青島（サブスク型サーフ用品）あり。",
      en: "Resort hotel within walking distance of Aoshima Beach. In-house Murasaki Sports Aoshima offers subscription-based surf gear.",
    },
    tags: null,
    sources: ["https://www.anahirmiyazaki.com/"],
  },
];

function ensureDir(dir: string): void {
  fs.mkdirSync(dir, { recursive: true });
}

function main(): void {
  ensureDir(OUT);
  let ok = 0;
  const failures: { slug: string; issues: string[] }[] = [];
  for (const s of seeds) {
    const full: Listing = {
      slug: s.slug,
      genre: "surf",
      category: s.category,
      area: s.area,
      name: s.name,
      address: s.address,
      lat: s.lat,
      lng: s.lng,
      phone: s.phone,
      website: s.website,
      google_maps_url: s.google_maps_url,
      hours: s.hours,
      price: s.price,
      description: s.description,
      tags: s.tags,
      sources: s.sources,
      verified_at: s.verified_at ?? TODAY,
      status: s.status ?? "open",
    };
    const parsed = listingSchema.safeParse(full);
    if (!parsed.success) {
      failures.push({
        slug: s.slug,
        issues: parsed.error.issues.map((i) => `${i.path.join(".")}: ${i.message}`),
      });
      continue;
    }
    const file = path.join(OUT, `${s.slug}.json`);
    fs.writeFileSync(file, JSON.stringify(parsed.data, null, 2) + "\n", "utf8");
    ok += 1;
  }
  console.log(`wrote ${ok} listing(s) to ${OUT}`);
  if (failures.length > 0) {
    console.error(`FAIL — ${failures.length} listing(s) invalid:`);
    for (const f of failures) {
      console.error(`  ${f.slug}:`);
      for (const i of f.issues) console.error(`    - ${i}`);
    }
    process.exit(1);
  }
}

main();
