import fs from "node:fs";
import path from "node:path";
import { listingSchema, type Listing } from "../lib/types";

const TODAY = "2026-09-15";
const ROOT = process.cwd();
const OUT = path.join(ROOT, "data", "listings", "camp");

type Seed = Omit<Listing, "genre" | "verified_at" | "status" | "features"> & {
  status?: Listing["status"];
  verified_at?: string;
  features?: string[];
};

const seeds: Seed[] = [
  // =============================================================
  // CAMPSITES
  // =============================================================
  {
    slug: "miyazaki-shirahama",
    category: ["campsite"],
    area: "miyazaki-shi",
    name: { ja: "宮崎白浜オートキャンプ場", en: "Miyazaki Shirahama Auto Camp" },
    address: { ja: "宮崎県宮崎市大字折生迫上白浜6600-1", en: "6600-1 Kami-Shirahama, Orio-zako, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0985-65-2020",
    website: "https://aoshima-camp.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "宮崎市南部・白浜海岸に面した市営のオートキャンプ場。青島から車で近い。",
      en: "City-run auto campsite facing Shirahama Beach in south Miyazaki. Short drive from Aoshima.",
    },
    tags: null,
    sources: ["https://www.city.miyazaki.miyazaki.jp/institution/list/item43/"],
  },
  {
    slug: "tsubakiyama-camp",
    category: ["campsite"],
    area: "miyazaki-shi",
    name: { ja: "椿山キャンプ場", en: "Tsubakiyama Campground" },
    address: { ja: "宮崎県宮崎市大字鏡洲4343-1", en: "4343-1 Kagamizu, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0985-58-0896",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "宮崎市の山あいにある市営キャンプ場。椿山森林公園内。",
      en: "City-run campsite in the hills west of Miyazaki, inside Tsubakiyama Forest Park.",
    },
    tags: null,
    sources: ["https://www.city.miyazaki.miyazaki.jp/institution/list/item10/"],
  },
  {
    slug: "aoshima-picnic-club",
    category: ["campsite", "rvpark", "carstay"],
    area: "miyazaki-shi",
    name: { ja: "AOSHIMA PICNIC CLUB", en: "Aoshima Picnic Club" },
    address: { ja: "宮崎県宮崎市加江田7275-1 こどものくに内", en: "Inside Kodomo-no-Kuni, 7275-1 Kaeda, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0985-77-6858",
    website: "https://aoshimapicnicclub.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "こどものくに内のキャンプ場・RVパーク併設。青島唯一のRVパーク認定で、車中泊も利用可。",
      en: "Camp and RV park inside Kodomo-no-Kuni. Only JRVA-certified RV park in Aoshima, with car-stay stalls too.",
    },
    tags: null,
    sources: [
      "https://aoshimapicnicclub.com/",
      "https://www.kurumatabi.com/park/rvpark/1255.html",
      "https://aoshimapicnicclub.com/stay/rv-park",
    ],
  },
  {
    slug: "hokedake-park-camp",
    category: ["campsite"],
    area: "kunitomi",
    name: { ja: "法華嶽公園キャンプ場", en: "Hokedake Park Campground" },
    address: { ja: "宮崎県東諸県郡国富町大字深年4106-18", en: "4106-18 Fukatoshi, Kunitomi-cho, Higashi-Morokata-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0985-78-1943",
    website: "http://www.town.kunitomi.miyazaki.jp/main/tourism/tourism_nature/hokedake/page001388.html",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "国富町の法華嶽公園にある町営キャンプ場。桜と紅葉の名所。",
      en: "Town-run campsite in Hokedake Park, Kunitomi. Known for cherry blossoms and autumn colours.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1299"],
  },
  {
    slug: "riverside-aya-autocamp",
    category: ["campsite", "onsen"],
    area: "aya",
    name: { ja: "リバーサイド綾オートキャンプ場（綾川荘）", en: "Riverside Aya Auto Camp (Ayakawaso)" },
    address: { ja: "宮崎県東諸県郡綾町北俣3765", en: "3765 Kitamata, Aya-cho, Higashi-Morokata-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0570-008-015",
    website: "https://ayakawasou.com/",
    google_maps_url: null,
    hours: {
      ja: "温泉入浴 10:00〜21:00",
      en: "Onsen 10:00–21:00",
    },
    price: null,
    description: {
      ja: "綾北川沿いのオートキャンプ場。同じ敷地内の綾川荘で日帰り入浴もできる。",
      en: "Auto camp along the Ayakita River. Ayakawaso on the same site offers day-use onsen.",
    },
    tags: null,
    sources: ["https://ayakawasou.com/facility"],
  },
  {
    slug: "hinamori-autocamp",
    category: ["campsite"],
    area: "kobayashi",
    name: { ja: "ひなもりオートキャンプ場", en: "Hinamori Auto Camp" },
    address: { ja: "宮崎県小林市細野字山中之前5739-14", en: "5739-14 Hosono Yamanaka-no-mae, Kobayashi-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0984-23-8100",
    website: "https://www.hinamori.jp/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "霧島山の麓、標高約630mにある県立のオートキャンプ場。夏でも涼しい。",
      en: "Prefectural auto campsite at ~630 m at the foot of the Kirishima range. Stays cool in summer.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1313"],
  },
  {
    slug: "yatake-kogen-belton",
    category: ["campsite"],
    area: "ebino",
    name: { ja: "矢岳高原ベルトンオートキャンプ場", en: "Yatake Kogen Belton Auto Camp" },
    address: { ja: "宮崎県えびの市大字西川北1377-2", en: "1377-2 Nishikawakita, Ebino-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0984-37-1033",
    website: "https://wakuwakucamp.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "えびの市の矢岳高原にあるオートキャンプ場。展望台からえびの盆地を見渡せる。",
      en: "Auto camp on the Yatake Highlands in Ebino. The lookout takes in the Ebino basin.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1314"],
  },
  {
    slug: "oujibaru-koen-camp",
    category: ["campsite"],
    area: "takaharu",
    name: { ja: "皇子原公園キャンプ場", en: "Ouji-baru Park Camp" },
    address: { ja: "宮崎県西諸県郡高原町大字蒲牟田3-251", en: "3-251 Gamuda, Takaharu-cho, Nishi-Morokata-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0984-42-3393",
    website: "https://oujibaru-koen.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "高千穂峰の登山口近く、高原町の皇子原公園にあるキャンプ場。",
      en: "Campsite in Ouji-baru Park in Takaharu, near the trailhead for Takachiho-no-Mine.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1316"],
  },
  {
    slug: "miike-no-yu-autocamp",
    category: ["campsite", "onsen"],
    area: "takaharu",
    name: { ja: "御池の湯オートキャンプ場", en: "Miike-no-Yu Auto Camp" },
    address: { ja: "宮崎県西諸県郡高原町大字蒲牟田7412-2", en: "7412-2 Gamuda, Takaharu-cho, Nishi-Morokata-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0984-42-4088",
    website: "https://miikenoyu-camp.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "御池の湖畔、天然温泉が併設されたオートキャンプ場。",
      en: "Auto camp on the shore of Lake Miike, with an on-site natural hot spring.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1317"],
  },
  {
    slug: "oku-kirishima-miike-camp",
    category: ["campsite"],
    area: "takaharu",
    name: { ja: "奥霧島御池キャンプ村", en: "Oku-Kirishima Miike Camp Village" },
    address: { ja: "宮崎県西諸県郡高原町大字蒲牟田長尾", en: "Nagao, Gamuda, Takaharu-cho, Nishi-Morokata-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0984-42-4038",
    website: "https://lake-miike.com/camp/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "御池の湖畔にあるキャンプ場。テントサイトとバンガロー。",
      en: "Lakeside campground at Lake Miike, with tent sites and bungalows.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1318"],
  },
  {
    slug: "snow-peak-miyakonojo",
    category: ["campsite"],
    area: "miyakonojo",
    name: { ja: "スノーピーク都城キャンプフィールド（関之尾公園）", en: "Snow Peak Miyakonojo Camp Field" },
    address: { ja: "宮崎県都城市関之尾町6615-2", en: "6615-2 Sekinoo-cho, Miyakonojo-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0986-38-2460",
    website: "https://sbs.snowpeak.co.jp/miyakonojo/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "関之尾滝のそば、都城市とスノーピークの官民連携のキャンプフィールド。",
      en: "Camp field beside Sekinoo Falls, run jointly by Miyakonojo City and Snow Peak.",
    },
    tags: null,
    sources: ["https://www.city.miyakonojo.miyazaki.jp/soshiki/3/61718.html"],
  },
  {
    slug: "kannonike-koen",
    category: ["campsite", "onsen"],
    area: "miyakonojo",
    name: { ja: "観音池公園", en: "Kannonike Park" },
    address: { ja: "宮崎県都城市高城町石山4195", en: "4195 Ishiyama, Takajo-cho, Miyakonojo-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0986-58-6139",
    website: "https://miyakonojo-bonchi.com/kannonike-park/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "都城市高城町の複合施設。キャンプ場、プール、温泉「観音さくらの里」を持つ。",
      en: "Complex in Takajo, Miyakonojo. Campground, pool, and the Kannon-sakura-no-Sato hot spring.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1091"],
  },
  {
    slug: "aoidake",
    category: ["campsite", "rvpark", "carstay", "onsen"],
    area: "miyakonojo",
    name: { ja: "青井岳温泉・青井岳キャンプ場", en: "Aoidake Onsen & Camp" },
    address: { ja: "宮崎県都城市山之口町山之口2123", en: "2123 Yamanokuchi, Yamanokuchi-cho, Miyakonojo-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0986-57-2177",
    website: "https://aoidake.com/",
    google_maps_url: null,
    hours: {
      ja: "温泉 7:00〜22:00（最終受付21:00）年中無休",
      en: "Onsen 7:00–22:00 (last entry 21:00), open year round",
    },
    price: null,
    description: {
      ja: "青井岳の温泉と、同じ敷地のキャンプ場・RVパーク・車中泊エリア。RVサイトは電源・水場あり。",
      en: "Aoidake hot spring with an on-site campsite, JRVA RV park, and car-stay bays. RV sites have power and water.",
    },
    tags: null,
    sources: [
      "https://aoidake.com/camp/",
      "https://www.kurumatabi.com/park/rvpark/1454.html",
      "https://www.kanko-miyazaki.jp/spot/2384",
    ],
  },
  {
    slug: "takamatsu-camp-park",
    category: ["campsite", "carstay"],
    area: "kushima",
    name: { ja: "高松キャンプ公園", en: "Takamatsu Camp Park" },
    address: { ja: "宮崎県串間市大字高松1233-6", en: "1233-6 Takamatsu, Kushima-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0987-55-1126",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "高松海水浴場のとなり。フリー、オート、キャンピングカー、バーベキューの各サイトがある。",
      en: "Next to Takamatsu Beach. Free, auto, campervan, and BBQ sites available.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1323"],
  },
  {
    slug: "toi-misaki-south-lighthouse",
    category: ["campsite"],
    area: "kushima",
    name: { ja: "都井岬南灯台キャンプ場", en: "Toi Misaki South Lighthouse Campground" },
    address: { ja: "宮崎県串間市大字大納57-イ", en: "57-i Ono, Kushima-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "都井岬の南、灯台の近くにあるキャンプ場。周辺には野生馬の岬馬。",
      en: "Campsite near the lighthouse on Cape Toi, home to the wild Misaki horses.",
    },
    tags: null,
    sources: ["https://www.nap-camp.com/miyazaki/15962"],
  },
  {
    slug: "sakaematsu-beach-camp",
    category: ["campsite"],
    area: "nichinan",
    name: { ja: "栄松ビーチ・キャンプ場", en: "Sakaematsu Beach Camp" },
    address: { ja: "宮崎県日南市南郷町中村乙4178-1", en: "4178-1 Nakamura-otsu, Nango-cho, Nichinan-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0987-64-0002",
    website: "https://sakaematsu-beach.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "南郷の栄松ビーチに面したオートキャンプ場。海水浴とキャンプが同じ場所で楽しめる。",
      en: "Auto camp facing Sakaematsu Beach in Nango. Swimming and camping in one spot.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1320"],
  },
  {
    slug: "hachinosu-park-camp",
    category: ["campsite"],
    area: "nichinan",
    name: { ja: "蜂之巣公園キャンプ場", en: "Hachinosu Park Camp" },
    address: { ja: "宮崎県日南市北郷町郷之原甲2850-1", en: "2850-1 Gonohara-ko, Kitago-cho, Nichinan-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0987-55-3828",
    website: "https://gonharu.info/hachinosu/index.html",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "日南市北郷、酒谷川ぞいの町営キャンプ場。夏は川遊びができる。",
      en: "Riverside town-run camp along the Sakatani in Kitago, Nichinan. River play in summer.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1321"],
  },
  {
    slug: "sakatani-camp",
    category: ["campsite"],
    area: "nichinan",
    name: { ja: "酒谷キャンプ場", en: "Sakatani Campground" },
    address: { ja: "宮崎県日南市大字酒谷甲3360-2", en: "3360-2 Sakatani-ko, Nichinan-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0987-26-1216",
    website: "https://michinoeki-sakatani.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "道の駅酒谷に隣接するキャンプ場。買い出しは道の駅で。",
      en: "Campground next to Michi-no-Eki Sakatani. Provisions available at the roadside station.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1322"],
  },
  {
    slug: "shio-no-mori",
    category: ["campsite"],
    area: "nichinan",
    name: { ja: "潮の杜キャンプ場", en: "Shio-no-Mori Camp" },
    address: { ja: "宮崎県日南市富士4028-4", en: "4028-4 Fuji, Nichinan-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "旧小学校を活用した日南のキャンプ場。",
      en: "Nichinan campsite in a repurposed former elementary school.",
    },
    tags: null,
    sources: ["https://www.nap-camp.com/miyazaki/13904"],
  },
  {
    slug: "welvillage-campers-ibii",
    category: ["campsite"],
    area: "nichinan",
    name: { ja: "ウエルビレッジ・キャンパーズ伊比井", en: "Wel-Village Campers Ibii" },
    address: { ja: "宮崎県日南市伊比井1689", en: "1689 Ibii, Nichinan-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "伊比井駅ちかくの日南のキャンプ場。海まで歩ける。",
      en: "Coastal camp in Nichinan near JR Ibii Station, within walking distance of the sea.",
    },
    tags: null,
    sources: ["https://www.nap-camp.com/miyazaki/15809"],
  },
  {
    slug: "futago-camp",
    category: ["campsite"],
    area: "nishimera",
    name: { ja: "双子キャンプ村オートキャンプ場", en: "Futago Camp Village Auto Camp" },
    address: { ja: "宮崎県児湯郡西米良村村所字広瀬264-1", en: "264-1 Hirose, Murasho, Nishimera-son, Koyu-gun, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "西米良村のオートキャンプ場。西米良温泉ゆた〜とに近い。",
      en: "Auto camp in Nishimera Village, close to Yutato hot spring.",
    },
    tags: null,
    sources: ["https://www.nap-camp.com/miyazaki/10492"],
  },
  {
    slug: "osuzu-camp",
    category: ["campsite"],
    area: "tsuno",
    name: { ja: "尾鈴キャンプ場", en: "Osuzu Campground" },
    address: { ja: "宮崎県児湯郡都農町（尾鈴県立自然公園内）", en: "Osuzu Prefectural Natural Park, Tsuno-cho, Koyu-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0983-25-5712",
    website: "https://www.tsunokanko.com/contents/camp.html",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "尾鈴県立自然公園の中にある町営キャンプ場。利用料の支払いはJR都農駅の観光協会で。",
      en: "Town-run camp inside Osuzu Prefectural Natural Park. Pay fees at the tourism office at JR Tsuno Station.",
    },
    tags: null,
    sources: ["https://www.tsunokanko.com/contents/camp.html"],
  },
  {
    slug: "hyuga-sunpark-autocamp",
    category: ["campsite"],
    area: "hyuga",
    name: { ja: "日向サンパークオートキャンプ場", en: "Hyuga Sun Park Auto Camp" },
    address: { ja: "宮崎県日向市幸脇303-5", en: "303-5 Sachiwaki, Hyuga-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "日向市南部・幸脇のオートキャンプ場。海に近い。",
      en: "Auto camp in Sachiwaki, southern Hyuga. Close to the coast.",
    },
    tags: null,
    sources: ["https://www.nap-camp.com/miyazaki/10524"],
  },
  {
    slug: "dog-run-camp-suzu",
    category: ["campsite", "rvpark"],
    area: "hyuga",
    name: { ja: "DOG RUN & CAMP FIELD SUZU", en: "Dog Run & Camp Field Suzu" },
    address: { ja: "宮崎県日向市日知屋682-192", en: "682-192 Hichiya, Hyuga-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-52-4092",
    website: "https://dogandcampsuzu.studio.site",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "貸切キャンプ場とドッグランに、JRVA認定RVパークを併設。",
      en: "Private camp with dog run and a JRVA-certified RV park on the same site.",
    },
    tags: null,
    sources: ["https://www.kurumatabi.com/park/rvpark/1363.html"],
  },
  {
    slug: "makisui-park",
    category: ["campsite"],
    area: "hyuga",
    name: { ja: "牧水公園", en: "Bokusui Park" },
    address: { ja: "宮崎県日向市東郷町坪谷1267", en: "1267 Tsuboya, Togo-cho, Hyuga-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "歌人・若山牧水の生家近くにある日向市東郷町の公園キャンプ場。",
      en: "Park campsite in Togo, Hyuga, near the birthplace of the poet Wakayama Bokusui.",
    },
    tags: null,
    sources: ["https://www.nap-camp.com/miyazaki/10525"],
  },
  {
    slug: "ishinamigawa-camp",
    category: ["campsite"],
    area: "hyuga",
    name: { ja: "石並川キャンプ場", en: "Ishinamigawa Campground" },
    address: { ja: "宮崎県日向市美々津町", en: "Mimitsu-cho, Hyuga-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-58-1080",
    website: "https://ishinami.rdy.jp/",
    google_maps_url: null,
    hours: {
      ja: "夏期のみ営業（7月〜9月）",
      en: "Open in summer only (July–September)",
    },
    price: null,
    description: {
      ja: "石並川ぞいの市営キャンプ場。夏だけ営業。川あそびができる。",
      en: "Riverside city-run camp along the Ishinamigawa. Open only in summer. River play on site.",
    },
    tags: null,
    sources: ["https://ishinami.rdy.jp/"],
  },
  {
    slug: "shimoso-hamayuu",
    category: ["campsite"],
    area: "nobeoka",
    name: { ja: "下阿蘇ビーチ「浜木綿村」ソレイユ・ルヴァン", en: "Shimo-Aso Beach Hamayuu-mura / Soleil Levant" },
    address: { ja: "宮崎県延岡市北浦町古江3337-1", en: "3337-1 Furue, Kitaura-cho, Nobeoka-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-45-3811",
    website: "https://michinoeki-kitaura.com/cms/soleil-levant/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "道の駅北浦の中にあるビーチキャンプ場。下阿蘇ビーチは日本の海水浴場100選。",
      en: "Beach camp within Michi-no-Eki Kitaura. Shimo-Aso Beach is on Japan's Top 100 Beaches list.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1305"],
  },
  {
    slug: "sumie-family-village",
    category: ["campsite"],
    area: "nobeoka",
    name: { ja: "須美江家族旅行村", en: "Sumie Family Travel Village" },
    address: { ja: "宮崎県延岡市須美江町1450-2", en: "1450-2 Sumie-cho, Nobeoka-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-43-0201",
    website: "http://sunbeach-sumie.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "須美江海水浴場に隣接した延岡市の家族向けキャンプ場。プールや水族館もある。",
      en: "Family-oriented Nobeoka campsite next to Sumie Beach. Pool and small aquarium on site.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1306"],
  },
  {
    slug: "shikakawa-camp",
    category: ["campsite"],
    area: "nobeoka",
    name: { ja: "鹿川キャンプ場", en: "Shikakawa Campground" },
    address: { ja: "宮崎県延岡市北方町上鹿川申986-45", en: "986-45 Kami-Shikakawa, Kitakata-cho, Nobeoka-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "延岡市北方町、九州脊梁の山あいにある山岳系キャンプ場。",
      en: "Mountain camp in Kitakata, Nobeoka, in the heart of the Kyushu Spine range.",
    },
    tags: null,
    sources: ["https://www.nap-camp.com/miyazaki/10485"],
  },
  {
    slug: "horigawa-camp",
    category: ["campsite"],
    area: "nobeoka",
    name: { ja: "祝子川キャンプ場", en: "Horigawa Campground" },
    address: { ja: "宮崎県延岡市北川町川内名10825-5", en: "10825-5 Kawachimyo, Kitagawa-cho, Nobeoka-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "080-5816-6290",
    website: "https://hourigawa-camp.jimdosite.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "祝子川ぞい、大崩山の登山口にちかいキャンプ場。",
      en: "Riverside campsite on the Horigawa, close to the Ogatayama trailhead.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1304"],
  },
  {
    slug: "otoshima-camp",
    category: ["campsite"],
    area: "kadogawa",
    name: { ja: "無人島「乙島」キャンプ場", en: "Otoshima Uninhabited Island Camp" },
    address: { ja: "宮崎県東臼杵郡門川町門川尾末", en: "Kadogawa-Suenaga, Kadogawa-cho, Higashi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-57-4110",
    website: "https://kadogawa-ta.com/otojima/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "門川湾の無人島にある船で渡るキャンプ場。予約は門川町観光協会で。",
      en: "Boat-access camp on an uninhabited island in Kadogawa Bay. Book via the Kadogawa Tourism Association.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1310"],
  },
  {
    slug: "hinokage-camp-mura",
    category: ["campsite"],
    area: "hinokage",
    name: { ja: "日之影キャンプ村", en: "Hinokage Camp Village" },
    address: { ja: "宮崎県西臼杵郡日之影町七折6164", en: "6164 Nanaori, Hinokage-cho, Nishi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-87-2820",
    website: "https://hinokage-camp.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "日之影町の五ヶ瀬川沿いのキャンプ場。テントサイトとバンガロー。",
      en: "Riverside camp along the Gokase in Hinokage, with tent sites and bungalows.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1303"],
  },
  {
    slug: "autocamp-takachiho",
    category: ["campsite", "rvpark"],
    area: "takachiho",
    name: { ja: "オートキャンプ場in高千穂", en: "Autocamp in Takachiho" },
    address: { ja: "宮崎県西臼杵郡高千穂町三田井3121-2", en: "3121-2 Mitai, Takachiho-cho, Nishi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-82-2351",
    website: "https://www.autocamp-takachiho.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "高千穂の中心部から車で約5分。同じ敷地にJRVA認定「RVパーク高千穂」を併設。",
      en: "About 5 minutes by car from central Takachiho. Includes the JRVA-certified RV Park Takachiho.",
    },
    tags: null,
    sources: [
      "https://www.kanko-miyazaki.jp/spot/1300",
      "https://www.kurumatabi.com/park/rvpark/816.html",
    ],
  },
  {
    slug: "shikimibaru-sukoyaka",
    category: ["campsite"],
    area: "takachiho",
    name: { ja: "四季見原すこやかの森キャンプ場", en: "Shikimibaru Sukoyaka-no-Mori Camp" },
    address: { ja: "宮崎県西臼杵郡高千穂町大字上野3751-722", en: "3751-722 Ueno, Takachiho-cho, Nishi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-82-2151",
    website: "https://www.town-takachiho.jp/top/soshiki/kikakukanko/2/3/3/303.html",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "標高1,200mにある町営キャンプ場。九州でもっとも高い場所のキャンプ場のひとつ。",
      en: "Town-run camp at 1,200 m, one of the highest-elevation campsites in Kyushu.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1301"],
  },
  {
    slug: "gokase-no-sato",
    category: ["campsite"],
    area: "gokase",
    name: { ja: "五ヶ瀬の里キャンプ村", en: "Gokase-no-Sato Camp Village" },
    address: { ja: "宮崎県西臼杵郡五ヶ瀬町三ヶ所141-1", en: "141-1 Sangasho, Gokase-cho, Nishi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "090-4475-5005",
    website: "https://www.gokasens.org/camp/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "五ヶ瀬町にあるゲストハウス併設のキャンプ場。",
      en: "Camp village with an attached guesthouse in Gokase.",
    },
    tags: null,
    sources: ["https://www.gokasens.org/camp/"],
  },
  {
    slug: "kataraustand",
    category: ["campsite"],
    area: "gokase",
    name: { ja: "カタラウスタンド", en: "Kataraustand" },
    address: { ja: "宮崎県西臼杵郡五ヶ瀬町三ヶ所8282-7", en: "8282-7 Sangasho, Gokase-cho, Nishi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "五ヶ瀬町の川ぞいのフリーサイト。ペット可。",
      en: "Riverside free-site camp in Gokase. Pets welcome.",
    },
    tags: null,
    sources: ["https://www.nap-camp.com/miyazaki/16860"],
  },
  {
    slug: "ikenokubo-green-park",
    category: ["campsite"],
    area: "morotsuka",
    name: { ja: "池の窪グリーンパーク", en: "Ikenokubo Green Park" },
    address: { ja: "宮崎県東臼杵郡諸塚村家代3574-2", en: "3574-2 Iejiro, Morotsuka-son, Higashi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-65-0526",
    website: "https://www.morotsuka-tourism.jp/spot/ikenokubo/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "標高約800mにある諸塚村のキャンプ場。バンガローとテントサイト。",
      en: "Morotsuka Village campsite at around 800 m elevation, with bungalows and tent sites.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1049"],
  },
  {
    slug: "keiryu-no-sato",
    category: ["campsite"],
    area: "morotsuka",
    name: { ja: "諸塚山 渓流の里", en: "Morotsuka-yama Keiryu-no-Sato" },
    address: { ja: "宮崎県東臼杵郡諸塚村七ツ山8650-2", en: "8650-2 Nanatsuyama, Morotsuka-son, Higashi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "諸塚山ぞいの渓流にあるキャンプ場。",
      en: "Riverside campground along a stream near Mount Morotsuka.",
    },
    tags: null,
    sources: ["https://www.nap-camp.com/miyazaki/10513"],
  },
  {
    slug: "hietsuki-no-sato",
    category: ["campsite"],
    area: "shiiba",
    name: { ja: "BASE CAMP shiiba", en: "Base Camp Shiiba" },
    address: { ja: "宮崎県東臼杵郡椎葉村大字下福良1-2", en: "1-2 Shimo-fukura, Shiiba-son, Higashi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-67-2722",
    website: "https://www.shiibakanko.jp/tourism/play/play3",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "椎葉村のダム湖ぞい、コテージ併設のキャンプ場。",
      en: "Shiiba Village camp with cottages beside the reservoir.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1307"],
  },
  {
    slug: "yatate-kogen-shiiba",
    category: ["campsite"],
    area: "shiiba",
    name: { ja: "矢立高原キャンプ場", en: "Yatate Kogen Campground" },
    address: { ja: "宮崎県東臼杵郡椎葉村大河内字矢立", en: "Yatate, Ookawachi, Shiiba-son, Higashi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0983-38-1440",
    website: "https://www.shiibakanko.jp/tourism/play/play3",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "椎葉村の高原にあるキャンプ場。",
      en: "Highland campsite in Shiiba Village.",
    },
    tags: null,
    sources: ["https://www.shiibakanko.jp/tourism/play/play3"],
  },
  {
    slug: "mizushidani-furusato-mura",
    category: ["campsite"],
    area: "misato",
    name: { ja: "水清谷ふるさと村オートキャンプ場", en: "Mizushidani Furusato-mura Auto Camp" },
    address: { ja: "宮崎県東臼杵郡美郷町南郷水清谷47", en: "47 Mizushidani, Nango, Misato-cho, Higashi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-59-0613",
    website: "https://www.visit-misato.jp/infopage/camp-mizushidani/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "美郷町南郷の川ぞいのオートキャンプ場。",
      en: "Riverside auto camp in Nango, Misato.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1308"],
  },
  {
    slug: "misato-lakeland",
    category: ["campsite", "onsen"],
    area: "misato",
    name: { ja: "美郷レイクランド（石峠レイクランド）", en: "Misato Lakeland" },
    address: { ja: "宮崎県東臼杵郡美郷町西郷田代5812-1", en: "5812-1 Tashiro, Saigo, Misato-cho, Higashi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-68-2222",
    website: "https://i-lakeland.jp/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "耳川ダム湖ぞいの複合施設。宿泊、キャンプ、温泉「耳川の湯」がある。",
      en: "Lakeside complex on the Mimikawa reservoir. Lodging, camping, and the Mimikawa-no-Yu onsen.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1134"],
  },
  {
    slug: "sky-lodge-ginga",
    category: ["campsite"],
    area: "misato",
    name: { ja: "スカイロッジ銀河村", en: "Sky Lodge Ginga Village" },
    address: { ja: "宮崎県東臼杵郡美郷町北郷宇納間7527-17", en: "7527-17 Unama, Kitago, Misato-cho, Higashi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "美郷町北郷、標高約900mの山あいのロッジとキャンプ場。",
      en: "Mountain lodges and campsite at around 900 m in Kitago, Misato.",
    },
    tags: null,
    sources: ["https://www.nap-camp.com/miyazaki/10519"],
  },
  {
    slug: "oseri-taki-camp",
    category: ["campsite"],
    area: "misato",
    name: { ja: "おせりの滝キャンプ場", en: "Oseri-no-Taki Camp" },
    address: { ja: "宮崎県東臼杵郡美郷町西郷小原1040-1", en: "1040-1 Kohara, Saigo, Misato-cho, Higashi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "美郷町西郷、おせりの滝のそばのキャンプ場。",
      en: "Camp near Oseri Falls in Saigo, Misato.",
    },
    tags: null,
    sources: ["https://www.nap-camp.com/miyazaki/10516"],
  },

  // =============================================================
  // RV PARKS (standalone; those combined with campsite are above)
  // =============================================================
  {
    slug: "rvpark-takazaki",
    category: ["rvpark"],
    area: "miyakonojo",
    name: { ja: "RVパークたかざき", en: "RV Park Takazaki" },
    address: { ja: "宮崎県都城市高崎町大牟田1399 高崎パークゴルフ場", en: "Takazaki Park Golf Course, 1399 Omuta, Takazaki-cho, Miyakonojo-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0986-62-4448",
    website: "https://miyakonojo-bonchi.com",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "高崎パークゴルフ場に併設されたJRVA認定RVパーク。近くにラスパたかざき温泉。",
      en: "JRVA-certified RV park at Takazaki Park Golf Course. Laspa Takazaki onsen is nearby.",
    },
    tags: null,
    sources: ["https://www.kurumatabi.com/park/rvpark/629.html"],
  },
  {
    slug: "rvparksmart-meirin",
    category: ["rvpark"],
    area: "takanabe",
    name: { ja: "RVパークsmart 高鍋町めいりん公園", en: "RV Park smart Takanabe Meirin Park" },
    address: { ja: "宮崎県児湯郡高鍋町上江6884-1", en: "6884-1 Kamie, Takanabe-cho, Koyu-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "092-433-7370",
    website: "https://rvparksmart.jp/rv-smart/meirinspa.html",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "高鍋温泉めいりんの湯のそば、めいりん公園の駐車場に整備されたRVパークsmart。",
      en: "RV Park smart in the Meirin Park lot next to Takanabe Meirin-no-Yu onsen.",
    },
    tags: null,
    sources: ["https://www.kurumatabi.com/park/rvpark/599.html"],
  },
  {
    slug: "rvpark-kadogawa",
    category: ["rvpark"],
    area: "kadogawa",
    name: { ja: "RVパークかどがわ", en: "RV Park Kadogawa" },
    address: { ja: "宮崎県東臼杵郡門川町加草2333", en: "2333 Kagusa, Kadogawa-cho, Higashi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-68-1101",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "農海産物直売所に隣接する門川町のJRVA認定RVパーク。",
      en: "JRVA-certified RV park in Kadogawa, next to a produce and seafood direct sales shop.",
    },
    tags: null,
    sources: ["https://www.kurumatabi.com/park/rvpark/585.html"],
  },

  // =============================================================
  // ONSEN (standalone day-use; combined onsen+campsite are above)
  // =============================================================
  {
    slug: "konohana-no-yu",
    category: ["onsen"],
    area: "miyazaki-shi",
    name: { ja: "このはなの湯（宮崎市自然休養村センター）", en: "Konohana-no-Yu" },
    address: { ja: "宮崎県宮崎市大字加江田6896", en: "6896 Kaeda, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0985-65-1921",
    website: null,
    google_maps_url: null,
    hours: {
      ja: "10:00〜21:00（最終受付 20:30）",
      en: "10:00–21:00 (last entry 20:30)",
    },
    price: null,
    description: {
      ja: "宮崎市加江田にある市営の日帰り入浴施設。青島から車で近い。",
      en: "City-run day-use bathhouse in Kaeda, Miyazaki. Short drive from Aoshima.",
    },
    tags: null,
    sources: ["https://www.city.miyazaki.miyazaki.jp/culture/facilities/89165.html"],
  },
  {
    slug: "kadogawa-onsen-kokoro",
    category: ["onsen"],
    area: "kadogawa",
    name: { ja: "かどがわ温泉 心の杜", en: "Kadogawa Onsen Kokoro-no-Mori" },
    address: { ja: "宮崎県東臼杵郡門川町大字庵川1942", en: "1942 Iogawa, Kadogawa-cho, Higashi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-63-7780",
    website: "https://kadogawa-kokoronomori.com",
    google_maps_url: null,
    hours: {
      ja: "温泉 10:00〜21:00",
      en: "Onsen 10:00–21:00",
    },
    price: {
      ja: "大人 600円",
      en: "Adult 600 yen",
    },
    description: {
      ja: "門川町の日帰り温泉。海のそばで海鮮の食事もできる。",
      en: "Day-use hot spring in Kadogawa near the coast, with a seafood restaurant on site.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/2294"],
  },
  {
    slug: "hinokage-onsen-eki",
    category: ["onsen"],
    area: "hinokage",
    name: { ja: "日之影温泉駅", en: "Hinokage Onsen Eki" },
    address: { ja: "宮崎県西臼杵郡日之影町大字七折3235-5", en: "3235-5 Nanaori, Hinokage-cho, Nishi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-87-2690",
    website: "https://hinokagecho.com/hinokageonsen.html",
    google_maps_url: null,
    hours: {
      ja: "温泉 12:00〜20:30",
      en: "Onsen 12:00–20:30",
    },
    price: {
      ja: "大人 500円",
      en: "Adult 500 yen",
    },
    description: {
      ja: "旧高千穂鉄道の日之影駅を再利用した日帰り温泉施設。",
      en: "Day-use hot spring housed in the former Hinokage station of the Takachiho Railway.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1135"],
  },
  {
    slug: "nango-onsen-dontaro",
    category: ["onsen"],
    area: "misato",
    name: { ja: "南郷温泉 山霧（どんタロの湯）", en: "Nango Onsen Yamagiri (Dontaro-no-Yu)" },
    address: { ja: "宮崎県東臼杵郡美郷町南郷神門151-1", en: "151-1 Mikado, Nango, Misato-cho, Higashi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-59-0100",
    website: "http://www.nango-spa.co.jp/",
    google_maps_url: null,
    hours: {
      ja: "温泉 10:00〜20:00",
      en: "Onsen 10:00–20:00",
    },
    price: {
      ja: "大人 520円",
      en: "Adult 520 yen",
    },
    description: {
      ja: "美郷町南郷の日帰り温泉。山あいの静かな立地。",
      en: "Day-use hot spring in Nango, Misato, tucked into the hills.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1147"],
  },
  {
    slug: "hourigawa-bijin-no-yu",
    category: ["onsen"],
    area: "nobeoka",
    name: { ja: "祝子川温泉 美人の湯", en: "Horigawa Onsen Bijin-no-Yu" },
    address: { ja: "宮崎県延岡市北川町下赤", en: "Shimoaka, Kitagawa-cho, Nobeoka-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-23-3080",
    website: "https://www.city.nobeoka.miyazaki.jp/site/miryoku/1245.html",
    google_maps_url: null,
    hours: {
      ja: "10:00〜20:00",
      en: "10:00–20:00",
    },
    price: {
      ja: "大人（中学生以上） 520円",
      en: "Adult (middle school+) 520 yen",
    },
    description: {
      ja: "延岡市北川町の日帰り温泉。大崩山の登山帰りに寄れる。",
      en: "Day-use hot spring in Kitagawa, Nobeoka. Convenient stop after hiking Ogatayama.",
    },
    tags: null,
    sources: ["https://www.city.nobeoka.miyazaki.jp/site/miryoku/1245.html"],
  },
  {
    slug: "yutato-nishimera",
    category: ["onsen"],
    area: "nishimera",
    name: { ja: "西米良温泉 カリコボーズの湯 ゆた〜と", en: "Nishimera Onsen Yutato" },
    address: { ja: "宮崎県児湯郡西米良村大字村所260-6", en: "260-6 Murasho, Nishimera-son, Koyu-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0983-41-4126",
    website: "http://www.yutato.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "西米良村の中心にある日帰り温泉。カリコボーズという地元の妖怪が名前の由来。",
      en: "Day-use hot spring in central Nishimera, named after the local Karikobōzu folklore spirits.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1143"],
  },
  {
    slug: "kijo-onsen-yurara",
    category: ["onsen"],
    area: "kijo",
    name: { ja: "木城温泉館 湯らら", en: "Kijo Onsen-kan Yurara" },
    address: { ja: "宮崎県児湯郡木城町大字高城1403-1", en: "1403-1 Takajo, Kijo-cho, Koyu-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0983-32-2525",
    website: "http://service.kijo.jp/~yurara/index.html",
    google_maps_url: null,
    hours: {
      ja: "10:00〜21:00",
      en: "10:00–21:00",
    },
    price: {
      ja: "大人 600円",
      en: "Adult 600 yen",
    },
    description: {
      ja: "木城町の日帰り温泉。露天風呂と食事処あり。",
      en: "Day-use hot spring in Kijo, with an outdoor bath and a restaurant.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/2576"],
  },
  {
    slug: "sun-lupinus",
    category: ["onsen"],
    area: "shintomi",
    name: { ja: "新富町温泉健康センター サン・ルピナス", en: "Sun Lupinus" },
    address: { ja: "宮崎県児湯郡新富町三納代1859-1", en: "1859-1 Minoushiro, Shintomi-cho, Koyu-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0983-33-1000",
    website: "https://sun-lupinus.com/",
    google_maps_url: null,
    hours: {
      ja: "10:00〜22:00",
      en: "10:00–22:00",
    },
    price: {
      ja: "大人 500円",
      en: "Adult 500 yen",
    },
    description: {
      ja: "新富町のラジウム温泉。町営の日帰り施設。",
      en: "Municipal day-use radium hot spring in Shintomi.",
    },
    tags: null,
    sources: ["https://sun-lupinus.com/"],
  },
  {
    slug: "laspa-takazaki",
    category: ["onsen"],
    area: "miyakonojo",
    name: { ja: "都城たかざき温泉 ラスパたかざき", en: "Laspa Takazaki" },
    address: { ja: "宮崎県都城市高崎町大牟田1332-8", en: "1332-8 Omuta, Takazaki-cho, Miyakonojo-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0986-62-5526",
    website: "https://www.laspatakazaki.com/",
    google_maps_url: null,
    hours: {
      ja: "8:00〜21:00（最終受付 20:30）",
      en: "8:00–21:00 (last entry 20:30)",
    },
    price: null,
    description: {
      ja: "都城市高崎町の日帰り温泉。RVパークたかざきに近い。",
      en: "Day-use hot spring in Takazaki, Miyakonojo. Close to RV Park Takazaki.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/2565"],
  },
  {
    slug: "yupoppo-kakashi-no-sato",
    category: ["onsen"],
    area: "miyakonojo",
    name: { ja: "かかしの里 ゆぽっぽ", en: "Kakashi-no-Sato Yupoppo" },
    address: { ja: "宮崎県都城市山田町中霧島3340-2", en: "3340-2 Naka-Kirishima, Yamada-cho, Miyakonojo-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0986-64-3711",
    website: "https://miyakonojo-bonchi.com/yupoppo/",
    google_maps_url: null,
    hours: {
      ja: "月〜土 9:00〜22:00（最終受付 21:00）",
      en: "Mon–Sat 9:00–22:00 (last entry 21:00)",
    },
    price: null,
    description: {
      ja: "都城市山田町の日帰り温泉。かかしの里の複合施設内。",
      en: "Day-use hot spring in Yamada, Miyakonojo, part of the Kakashi-no-Sato complex.",
    },
    tags: null,
    sources: ["https://miyakonojo-bonchi.com/yupoppo/"],
  },
  {
    slug: "kannonsakura-no-sato",
    category: ["onsen"],
    area: "miyakonojo",
    name: { ja: "観音さくらの里", en: "Kannon-sakura-no-Sato" },
    address: { ja: "宮崎県都城市高城町石山4195", en: "4195 Ishiyama, Takajo-cho, Miyakonojo-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0986-29-2100",
    website: "https://miyakonojo-bonchi.com/kannonsakura/",
    google_maps_url: null,
    hours: null,
    price: {
      ja: "420円",
      en: "420 yen",
    },
    description: {
      ja: "観音池公園にある日帰り温泉。露天風呂を含む13種類の湯船。",
      en: "Day-use hot spring inside Kannonike Park, with 13 baths including an outdoor bath.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1145"],
  },
  {
    slug: "sun-cherry-kitago",
    category: ["onsen"],
    area: "nichinan",
    name: { ja: "サンチェリーきたごう", en: "Sun Cherry Kitago" },
    address: { ja: "宮崎県日南市北郷町大藤甲1519-1", en: "1519-1 Ofuji-ko, Kitago-cho, Nichinan-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0987-67-4737",
    website: null,
    google_maps_url: null,
    hours: {
      ja: "大浴場 11:00〜20:00",
      en: "Bath 11:00–20:00",
    },
    price: null,
    description: {
      ja: "日南市北郷の市営温泉施設。2024年12月に再開。",
      en: "Municipal hot spring in Kitago, Nichinan. Reopened in December 2024.",
    },
    tags: null,
    sources: ["https://www.city.nichinan.lg.jp/soshikikarasagasu/kanko_cruiseka/1/3/5913.html"],
  },
  {
    slug: "sukimuland-kajika",
    category: ["onsen"],
    area: "kobayashi",
    name: { ja: "すきむらんど かじかの湯", en: "Sukimu-Land Kajika-no-Yu" },
    address: { ja: "宮崎県小林市須木下田356-1", en: "356-1 Sugi-Shimoda, Kobayashi-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0984-48-2480",
    website: "https://sukimuland.com/",
    google_maps_url: null,
    hours: null,
    price: {
      ja: "中学生以上 500円、小学生 250円",
      en: "Middle school+ 500 yen; elementary 250 yen",
    },
    description: {
      ja: "小林市須木のすきむらんど内の日帰り温泉。",
      en: "Day-use hot spring inside the Sukimu-Land complex in Sugi, Kobayashi.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1059"],
  },
  {
    slug: "jubei-no-yu",
    category: ["onsen"],
    area: "ebino",
    name: { ja: "十兵衛の湯（京町温泉）", en: "Jubei-no-Yu (Kyomachi Onsen)" },
    address: { ja: "宮崎県えびの市大字向江212-1", en: "212-1 Mukae, Ebino-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0984-37-2799",
    website: "http://www.jyubei.co.jp/index.html",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "京町温泉郷の日帰り入浴施設。家族貸切風呂もある。",
      en: "Day-use bathhouse in the Kyomachi Onsen area, with private family baths.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/2502"],
  },
  {
    slug: "kyomachi-kanko-hotel",
    category: ["onsen"],
    area: "ebino",
    name: { ja: "京町観光ホテル", en: "Kyomachi Kanko Hotel" },
    address: { ja: "宮崎県えびの市向江669", en: "669 Mukae, Ebino-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0984-37-1231",
    website: "https://kyoukan.jp/",
    google_maps_url: null,
    hours: {
      ja: "立ち寄り湯 7:00〜22:00（最終受付 21:00）",
      en: "Day-use bath 7:00–22:00 (last entry 21:00)",
    },
    price: null,
    description: {
      ja: "京町温泉のホテル。立ち寄り湯もできる。",
      en: "Hotel in the Kyomachi Onsen area that also welcomes day-use bathers.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/2601"],
  },
  {
    slug: "shiratori-onsen-shimoyu",
    category: ["onsen"],
    area: "ebino",
    name: { ja: "白鳥温泉 下湯", en: "Shiratori Onsen Shimoyu" },
    address: { ja: "宮崎県えびの市末永1470", en: "1470 Suenaga, Ebino-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0984-33-3611",
    website: "http://shiratori-onsen.com/wp/down/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "えびの高原ふもとの日帰り温泉。庭園の露天風呂と貸切風呂がある。",
      en: "Day-use hot spring at the foot of the Ebino Highlands, with a garden outdoor bath and private baths.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1403"],
  },
  {
    slug: "ebino-kogen-hotel",
    category: ["onsen"],
    area: "ebino",
    name: { ja: "えびの高原ホテル（国民宿舎えびの高原荘）", en: "Ebino Kogen Hotel" },
    address: { ja: "宮崎県えびの市大字末永1489", en: "1489 Suenaga, Ebino-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0984-33-0161",
    website: "https://ebinokogen-hotel.com/",
    google_maps_url: null,
    hours: {
      ja: "日帰り温泉 11:00〜17:00（最終受付 16:00）",
      en: "Day-use onsen 11:00–17:00 (last entry 16:00)",
    },
    price: null,
    description: {
      ja: "えびの高原の県営国民宿舎。日帰り入浴もできる。",
      en: "Prefectural lodge on the Ebino Highlands. Day-use bathing available.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1325"],
  },
  {
    slug: "yunomoto-onsen",
    category: ["onsen"],
    area: "takaharu",
    name: { ja: "湯之元温泉", en: "Yunomoto Onsen" },
    address: { ja: "宮崎県西諸県郡高原町大字蒲牟田7535", en: "7535 Gamuda, Takaharu-cho, Nishi-Morokata-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0984-42-3701",
    website: "https://yunomoto.org/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "高原町の炭酸泉。日帰り入浴もできる。",
      en: "Carbonated hot spring in Takaharu, with day-use bathing available.",
    },
    tags: null,
    sources: ["https://yunomoto.org/spa.php"],
  },
];

function ensureDir(dir: string): void {
  fs.mkdirSync(dir, { recursive: true });
}

function main(): void {
  ensureDir(OUT);
  let ok = 0;
  const failures: { slug: string; issues: string[] }[] = [];
  for (const s of seeds) {
    const full: Listing = {
      slug: s.slug,
      genre: "camp",
      category: s.category,
      area: s.area,
      name: s.name,
      address: s.address,
      lat: s.lat,
      lng: s.lng,
      phone: s.phone,
      website: s.website,
      google_maps_url: s.google_maps_url,
      hours: s.hours,
      price: s.price,
      description: s.description,
      tags: s.tags,
      features: s.features ?? [],
      sources: s.sources,
      verified_at: s.verified_at ?? TODAY,
      status: s.status ?? "open",
    };
    const parsed = listingSchema.safeParse(full);
    if (!parsed.success) {
      failures.push({
        slug: s.slug,
        issues: parsed.error.issues.map((i) => `${i.path.join(".")}: ${i.message}`),
      });
      continue;
    }
    const file = path.join(OUT, `${s.slug}.json`);
    fs.writeFileSync(file, JSON.stringify(parsed.data, null, 2) + "\n", "utf8");
    ok += 1;
  }
  console.log(`wrote ${ok} listing(s) to ${OUT}`);
  if (failures.length > 0) {
    console.error(`FAIL - ${failures.length} listing(s) invalid:`);
    for (const f of failures) {
      console.error(`  ${f.slug}:`);
      for (const i of f.issues) console.error(`    - ${i}`);
    }
    process.exit(1);
  }
}

main();
