import fs from "node:fs";
import path from "node:path";
import { listingSchema, type ListingInput as Listing } from "../lib/types";

const TODAY = "2026-09-15";
const ROOT = process.cwd();
const OUT = path.join(ROOT, "data", "listings", "food");

type Seed = Omit<Listing, "genre" | "verified_at" | "status" | "features"> & {
  status?: Listing["status"];
  verified_at?: string;
  features?: string[];
};

const seeds: Seed[] = [
  // =============================================================
  // JIDORI — みやざき地頭鶏 charcoal-grill shops / cooperative-listed
  // =============================================================
  {
    slug: "gunkei-honten-kakushigura",
    category: ["jidori"],
    area: "miyazaki-shi",
    name: { ja: "ぐんけい本店 隠蔵", en: "Gunkei Honten Kakushigura" },
    address: { ja: "宮崎県宮崎市中央通8-12", en: "8-12 Chuo-dori, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0120-85-8170",
    website: "http://www.gunkei.jp/restaurant/info-kakushigura/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "みやざき地頭鶏を炭火で焼く店。ぐんけいグループの本店。中央通の裏路地にある。",
      en: "Charcoal-grilled Miyazaki Jitokko chicken. The flagship shop of the Gunkei group, in a Chuo-dori back alley.",
    },
    tags: null,
    sources: ["https://www.miyazaki-city.tourism.or.jp/gourmet/10120"],
  },
  {
    slug: "gunkei-miyazaki-ekimae-kiten",
    category: ["jidori"],
    area: "miyazaki-shi",
    name: { ja: "ぐんけい宮崎駅前店 きてん", en: "Gunkei Miyazaki Ekimae Kiten" },
    address: { ja: "宮崎県宮崎市錦町1-10 宮崎グリーンスフィア壱番館2F", en: "2F Miyazaki Green Sphere Ichibankan, 1-10 Nishikimachi, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0985-33-9001",
    website: "http://www.gunkei.jp/restaurant/info-kiten/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "みやざき地頭鶏の炭火焼を出す店。JR宮崎駅前のグリーンスフィア2階。",
      en: "Charcoal-grilled Miyazaki Jitokko on the 2F of Green Sphere, right in front of JR Miyazaki Station.",
    },
    tags: null,
    sources: ["https://www.mjitokko.jp/restaurant/detail.php?id=1608001019"],
  },
  {
    slug: "gunkei-farm",
    category: ["jidori"],
    area: "miyazaki-shi",
    name: { ja: "ぐんけい農園直営店", en: "Gunkei Farm Store" },
    address: { ja: "宮崎県宮崎市高岡町上倉永1087-1", en: "1087-1 Kami-Kuranaga, Takaoka-cho, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0985-41-6001",
    website: "http://www.gunkei.jp/farm/miyazaki-jitokko/",
    google_maps_url: null,
    hours: {
      ja: "9:00〜17:00",
      en: "9:00–17:00",
    },
    price: null,
    description: {
      ja: "みやざき地頭鶏を林間放し飼いで育てる直営農場。物販あり。",
      en: "The farm where Gunkei raises Miyazaki Jitokko free-range in the woodland. Retail on site.",
    },
    tags: null,
    sources: ["https://www.mjitokko.jp/restaurant/detail.php?id=1608001034"],
  },
  {
    slug: "suisen-jidori-sumibiyaki",
    category: ["jidori"],
    area: "miyazaki-shi",
    name: { ja: "地鶏炭火焼 粋仙", en: "Jidori Sumibiyaki Suisen" },
    address: { ja: "宮崎県宮崎市広島2-11-3", en: "2-11-3 Hiroshima, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0985-23-1588",
    website: "https://www.suisen-jidori.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "みやざき地頭鶏や宮崎鶏を日向備長炭で焼く炭火焼専門店。組合の指定店。",
      en: "Miyazaki Jitokko and regional chicken grilled over Hyuga binchotan. A cooperative-designated shop.",
    },
    tags: null,
    sources: ["https://www.mjitokko.jp/restaurant/detail.php?id=1608000960"],
  },
  {
    slug: "furusato-ryori-suginoko",
    category: ["jidori"],
    area: "miyazaki-shi",
    name: { ja: "ふるさと料理 杉の子", en: "Furusato Ryori Suginoko" },
    address: { ja: "宮崎県宮崎市橘通西2-1-4", en: "2-1-4 Tachibana-dori Nishi, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0985-22-5798",
    website: "https://www.miyazaki-suginoko.net/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "みやざき地頭鶏の炭火焼を含む宮崎の郷土料理を出す店。組合の指定店。",
      en: "Miyazaki home-style dishes, including charcoal-grilled Miyazaki Jitokko. A cooperative-designated shop.",
    },
    tags: null,
    sources: ["https://www.mjitokko.jp/restaurant/detail.php?id=1608001031"],
  },
  {
    slug: "kutsurogi-sanshirou",
    category: ["jidori"],
    area: "miyazaki-shi",
    name: { ja: "Kutsurogi 三四郎", en: "Kutsurogi Sanshirou" },
    address: { ja: "宮崎県宮崎市堀川町57-1", en: "57-1 Horikawa-cho, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0985-31-1888",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "みやざき地頭鶏の炭火焼を扱う店。組合の指定店。",
      en: "Charcoal-grilled Miyazaki Jitokko. A cooperative-designated shop.",
    },
    tags: null,
    sources: ["https://www.mjitokko.jp/restaurant/detail.php?id=1608001108"],
  },
  {
    slug: "tsukada-nojo-miyazaki-honten",
    category: ["jidori"],
    area: "miyazaki-shi",
    name: { ja: "塚田農場 宮崎本店", en: "Tsukada Farm Miyazaki Honten" },
    address: { ja: "宮崎県宮崎市橘通西3-2-24 ライオンタワー宮崎ビル", en: "Lion Tower Miyazaki Bldg, 3-2-24 Tachibana-dori Nishi, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0985-61-3361",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "みやざき地頭鶏をはじめとする宮崎食材の居酒屋。塚田農場グループの宮崎本店。",
      en: "Izakaya featuring Miyazaki Jitokko and other Miyazaki produce. Tsukada Farm's Miyazaki flagship.",
    },
    tags: null,
    sources: ["https://www.mjitokko.jp/restaurant/detail.php?id=1608001036"],
  },
  {
    slug: "jitokko-land-nichinan",
    category: ["jidori"],
    area: "nichinan",
    name: { ja: "地頭鶏ランド日南", en: "Jitokko Land Nichinan" },
    address: { ja: "宮崎県日南市大字毛吉田2723-1", en: "2723-1 Keyoshida, Nichinan-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0987-27-1269",
    website: "https://jitokko.co.jp/",
    google_maps_url: null,
    hours: {
      ja: "8:00〜17:00 日曜定休",
      en: "8:00–17:00, closed Sundays",
    },
    price: null,
    description: {
      ja: "みやざき地頭鶏の生産センター。処理場に併設された直売所で丸鶏や加工品を扱う。",
      en: "Miyazaki Jitokko production centre. The retail counter next to the processing plant sells whole birds and prepared products.",
    },
    tags: null,
    sources: ["https://www.kankou-nichinan.jp/tourisms/764/"],
  },
  {
    slug: "kanemaru-jitokko-farm",
    category: ["jidori"],
    area: "miyakonojo",
    name: { ja: "かねまる地頭鶏農場", en: "Kanemaru Jitokko Farm" },
    address: { ja: "宮崎県都城市高崎町縄瀬3203-2", en: "3203-2 Nawase, Takazaki-cho, Miyakonojo-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://jitokko.jp/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "都城市高崎町のみやざき地頭鶏の農場。丸鶏や加工品を通販・直販。",
      en: "Miyazaki Jitokko farm in Takazaki, Miyakonojo. Sells whole birds and prepared products direct.",
    },
    tags: null,
    sources: ["https://www.city.miyakonojo.miyazaki.jp/site/chicken/22834.html"],
  },

  // =============================================================
  // SHOCHU — Miyazaki distilleries with public tour / retail / tasting
  // =============================================================
  {
    slug: "kagura-tunnel-no-eki",
    category: ["shochu"],
    area: "takachiho",
    name: { ja: "神楽酒造 トンネルの駅", en: "Kagura Shuzo — Tunnel no Eki" },
    address: { ja: "宮崎県西臼杵郡高千穂町下野2221-2", en: "2221-2 Shimono, Takachiho-cho, Nishi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-73-4050",
    website: "https://tonnerunoeki.com/",
    google_maps_url: null,
    hours: {
      ja: "9:00〜17:00 第1水曜定休",
      en: "9:00–17:00, closed the first Wednesday",
    },
    price: null,
    description: {
      ja: "旧鉄道トンネルを焼酎の貯蔵庫にした施設。神楽酒造の焼酎は無料試飲もできる。",
      en: "A former railway tunnel used as a shochu cellar. Free tastings of Kagura Shuzo's shochu.",
    },
    tags: null,
    sources: ["https://tonnerunoeki.com/about"],
  },
  {
    slug: "takachiho-shuzo",
    category: ["shochu"],
    area: "takachiho",
    name: { ja: "高千穂酒造", en: "Takachiho Shuzo" },
    address: { ja: "宮崎県西臼杵郡高千穂町大字押方925", en: "925 Oshikata, Takachiho-cho, Nishi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-72-2323",
    website: "https://www.takachihosyuzo.co.jp/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "高千穂の焼酎蔵。蔵見学は要予約。",
      en: "Takachiho shochu brewery. Tours by reservation only.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/sakagura1"],
  },
  {
    slug: "akatsuki-shuzo",
    category: ["shochu"],
    area: "takachiho",
    name: { ja: "アカツキ酒造", en: "Akatsuki Shuzo" },
    address: { ja: "宮崎県西臼杵郡高千穂町河内1835-5", en: "1835-5 Kawachi, Takachiho-cho, Nishi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-75-1612",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "高千穂町の米焼酎蔵。蔵見学は要予約。",
      en: "Rice-shochu brewery in Takachiho. Tours by reservation only.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/sakagura1"],
  },
  {
    slug: "himeizumi-shuzo",
    category: ["shochu"],
    area: "hinokage",
    name: { ja: "姫泉酒造", en: "Himeizumi Shuzo" },
    address: { ja: "宮崎県西臼杵郡日之影町岩井川3380-1", en: "3380-1 Iwaigawa, Hinokage-cho, Nishi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-87-2016",
    website: "https://www.himeizumi.co.jp/",
    google_maps_url: null,
    hours: {
      ja: "10:00〜16:00 蔵見学は要予約",
      en: "10:00–16:00, tour by reservation",
    },
    price: null,
    description: {
      ja: "日之影町の焼酎蔵。蔵見学は要予約。",
      en: "Shochu brewery in Hinokage. Tours by reservation only.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/sakagura1"],
  },
  {
    slug: "sentoku-shuzo",
    category: ["shochu"],
    area: "nobeoka",
    name: { ja: "千徳酒造", en: "Sentoku Shuzo" },
    address: { ja: "宮崎県延岡市大瀬町2-1-8", en: "2-1-8 Oze-machi, Nobeoka-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-32-2024",
    website: "http://sentoku.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "延岡市の酒蔵。宮崎県で唯一の清酒蔵。蔵見学は要予約。",
      en: "Nobeoka brewery. Miyazaki's only sake (seishu) brewery. Tours by reservation.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/sakagura1"],
  },
  {
    slug: "sato-shochu",
    category: ["shochu"],
    area: "nobeoka",
    name: { ja: "佐藤焼酎製造場", en: "Sato Shochu" },
    address: { ja: "宮崎県延岡市祝子町2388-1", en: "2388-1 Horigawa-cho, Nobeoka-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-33-2811",
    website: "https://satoshochu.com/",
    google_maps_url: null,
    hours: {
      ja: "10:00〜16:00 蔵見学は要予約",
      en: "10:00–16:00, tour by reservation",
    },
    price: null,
    description: {
      ja: "延岡市の焼酎蔵。蔵見学は要予約。直売所あり。",
      en: "Nobeoka shochu brewery. Tours by reservation. Direct sales on site.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/sakagura1"],
  },
  {
    slug: "akugare-distillery",
    category: ["shochu"],
    area: "hyuga",
    name: { ja: "あくがれ蒸留所", en: "Akugare Distillery" },
    address: { ja: "宮崎県日向市東郷町山陰辛212-1", en: "212-1 Yamakage-Kanoto, Togo-cho, Hyuga-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-68-3550",
    website: "https://www.akugare.jp/",
    google_maps_url: null,
    hours: {
      ja: "10:00〜17:00 蔵見学は要予約",
      en: "10:00–17:00, tour by reservation",
    },
    price: null,
    description: {
      ja: "日向市東郷町の焼酎蔵。蔵見学は要予約。",
      en: "Shochu brewery in Togo, Hyuga. Tours by reservation only.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/sakagura1"],
  },
  {
    slug: "ochiai-shuzo",
    category: ["shochu"],
    area: "miyazaki-shi",
    name: { ja: "落合酒造場", en: "Ochiai Shuzo" },
    address: { ja: "宮崎県宮崎市鏡洲1626", en: "1626 Kagamizu, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0985-55-3206",
    website: "https://ochiaishuzojyo.jp/",
    google_maps_url: null,
    hours: {
      ja: "10:00〜16:00 蔵見学は要予約",
      en: "10:00–16:00, tour by reservation",
    },
    price: null,
    description: {
      ja: "宮崎市鏡洲の焼酎蔵。蔵見学は要予約。",
      en: "Shochu brewery in Kagamizu, Miyazaki. Tours by reservation only.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/sakagura2"],
  },
  {
    slug: "yamaya-distillery",
    category: ["shochu"],
    area: "saito",
    name: { ja: "やまや蒸留所", en: "Yamaya Distillery" },
    address: { ja: "宮崎県西都市三納10029", en: "10029 Minou, Saito-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0983-45-1013",
    website: "https://yamayadistillery.com/",
    google_maps_url: null,
    hours: {
      ja: "8:00〜17:00 蔵見学は要予約 土日休",
      en: "8:00–17:00, tour by reservation, closed weekends",
    },
    price: null,
    description: {
      ja: "西都市三納の焼酎蔵。蔵見学は要予約。店頭販売あり。",
      en: "Shochu distillery in Minou, Saito. Tours by reservation. Direct sales on site.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/sakagura2"],
  },
  {
    slug: "kagura-shuzo-saito",
    category: ["shochu"],
    area: "saito",
    name: { ja: "神楽酒造 西の都アグリホール", en: "Kagura Shuzo (Saito Plant)" },
    address: { ja: "宮崎県西都市鹿野田11365-1", en: "11365-1 Kanoda, Saito-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0983-41-1234",
    website: "https://www.kagurashuzo.co.jp/",
    google_maps_url: null,
    hours: {
      ja: "平日 9:00〜16:30 蔵見学は要予約",
      en: "Weekdays 9:00–16:30, tour by reservation",
    },
    price: null,
    description: {
      ja: "神楽酒造の西都工場。蔵見学は平日のみ、要予約。",
      en: "Kagura Shuzo's Saito plant. Weekday-only tours by reservation.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/sakagura2"],
  },
  {
    slug: "unkai-aya",
    category: ["shochu"],
    area: "aya",
    name: { ja: "雲海酒造 綾自然蔵見学館", en: "Unkai Shuzo Aya Natural Cellar" },
    address: { ja: "宮崎県東諸県郡綾町南俣1795-1", en: "1795-1 Minamimata, Aya-cho, Higashi-Morokata-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0985-77-3737",
    website: "http://unkai.co.jp/learn/facility",
    google_maps_url: null,
    hours: {
      ja: "蔵見学 10:30／14:30（要予約）",
      en: "Tours 10:30 or 14:30 (reservation required)",
    },
    price: null,
    description: {
      ja: "雲海酒造の綾工場。蔵見学は約90分、試飲つき。店頭販売あり。",
      en: "Unkai's Aya facility. Tour is about 90 min with tasting. Direct sales on site.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/sakagura2"],
  },
  {
    slug: "kirishima-factory-garden",
    category: ["shochu"],
    area: "miyakonojo",
    name: { ja: "霧島ファクトリーガーデン", en: "Kirishima Factory Garden" },
    address: { ja: "宮崎県都城市志比田町5480", en: "5480 Shihida-cho, Miyakonojo-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0986-21-8111",
    website: "http://www.kirishima-fg.jp/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "霧島酒造の工場見学施設。試飲、直売ショップ、レストランを併設。",
      en: "Kirishima Shuzo's public factory. Tour, tasting, direct sales shop and restaurant on site.",
    },
    tags: null,
    sources: ["https://www.city.miyakonojo.miyazaki.jp/site/kanko/10169.html"],
  },
  {
    slug: "oura-shuzo",
    category: ["shochu"],
    area: "miyakonojo",
    name: { ja: "大浦酒造", en: "Oura Shuzo" },
    address: { ja: "宮崎県都城市乙房町4113-1", en: "4113-1 Otsubo-cho, Miyakonojo-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0986-37-3883",
    website: "https://ooura-syuzou.net/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "都城市乙房町の焼酎蔵。蔵見学は要予約。隣接の直売店あり。",
      en: "Shochu brewery in Otsubo, Miyakonojo. Tour by reservation. Adjacent direct-sales shop.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/sakagura4"],
  },
  {
    slug: "suki-shuzo",
    category: ["shochu"],
    area: "kobayashi",
    name: { ja: "すき酒造", en: "Suki Shuzo" },
    address: { ja: "宮崎県小林市須木下田唐池393-3", en: "393-3 Karaike, Sugi-Shimoda, Kobayashi-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0984-48-2016",
    website: null,
    google_maps_url: null,
    hours: {
      ja: "9:00〜16:00 蔵見学は要予約",
      en: "9:00–16:00, tour by reservation",
    },
    price: null,
    description: {
      ja: "小林市須木の焼酎蔵。蔵見学は要予約、店頭販売あり。",
      en: "Shochu brewery in Sugi, Kobayashi. Tour by reservation. Direct sales on site.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/sakagura4"],
  },
  {
    slug: "akashi-shuzo",
    category: ["shochu"],
    area: "ebino",
    name: { ja: "明石酒造", en: "Akashi Shuzo" },
    address: { ja: "宮崎県えびの市大字栗下61-1", en: "61-1 Kurishita, Ebino-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0984-35-1603",
    website: "https://www.meigetsu.co.jp/",
    google_maps_url: null,
    hours: {
      ja: "8:00〜17:00 蔵見学は要予約",
      en: "8:00–17:00, tour by reservation",
    },
    price: null,
    description: {
      ja: "えびの市の焼酎蔵。蔵見学は要予約。",
      en: "Ebino shochu brewery. Tour by reservation only.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/sakagura4"],
  },
  {
    slug: "ohtemon-shuzo",
    category: ["shochu"],
    area: "nichinan",
    name: { ja: "酒蔵 王手門", en: "Ohtemon Shuzo" },
    address: { ja: "宮崎県日南市北郷町大藤甲898-8", en: "898-8 Ofuji-ko, Kitago-cho, Nichinan-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0987-21-7717",
    website: "https://ohtemon1895.jp/",
    google_maps_url: null,
    hours: {
      ja: "水金土 9:00〜15:00 蔵見学は要予約",
      en: "Wed/Fri/Sat 9:00–15:00, tour by reservation",
    },
    price: null,
    description: {
      ja: "日南市北郷の焼酎蔵。蔵見学は水金土のみ、要予約。",
      en: "Shochu brewery in Kitago, Nichinan. Tours Wed/Fri/Sat by reservation.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/sakagura3"],
  },
  {
    slug: "kyoya-shuzo",
    category: ["shochu"],
    area: "nichinan",
    name: { ja: "京屋酒造", en: "Kyoya Shuzo" },
    address: { ja: "宮崎県日南市平野4299", en: "4299 Hirano, Nichinan-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0987-22-2002",
    website: "https://www.kyo-ya.com/",
    google_maps_url: null,
    hours: {
      ja: "9:00〜16:00 蔵見学は要予約",
      en: "9:00–16:00, tour by reservation",
    },
    price: null,
    description: {
      ja: "日南市の焼酎蔵。蔵見学は要予約。",
      en: "Nichinan shochu brewery. Tour by reservation only.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/sakagura3"],
  },
  {
    slug: "sakuranomine-shuzo",
    category: ["shochu"],
    area: "nichinan",
    name: { ja: "櫻乃峰酒造", en: "Sakuranomine Shuzo" },
    address: { ja: "宮崎県日南市大字隈谷甲1192", en: "1192 Kumatani-ko, Nichinan-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0987-27-0271",
    website: "https://sakuranomine.jp/",
    google_maps_url: null,
    hours: {
      ja: "9:00〜16:00 蔵見学は要予約",
      en: "9:00–16:00, tour by reservation",
    },
    price: null,
    description: {
      ja: "日南市の焼酎蔵。蔵見学は要予約。",
      en: "Nichinan shochu brewery. Tour by reservation only.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/sakagura3"],
  },
  {
    slug: "furusawa-jozo",
    category: ["shochu"],
    area: "nichinan",
    name: { ja: "古澤醸造", en: "Furusawa Jozo" },
    address: { ja: "宮崎県日南市大堂津4-10-1", en: "4-10-1 Odotsu, Nichinan-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0987-27-0005",
    website: "https://nichinan-yaezakura.jp/",
    google_maps_url: null,
    hours: {
      ja: "8:00〜16:00 蔵見学は要予約",
      en: "8:00–16:00, tour by reservation",
    },
    price: null,
    description: {
      ja: "日南市大堂津の焼酎蔵。蔵見学は要予約。店頭販売あり。",
      en: "Shochu brewery in Odotsu, Nichinan. Tour by reservation. Direct sales on site.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/sakagura3"],
  },
  {
    slug: "sakuranosato-shuzo",
    category: ["shochu"],
    area: "nichinan",
    name: { ja: "櫻の郷酒造 焼酎道場", en: "Sakuranosato Shuzo (Shochu Dojo)" },
    address: { ja: "宮崎県日南市北郷町郷之原甲888", en: "888 Gonohara-ko, Kitago-cho, Nichinan-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0987-55-4134",
    website: "https://www.sakuranosato.co.jp/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "日南市北郷の焼酎蔵「焼酎道場」。予約不要で見学と試飲、オリジナルブレンド体験ができる。",
      en: "Nichinan brewery 'Shochu Dojo'. Walk-in tour, tasting, and make-your-own blend, no reservation needed.",
    },
    tags: null,
    sources: ["https://www.sakuranosato.co.jp/tour/"],
  },
  {
    slug: "inoue-shuzo",
    category: ["shochu"],
    area: "nichinan",
    name: { ja: "井上酒造", en: "Inoue Shuzo" },
    address: { ja: "宮崎県日南市南郷町榎原甲1326", en: "1326 Yowara-ko, Nango-cho, Nichinan-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0987-68-1055",
    website: "https://www.obisugi.co.jp/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "日南市南郷の焼酎蔵。蔵見学と試飲・直売は予約制。",
      en: "Shochu brewery in Nango, Nichinan. Tour, tasting, and direct sales by reservation.",
    },
    tags: null,
    sources: ["https://www.obisugi.co.jp/tour/"],
  },
  {
    slug: "jukai-shuzo",
    category: ["shochu"],
    area: "kushima",
    name: { ja: "寿海酒造", en: "Jukai Shuzo" },
    address: { ja: "宮崎県串間市北方1295", en: "1295 Kitakata, Kushima-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0987-72-5611",
    website: "https://www.jyukai-shuzou.jp/",
    google_maps_url: null,
    hours: {
      ja: "13:00〜16:00 蔵見学・店頭販売は要予約",
      en: "13:00–16:00, tour and direct sales by reservation",
    },
    price: null,
    description: {
      ja: "串間市の焼酎蔵。蔵見学と店頭販売は要予約。",
      en: "Kushima shochu brewery. Tour and direct sales by reservation.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/sakagura3"],
  },

  // =============================================================
  // FARM — publicly bookable farm experiences
  // =============================================================
  {
    slug: "hinata-ichigo-en",
    category: ["farm"],
    area: "miyazaki-shi",
    name: { ja: "ひなたいちご園", en: "Hinata Ichigo Farm" },
    address: { ja: "宮崎県宮崎市郡司分甲5231-3", en: "5231-3 Gunjibun-ko, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://hinataichigo.com/",
    google_maps_url: null,
    hours: {
      ja: "いちご狩り 1月〜5月",
      en: "Strawberry picking January–May",
    },
    price: null,
    description: {
      ja: "宮崎市のいちご狩り農園。高設栽培。",
      en: "Strawberry-picking farm in Miyazaki City, using elevated-bed cultivation.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/strawberry"],
  },
  {
    slug: "lakeside-red-farm",
    category: ["farm"],
    area: "miyazaki-shi",
    name: { ja: "レイクサイドレッドファーム", en: "Lakeside Red Farm" },
    address: { ja: "宮崎県宮崎市清武町今泉丙1331-1", en: "1331-1 Imaizumi-hei, Kiyotake-cho, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "http://www.corefarm.co.jp/lakeside/",
    google_maps_url: null,
    hours: {
      ja: "いちご狩り 1月〜6月",
      en: "Strawberry picking January–June",
    },
    price: null,
    description: {
      ja: "宮崎市清武町のいちご狩り農園。量り売りと食べ放題を選べる。",
      en: "Strawberry farm in Kiyotake, Miyazaki. Choose between weigh-out or all-you-can-pick.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/strawberry"],
  },
  {
    slug: "kawahara-ichigo-noen",
    category: ["farm"],
    area: "nobeoka",
    name: { ja: "川原いちご農園", en: "Kawahara Ichigo Farm" },
    address: { ja: "宮崎県延岡市柚の木田町1195", en: "1195 Yunokida-cho, Nobeoka-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://www.kawahara-ichigo.com/",
    google_maps_url: null,
    hours: {
      ja: "いちご狩り 3月〜5月",
      en: "Strawberry picking March–May",
    },
    price: null,
    description: {
      ja: "延岡市のいちご狩り農園。",
      en: "Strawberry-picking farm in Nobeoka.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/strawberry"],
  },
  {
    slug: "ichini-no-ichigo-en",
    category: ["farm"],
    area: "nobeoka",
    name: { ja: "いちにのいちご園", en: "Ichini no Ichigo En" },
    address: { ja: "宮崎県延岡市大貫町4-1439", en: "4-1439 Onuki-cho, Nobeoka-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://1215.jp/",
    google_maps_url: null,
    hours: {
      ja: "いちご狩り 1月〜5月",
      en: "Strawberry picking January–May",
    },
    price: null,
    description: {
      ja: "延岡市のいちご狩り農園。5品種を扱う。",
      en: "Strawberry farm in Nobeoka growing five varieties.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/strawberry"],
  },
  {
    slug: "sasagino-ichigo-en",
    category: ["farm"],
    area: "hyuga",
    name: { ja: "笹木野いちご園", en: "Sasagino Ichigo Farm" },
    address: { ja: "宮崎県日向市東郷町山陰戊93", en: "93 Yamakage-tsuchinoe, Togo-cho, Hyuga-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "http://sasagino-ichigoen.com/",
    google_maps_url: null,
    hours: {
      ja: "いちご狩り 1月〜5月",
      en: "Strawberry picking January–May",
    },
    price: null,
    description: {
      ja: "日向市東郷町のいちご狩り農園。車いすでも入れる。",
      en: "Strawberry farm in Togo, Hyuga. Wheelchair accessible.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/strawberry"],
  },
  {
    slug: "kamenoko-ichigo-en",
    category: ["farm"],
    area: "hyuga",
    name: { ja: "亀の子いちご園", en: "Kamenoko Ichigo Farm" },
    address: { ja: "宮崎県日向市塩見字亀ノ甲7028", en: "7028 Kamenoko, Shiomi, Hyuga-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://kamenoko15.com/",
    google_maps_url: null,
    hours: {
      ja: "いちご狩り 2月〜5月（50分食べ放題）",
      en: "Strawberry picking February–May (50 min all-you-can-eat)",
    },
    price: null,
    description: {
      ja: "日向市塩見のいちご狩り農園。50分の食べ放題方式。",
      en: "Strawberry farm in Shiomi, Hyuga. 50-minute all-you-can-eat picking.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/strawberry"],
  },
  {
    slug: "sens-berry-farm",
    category: ["farm"],
    area: "ebino",
    name: { ja: "SEN's Berry Farm", en: "SEN's Berry Farm" },
    address: { ja: "宮崎県えびの市原田4070", en: "4070 Harada, Ebino-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "えびの市原田のいちご狩り農園。",
      en: "Strawberry-picking farm in Harada, Ebino.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/strawberry"],
  },
  {
    slug: "minami-ichigo-noen",
    category: ["farm"],
    area: "nichinan",
    name: { ja: "南いちご農園", en: "Minami Strawberry Farm" },
    address: { ja: "宮崎県日南市北郷町郷之原", en: "Gonohara, Kitago-cho, Nichinan-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://www.373strawberryfarm.com/",
    google_maps_url: null,
    hours: {
      ja: "いちご狩り 1月〜5月",
      en: "Strawberry picking January–May",
    },
    price: null,
    description: {
      ja: "日南市北郷のいちご狩り農園。ぶどうや柿など季節の果物も。",
      en: "Strawberry farm in Kitago, Nichinan. Grapes and persimmons also in season.",
    },
    tags: null,
    sources: ["https://www.373strawberryfarm.com/picking.php"],
  },
  {
    slug: "kushima-ichigo-hatake-onitsuka",
    category: ["farm"],
    area: "kushima",
    name: { ja: "串間いちご畑（おにつか農園）", en: "Kushima Ichigo Hatake (Onitsuka Farm)" },
    address: { ja: "宮崎県串間市大字本城", en: "Honjo, Kushima-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "080-5215-2140",
    website: null,
    google_maps_url: null,
    hours: {
      ja: "いちご狩り 12月〜5月中旬 量り売り",
      en: "Strawberry picking December–mid-May, pay by weight",
    },
    price: null,
    description: {
      ja: "串間市のいちご畑。完熟きんかん、日向夏、動物ふれあいもある。",
      en: "Kushima strawberry field. Also serves ripe kinkan, hyuganatsu, and animal petting.",
    },
    tags: null,
    sources: ["https://www.city.kushima.lg.jp/ecotourism/activity/2021/02/sup.html"],
  },
  {
    slug: "kiyanse-farm",
    category: ["farm"],
    area: "miyakonojo",
    name: { ja: "KIYANSE FARM", en: "Kiyanse Farm" },
    address: { ja: "宮崎県都城市高城町大井手1953-8", en: "1953-8 Oide, Takajo-cho, Miyakonojo-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: {
      ja: "ブルーベリー狩り 6月〜8月",
      en: "Blueberry picking June–August",
    },
    price: null,
    description: {
      ja: "都城市高城町のブルーベリー狩り農園。30品種を無農薬で栽培。",
      en: "Blueberry-picking farm in Takajo, Miyakonojo. 30 varieties grown pesticide-free.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/fruit"],
  },
  {
    slug: "kocchan-blueberry-en",
    category: ["farm"],
    area: "mimata",
    name: { ja: "こっちゃんブルーベリー園", en: "Kocchan Blueberry Farm" },
    address: { ja: "宮崎県三股町長田5045-2", en: "5045-2 Nagata, Mimata-cho, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: {
      ja: "ブルーベリー狩り 7月〜8月",
      en: "Blueberry picking July–August",
    },
    price: null,
    description: {
      ja: "三股町のブルーベリー狩り農園。200株以上を有機で栽培。",
      en: "Blueberry-picking farm in Mimata. Over 200 organically grown bushes.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/fruit"],
  },
  {
    slug: "miki-farm",
    category: ["farm"],
    area: "takanabe",
    name: { ja: "ミキファーム", en: "Miki Farm" },
    address: { ja: "宮崎県児湯郡高鍋町南高鍋8751", en: "8751 Minami-Takanabe, Takanabe-cho, Koyu-gun, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://miki-farm.co.jp/",
    google_maps_url: null,
    hours: {
      ja: "ライチ狩り 5月〜7月",
      en: "Lychee picking May–July",
    },
    price: null,
    description: {
      ja: "高鍋町のライチ狩り農園。国内で数少ないライチ狩り。",
      en: "Lychee-picking farm in Takanabe, one of few lychee-picking farms in Japan.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/fruit"],
  },
  {
    slug: "mukabaki-kajuen",
    category: ["farm"],
    area: "nobeoka",
    name: { ja: "むかばき果樹園", en: "Mukabaki Orchard" },
    address: { ja: "宮崎県延岡市行縢町", en: "Mukabaki-cho, Nobeoka-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: {
      ja: "ぶどう狩り 8月／キウイ狩り 10月",
      en: "Grape picking August, kiwi picking October",
    },
    price: null,
    description: {
      ja: "延岡市行縢町の有機果樹園。ぶどう狩りとキウイ狩り。",
      en: "Organic orchard in Mukabaki, Nobeoka. Grape and kiwi picking in season.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/fruit"],
  },
  {
    slug: "taguchi-family-farm",
    category: ["farm"],
    area: "nobeoka",
    name: { ja: "田口ファミリーファーム", en: "Taguchi Family Farm" },
    address: { ja: "宮崎県延岡市北方町蔵田辰816", en: "816 Kurada-Tatsu, Kitakata-cho, Nobeoka-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://taguchifamily.farm/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "延岡市北方町の果樹園。いちご、柿、ぶどう、桃、きんかんの収穫体験。",
      en: "Orchard in Kitakata, Nobeoka. Picking experiences for strawberries, persimmons, grapes, peaches, kinkan.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/fruit"],
  },
  {
    slug: "kawasaki-nouen-mango",
    category: ["farm"],
    area: "saito",
    name: { ja: "川﨑農園", en: "Kawasaki Farm" },
    address: { ja: "宮崎県西都市大字鹿野田481", en: "481 Kanoda, Saito-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0983-42-3404",
    website: "http://www.kawasakinouen.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "西都市の完熟マンゴー農園。宮崎マンゴー発祥の地とされる。",
      en: "Ripe-mango farm in Saito, considered the birthplace of Miyazaki mango.",
    },
    tags: null,
    sources: ["https://www.saito-kanko.jp/members/%E5%B7%9D%EF%A8%91%E8%BE%B2%E5%9C%92/"],
  },
  {
    slug: "miyazaki-sabou-tea",
    category: ["farm"],
    area: "gokase",
    name: { ja: "宮﨑茶房", en: "Miyazaki Sabou" },
    address: { ja: "宮崎県西臼杵郡五ヶ瀬町大字桑野内4966", en: "4966 Kuwanouchi, Gokase-cho, Nishi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-82-0211",
    website: "https://www.miyazaki-sabou.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "五ヶ瀬町の有機茶園。茶園の散策と試飲の体験ができる。",
      en: "Organic tea farm in Gokase. Farm walks and tasting experiences.",
    },
    tags: null,
    sources: ["https://takachiho-kanko.info/shopping/32/"],
  },
  {
    slug: "takachiho-bokujo-dairy-experience",
    category: ["farm"],
    area: "miyakonojo",
    name: { ja: "高千穂牧場 手作り体験", en: "Takachiho Bokujo Hands-on Experience" },
    address: { ja: "宮崎県都城市吉之元町5265-103", en: "5265-103 Yoshinomoto-cho, Miyakonojo-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0986-33-2102",
    website: "https://www.takachiho-bokujou.co.jp/oneday/taiken/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "霧島連山ふもとの観光牧場。バターやアイスの手作り体験、乳しぼり、乗馬（要予約）。",
      en: "Tourist dairy farm at the foot of the Kirishima range. Butter and ice-cream making, milking, horse riding (reservation required).",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/activity/1502"],
  },
  {
    slug: "enchard-cafe-farm",
    category: ["farm"],
    area: "nobeoka",
    name: { ja: "ENCHARD cafe & shop", en: "ENCHARD cafe & shop" },
    address: { ja: "宮崎県延岡市北方町蔵田辰567-14", en: "567-14 Kurada-Tatsu, Kitakata-cho, Nobeoka-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "090-6295-5676",
    website: null,
    google_maps_url: null,
    hours: {
      ja: "いちご 12月〜4月／ぶどう 8月〜9月／柿 10月〜11月",
      en: "Strawberry Dec–Apr, grape Aug–Sep, persimmon Oct–Nov",
    },
    price: null,
    description: {
      ja: "延岡市北方町のカフェ併設の果樹園。いちご・ぶどう・柿の収穫体験。",
      en: "Cafe-orchard in Kitakata, Nobeoka. Strawberry, grape and persimmon picking in season.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/feature/fruit"],
  },

  // =============================================================
  // MARKET — 直売所・道の駅物産館・漁協直売
  // =============================================================
  {
    slug: "michi-no-eki-takachiho",
    category: ["market"],
    area: "takachiho",
    name: { ja: "道の駅 高千穂 物産館", en: "Michi-no-Eki Takachiho" },
    address: { ja: "宮崎県西臼杵郡高千穂町大字三田井1296-5", en: "1296-5 Mitai, Takachiho-cho, Nishi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-72-9123",
    website: "https://takachiho-kanko.info/shopping/26/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "高千穂の道の駅の物産館。地元の野菜と加工品を扱う。",
      en: "Michi-no-Eki Takachiho's shop. Local vegetables and prepared products.",
    },
    tags: null,
    sources: ["https://takachiho-kanko.info/shopping/26/"],
  },
  {
    slug: "michi-no-eki-kitakata-yocchimiro",
    category: ["market"],
    area: "nobeoka",
    name: { ja: "道の駅 北方 よっちみろ屋", en: "Michi-no-Eki Kitakata Yocchimiroya" },
    address: { ja: "宮崎県延岡市北方町早日渡巳175-1", en: "175-1 Hayato-Mi, Kitakata-cho, Nobeoka-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "延岡市北方町の道の駅の直売所。",
      en: "Michi-no-Eki direct-sales shop in Kitakata, Nobeoka.",
    },
    tags: null,
    sources: ["https://sanchoku55.com/miyazaki/sanchoku/"],
  },
  {
    slug: "michi-no-eki-kitagawa-hayuma",
    category: ["market"],
    area: "nobeoka",
    name: { ja: "道の駅 北川はゆま", en: "Michi-no-Eki Kitagawa Hayuma" },
    address: { ja: "宮崎県延岡市北川町長井5751-1", en: "5751-1 Nagai, Kitagawa-cho, Nobeoka-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "延岡市北川町の道の駅の物産館。新鮮野菜と手作りの特産品を扱う。",
      en: "Michi-no-Eki shop in Kitagawa, Nobeoka. Fresh vegetables and local products.",
    },
    tags: null,
    sources: ["https://sanchoku55.com/miyazaki/sanchoku/"],
  },
  {
    slug: "michi-no-eki-kitaura",
    category: ["market"],
    area: "nobeoka",
    name: { ja: "道の駅 北浦 物産館", en: "Michi-no-Eki Kitaura" },
    address: { ja: "宮崎県延岡市北浦町古江3337-1", en: "3337-1 Furue, Kitaura-cho, Nobeoka-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://nobekan.jp/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "道の駅北浦の物産館。地元の野菜・加工品・漁協の直売コーナー、月の塩など。",
      en: "Michi-no-Eki Kitaura shop. Local produce, crafts, fisheries co-op section, tsuki-no-shio salt and more.",
    },
    tags: null,
    sources: [
      "https://nobekan.jp/souvenir/%E9%81%93%E3%81%AE%E9%A7%85%E5%8C%97%E6%B5%A6%E3%80%80%E7%89%A9%E7%94%A3%E9%A4%A8/",
    ],
  },
  {
    slug: "michi-no-eki-togo-shikisai",
    category: ["market"],
    area: "hyuga",
    name: { ja: "道の駅 とうごう 詩季彩", en: "Michi-no-Eki Togo Shikisai" },
    address: { ja: "宮崎県日向市東郷町山陰辛244-1", en: "244-1 Yamakage-Kanoto, Togo-cho, Hyuga-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "日向市東郷町の道の駅の物産館「詩季彩」。",
      en: "Shikisai, the shop at Michi-no-Eki Togo, Hyuga.",
    },
    tags: null,
    sources: ["https://sanchoku55.com/miyazaki/sanchoku/"],
  },
  {
    slug: "shunsen-kadogawa-chokubai-center",
    category: ["market"],
    area: "kadogawa",
    name: { ja: "旬鮮かどがわ直売センター", en: "Shunsen Kadogawa Direct Sales Center" },
    address: { ja: "宮崎県東臼杵郡門川町加草2333", en: "2333 Kagusa, Kadogawa-cho, Higashi-Usuki-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-68-1101",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "門川町の直売所。野菜・魚・蜂蜜・手搾りへべす果汁など。",
      en: "Kadogawa direct-sales shop. Vegetables, fish, honey, hand-pressed hebesu juice.",
    },
    tags: null,
    sources: ["http://www.yappamiyazaki.jp/store/search.php?codeNumber=1358401086"],
  },
  {
    slug: "michi-no-eki-hyuga",
    category: ["market"],
    area: "hyuga",
    name: { ja: "道の駅 日向", en: "Michi-no-Eki Hyuga" },
    address: { ja: "宮崎県日向市大字幸脇241-7", en: "241-7 Sachiwaki, Hyuga-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "日向市南部の道の駅の直売所。海が近い。",
      en: "Direct-sales shop at Michi-no-Eki Hyuga in the south of the city, near the sea.",
    },
    tags: null,
    sources: ["https://sanchoku55.com/miyazaki/sanchoku/"],
  },
  {
    slug: "michi-no-eki-tsuno-monzenichiba",
    category: ["market"],
    area: "tsuno",
    name: { ja: "道の駅 つの 門前市場", en: "Michi-no-Eki Tsuno Monzenichiba" },
    address: { ja: "宮崎県児湯郡都農町大字川北5129", en: "5129 Kawakita, Tsuno-cho, Koyu-gun, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://michinoeki-tsuno.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "都農町の道の駅の直売所。都農・川南の野菜と果物、都農ワインを扱う。",
      en: "Direct-sales shop at Michi-no-Eki Tsuno. Vegetables and fruit from Tsuno and Kawaminami, plus Tsuno Wine.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1082"],
  },
  {
    slug: "michi-no-eki-takaoka-vitaminkan",
    category: ["market"],
    area: "miyazaki-shi",
    name: { ja: "道の駅 高岡 ビタミン館", en: "Michi-no-Eki Takaoka Vitaminkan" },
    address: { ja: "宮崎県宮崎市高岡町花見304-5", en: "304-5 Hanami, Takaoka-cho, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0985-82-4936",
    website: "https://vitaminkan.miyazaki.jp/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "宮崎市高岡町の道の駅の直売所。農産物と特産・お土産を扱う。",
      en: "Direct-sales shop at Michi-no-Eki Takaoka in Miyazaki City. Produce and local specialties.",
    },
    tags: null,
    sources: ["https://www.city.miyazaki.miyazaki.jp/culture/facilities/718.html"],
  },
  {
    slug: "michi-no-eki-yamanokuchi",
    category: ["market"],
    area: "miyakonojo",
    name: { ja: "道の駅 山之口 ふるさと産品販売所", en: "Michi-no-Eki Yamanokuchi" },
    address: { ja: "宮崎県都城市山之口町山之口2304-6", en: "2304-6 Yamanokuchi, Yamanokuchi-cho, Miyakonojo-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0986-57-5222",
    website: "http://www.btvm.ne.jp/~yama-269/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "都城市山之口の道の駅の直売所。地元の野菜と甘乳蘇を扱う。",
      en: "Direct-sales shop at Michi-no-Eki Yamanokuchi, Miyakonojo. Local vegetables and kanchisu.",
    },
    tags: null,
    sources: ["https://www.kanko-miyazaki.jp/spot/1128"],
  },
  {
    slug: "michi-no-eki-nango",
    category: ["market"],
    area: "nichinan",
    name: { ja: "道の駅 なんごう", en: "Michi-no-Eki Nango" },
    address: { ja: "宮崎県日南市南郷町大字贄波3220-24", en: "3220-24 Nietsuba, Nango-cho, Nichinan-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0987-64-3055",
    website: "https://www.michinoeki-nango.jp/",
    google_maps_url: null,
    hours: {
      ja: "4月〜7月に完熟マンゴー販売",
      en: "Ripe mango sales April–July",
    },
    price: null,
    description: {
      ja: "日南市南郷の道の駅の直売所。トロピカルフルーツと完熟マンゴーを扱う。",
      en: "Michi-no-Eki Nango shop in Nichinan. Tropical fruit and ripe mango.",
    },
    tags: null,
    sources: ["https://www.michinoeki-nango.jp/"],
  },
  {
    slug: "michi-no-eki-sakatani-shop",
    category: ["market"],
    area: "nichinan",
    name: { ja: "道の駅 酒谷 せせらぎの里 物産館", en: "Michi-no-Eki Sakatani Shop" },
    address: { ja: "宮崎県日南市酒谷1840-4", en: "1840-4 Sakatani, Nichinan-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0987-26-1051",
    website: "https://michinoeki-sakatani.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "日南市酒谷の道の駅の物産館。地元の野菜・山菜・果物、草だんごや棚田そばを扱う。",
      en: "Michi-no-Eki Sakatani shop. Local produce and mountain vegetables; kusa-dango and tanada soba.",
    },
    tags: null,
    sources: ["https://michinoeki-sakatani.com/"],
  },
  {
    slug: "michi-no-eki-kushima",
    category: ["market"],
    area: "kushima",
    name: { ja: "道の駅 くしま ウミヤママルシェ", en: "Michi-no-Eki Kushima" },
    address: { ja: "宮崎県串間市大字西方5503-1", en: "5503-1 Nishikata, Kushima-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0987-72-0800",
    website: "https://michinoeki-kushima.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "串間市の道の駅の直売所。海の幸と山の幸を扱う。2022年開業。",
      en: "Michi-no-Eki Kushima shop. Sea and mountain produce. Opened 2022.",
    },
    tags: null,
    sources: ["https://michinoeki-kushima.com/"],
  },
  {
    slug: "michi-no-eki-ebino-yui-no-ichi",
    category: ["market"],
    area: "ebino",
    name: { ja: "道の駅 えびの 結いの市", en: "Michi-no-Eki Ebino Yui-no-Ichi" },
    address: { ja: "宮崎県えびの市大字永山1006-1", en: "1006-1 Nagayama, Ebino-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0984-35-3338",
    website: "https://michinoeki-ebino.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "えびの市の道の駅の直売所。地場野菜と果物、宮崎牛。JAが運営。",
      en: "Michi-no-Eki Ebino direct sales. Local produce, fruit, and Miyazaki Beef. Operated by JA.",
    },
    tags: null,
    sources: ["https://life.ja-group.jp/farm/market/detail?id=231"],
  },
  {
    slug: "michi-no-eki-fenix",
    category: ["market"],
    area: "miyazaki-shi",
    name: { ja: "道の駅 フェニックス", en: "Michi-no-Eki Phoenix" },
    address: { ja: "宮崎県宮崎市大字内海字三池381-1", en: "381-1 Miike, Uchiumi, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "宮崎市南部・日南海岸の道の駅の物産館。",
      en: "Michi-no-Eki shop on the Nichinan coast, south of Miyazaki City.",
    },
    tags: null,
    sources: ["https://sanchoku55.com/miyazaki/sanchoku/"],
  },
  {
    slug: "aya-tezukuri-honmono-center",
    category: ["market"],
    area: "aya",
    name: { ja: "綾 手づくりほんものセンター", en: "Aya Handmade Honmono Center" },
    address: { ja: "宮崎県東諸県郡綾町大字南俣515", en: "515 Minamimata, Aya-cho, Higashi-Morokata-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0985-77-0777",
    website: "http://www.aya-honmono.jp/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "綾町の直売施設。有機認証の農産物、加工品、工芸品を扱う。",
      en: "Aya direct-sales facility. Certified organic produce, prepared foods, and crafts.",
    },
    tags: null,
    sources: ["https://www.town.aya.miyazaki.jp/site/tour-guide/9339.html"],
  },
  {
    slug: "mimata-yokamonya",
    category: ["market"],
    area: "mimata",
    name: { ja: "三股町物産館 よかもんや", en: "Mimata Yokamonya" },
    address: { ja: "宮崎県北諸県郡三股町大字樺山4421-22", en: "4421-22 Kabayama, Mimata-cho, Kita-Morokata-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0986-52-3131",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "三股町の町営物産館。町内の名品と野菜を扱う。",
      en: "Town-run product hall in Mimata. Local specialties and vegetables.",
    },
    tags: null,
    sources: ["https://www.town.mimata.lg.jp/kanko/buy-yokamonya/"],
  },
  {
    slug: "wachidonga-mura-shikibunosato",
    category: ["market"],
    area: "kunitomi",
    name: { ja: "わちどんが村 式部の里", en: "Wachidonga-mura Shikibunosato" },
    address: { ja: "宮崎県東諸県郡国富町大字嵐田字中須2434-3", en: "2434-3 Nakasu, Aratada, Kunitomi-cho, Higashi-Morokata-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0985-41-4831",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "国富町のJA直売所。",
      en: "JA direct-sales shop in Kunitomi.",
    },
    tags: null,
    sources: ["https://life.ja-group.jp/farm/market/list?state=%E5%AE%AE%E5%B4%8E%E7%9C%8C"],
  },
  {
    slug: "koyu-ruupin",
    category: ["market"],
    area: "shintomi",
    name: { ja: "こゆ農畜産物直売所 ルーピン", en: "Koyu Farmers Market Lupin" },
    address: { ja: "宮崎県児湯郡新富町大字三納代2032-2", en: "2032-2 Minoushiro, Shintomi-cho, Koyu-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0983-32-1107",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "新富町のJA直売所。",
      en: "JA direct-sales shop in Shintomi.",
    },
    tags: null,
    sources: ["https://life.ja-group.jp/farm/market/list?state=%E5%AE%AE%E5%B4%8E%E7%9C%8C"],
  },
  {
    slug: "sanchoku-osuzumura",
    category: ["market"],
    area: "kawaminami",
    name: { ja: "産直 おすず村", en: "Sanchoku Osuzu-mura" },
    address: { ja: "宮崎県児湯郡川南町大字川南13590-2", en: "13590-2 Kawaminami, Kawaminami-cho, Koyu-gun, Miyazaki" },
    lat: null, lng: null,
    phone: "0983-27-3066",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "川南町のJA直売所。",
      en: "JA direct-sales shop in Kawaminami.",
    },
    tags: null,
    sources: ["https://life.ja-group.jp/farm/market/list?state=%E5%AE%AE%E5%B4%8E%E7%9C%8C"],
  },
  {
    slug: "icchagahiroba",
    category: ["market"],
    area: "saito",
    name: { ja: "いっちゃが広場", en: "Icchaga Hiroba" },
    address: { ja: "宮崎県西都市大字三宅9386", en: "9386 Miyake, Saito-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0983-43-5005",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "西都市のJA直売所。",
      en: "JA direct-sales shop in Saito.",
    },
    tags: null,
    sources: ["https://life.ja-group.jp/farm/market/list?state=%E5%AE%AE%E5%B4%8E%E7%9C%8C"],
  },
  {
    slug: "hachina-kan-hyuga",
    category: ["market"],
    area: "hyuga",
    name: { ja: "八菜館 ひちや店", en: "Hachinakan Hichiya" },
    address: { ja: "宮崎県日向市江良町2-62-2", en: "2-62-2 Era-cho, Hyuga-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0982-54-7810",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "日向市のJA直売所。",
      en: "JA direct-sales shop in Hyuga.",
    },
    tags: null,
    sources: ["https://life.ja-group.jp/farm/market/list?state=%E5%AE%AE%E5%B4%8E%E7%9C%8C"],
  },
  {
    slug: "hyakushomura-otsuka",
    category: ["market"],
    area: "miyazaki-shi",
    name: { ja: "百笑村 大塚店", en: "Hyakushomura Otsuka" },
    address: { ja: "宮崎県宮崎市大塚町樋之口2003", en: "2003 Hinokuchi, Otsuka-cho, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0985-53-0828",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "宮崎市大塚町のJA直売所。",
      en: "JA direct-sales shop in Otsuka, Miyazaki City.",
    },
    tags: null,
    sources: ["https://life.ja-group.jp/farm/market/list?state=%E5%AE%AE%E5%B4%8E%E7%9C%8C"],
  },
  {
    slug: "hyakushomura-kobayashi",
    category: ["market"],
    area: "kobayashi",
    name: { ja: "百笑村 小林店", en: "Hyakushomura Kobayashi" },
    address: { ja: "宮崎県小林市水流迫648", en: "648 Tsurusako, Kobayashi-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0984-23-5632",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "小林市のJA直売所。",
      en: "JA direct-sales shop in Kobayashi.",
    },
    tags: null,
    sources: ["https://life.ja-group.jp/farm/market/list?state=%E5%AE%AE%E5%B4%8E%E7%9C%8C"],
  },
  {
    slug: "asagiri-atom-miyakonojo",
    category: ["market"],
    area: "miyakonojo",
    name: { ja: "朝霧の里 ATOM", en: "Asagiri-no-Sato ATOM" },
    address: { ja: "宮崎県都城市高木町6316", en: "6316 Takagi-cho, Miyakonojo-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0986-38-1129",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "都城市のJA直売所。",
      en: "JA direct-sales shop in Miyakonojo.",
    },
    tags: null,
    sources: ["https://life.ja-group.jp/farm/market/list?state=%E5%AE%AE%E5%B4%8E%E7%9C%8C"],
  },
  {
    slug: "agri-shop-agata",
    category: ["market"],
    area: "nichinan",
    name: { ja: "アグリショップ あがた生活店", en: "Agri Shop Agata" },
    address: { ja: "宮崎県日南市中央通1-2-3", en: "1-2-3 Chuo-dori, Nichinan-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0987-23-5533",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "日南市中央通のJA直売所。",
      en: "JA direct-sales shop on Nichinan's Chuo-dori.",
    },
    tags: null,
    sources: ["https://life.ja-group.jp/farm/market/list?state=%E5%AE%AE%E5%B4%8E%E7%9C%8C"],
  },
  {
    slug: "hinata-marche-ikime-shikinooka",
    category: ["market"],
    area: "miyazaki-shi",
    name: { ja: "ひなたマルシェ生目四季の丘", en: "Hinata Marche Ikime Shikinooka" },
    address: { ja: "宮崎県宮崎市大字柏原字高後508-7", en: "508-7 Koka, Kashiwabara, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0985-65-6666",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "宮崎市生目のJA直売所。",
      en: "JA direct-sales shop in Ikime, Miyazaki City.",
    },
    tags: null,
    sources: ["https://life.ja-group.jp/farm/market/list?state=%E5%AE%AE%E5%B4%8E%E7%9C%8C"],
  },
  {
    slug: "minato-aoshima-chokubai-center",
    category: ["market"],
    area: "miyazaki-shi",
    name: { ja: "港あおしま 直売センター", en: "Minato Aoshima Direct Sales Center" },
    address: { ja: "宮崎県宮崎市青島3-5-1", en: "3-5-1 Aoshima, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: "0985-65-0606",
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "青島漁港の漁協直売所。青島どれの魚介類を扱う。",
      en: "Aoshima fisheries co-op direct sales. Aoshima-dore seafood.",
    },
    tags: null,
    sources: ["https://www.pride-fish.jp/shop/index.php?c=shop2&pk=1424737936"],
  },
  {
    slug: "minato-aburatsu-asa-ichi",
    category: ["market"],
    area: "nichinan",
    name: { ja: "港あぶらつ朝市", en: "Minato Aburatsu Morning Market" },
    address: { ja: "宮崎県日南市油津 油津漁港", en: "Aburatsu fishing port, Aburatsu, Nichinan-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: {
      ja: "毎月第4日曜 7:00〜9:00",
      en: "4th Sunday of each month, 7:00–9:00",
    },
    price: null,
    description: {
      ja: "油津漁港で毎月第4日曜に開かれる朝市。日南どれの魚とセルフ焼き場もある。",
      en: "Morning market at Aburatsu port on the 4th Sunday of each month. Nichinan-dore fish and a self-grill area.",
    },
    tags: null,
    sources: [
      "https://miyazaki.uminohi.jp/event/%E6%B8%AF%E3%81%82%E3%81%B6%E3%82%89%E3%81%A4%E6%9C%9D%E5%B8%82/",
    ],
  },
];

function ensureDir(dir: string): void {
  fs.mkdirSync(dir, { recursive: true });
}

function main(): void {
  ensureDir(OUT);
  let ok = 0;
  const failures: { slug: string; issues: string[] }[] = [];
  for (const s of seeds) {
    const full: Listing = {
      slug: s.slug,
      genre: "food",
      category: s.category,
      area: s.area,
      name: s.name,
      address: s.address,
      lat: s.lat,
      lng: s.lng,
      phone: s.phone,
      website: s.website,
      google_maps_url: s.google_maps_url,
      hours: s.hours,
      price: s.price,
      description: s.description,
      tags: s.tags,
      features: s.features ?? [],
      sources: s.sources,
      verified_at: s.verified_at ?? TODAY,
      status: s.status ?? "open",
    };
    const parsed = listingSchema.safeParse(full);
    if (!parsed.success) {
      failures.push({
        slug: s.slug,
        issues: parsed.error.issues.map((i) => `${i.path.join(".")}: ${i.message}`),
      });
      continue;
    }
    const file = path.join(OUT, `${s.slug}.json`);
    fs.writeFileSync(file, JSON.stringify(parsed.data, null, 2) + "\n", "utf8");
    ok += 1;
  }
  console.log(`wrote ${ok} listing(s) to ${OUT}`);
  if (failures.length > 0) {
    console.error(`FAIL - ${failures.length} listing(s) invalid:`);
    for (const f of failures) {
      console.error(`  ${f.slug}:`);
      for (const i of f.issues) console.error(`    - ${i}`);
    }
    process.exit(1);
  }
}

main();
