// このスクリプトは初回生成用。再実行すると data/listings/golf/*.json の手修正が
// 上書きされるので再実行しないこと。listing の正は JSON ファイルのほう。
import fs from "node:fs";
import path from "node:path";
import { listingSchema, type Listing } from "../lib/types";

// Verification date of the candidate list these seeds are built from.
const TODAY = "2026-09-15";
const ROOT = process.cwd();
const OUT = path.join(ROOT, "data", "listings", "golf");

type Seed = Omit<Listing, "genre" | "verified_at" | "status" | "features"> & {
  status?: Listing["status"];
  verified_at?: string;
  features?: string[];
};

const seeds: Seed[] = [
  // =============================================================
  // COURSES
  // =============================================================
  {
    slug: "miyazaki-cc",
    category: ["course"],
    area: "miyazaki-shi",
    name: { ja: "宮崎カントリークラブ", en: "Miyazaki Country Club" },
    address: { ja: "宮崎県宮崎市田吉4855-90", en: "4855-90 Tayoshi, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://www.miyazakicc.jp/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "宮崎市田吉の18Hコース。1960年開場。JLPGAツアーチャンピオンシップリコーカップの開催コース。",
      en: "18-hole course in Tayoshi, Miyazaki City. Opened 1960; hosts the JLPGA Tour Championship Ricoh Cup.",
    },
    tags: null,
    features: ["reservation-online", "english"],
    sources: ["https://www.miyazakicc.jp/"],
  },
  {
    slug: "phoenix-cc",
    category: ["course"],
    area: "miyazaki-shi",
    name: { ja: "フェニックスカントリークラブ", en: "Phoenix Country Club" },
    address: { ja: "宮崎県宮崎市山崎町浜山", en: "Hamayama, Yamazaki-cho, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://seagaia.co.jp/pcc",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "シーガイア内の27Hコース。宿泊付きプランあり。レストランとコンペルーム、350ヤード練習場のアカデミー併設。",
      en: "27-hole course inside the Seagaia resort. Stay-and-play plans, restaurant and function rooms, and an academy with a 350-yard range.",
    },
    tags: null,
    features: ["restaurant", "reservation-online", "english", "stay-onsite", "practice-range", "lesson"],
    sources: ["https://seagaia.co.jp/pcc", "https://seagaia.co.jp/golf/"],
  },
  {
    slug: "tom-watson-golf-course",
    category: ["course"],
    area: "miyazaki-shi",
    name: { ja: "トム・ワトソンゴルフコース", en: "Tom Watson Golf Course" },
    address: { ja: "宮崎県宮崎市山崎町浜山", en: "Hamayama, Yamazaki-cho, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://seagaia.co.jp/twgc",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "シーガイア内の18Hコース。ナイター営業あり。リゾート内に宿泊施設とレストラン。英語表示とネット予約あり。",
      en: "18-hole course inside the Seagaia resort. Night play available, lodging and a restaurant on the resort, English site and online booking.",
    },
    tags: null,
    features: ["night", "stay-onsite", "restaurant", "reservation-online", "english"],
    sources: ["https://seagaia.co.jp/twgc"],
  },
  {
    slug: "hibiscus-gc",
    category: ["course"],
    area: "miyazaki-shi",
    name: { ja: "ハイビスカスゴルフクラブ", en: "Hibiscus Golf Club" },
    address: { ja: "宮崎県宮崎市佐土原町下田島21085-1", en: "21085-1 Shimotajima, Sadowara-cho, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://www.hibiscus-gc.jp/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "佐土原の18H・パー72・6,920ヤード。レストランあり。ネット予約可。",
      en: "18-hole par-72 course, 6,920 yards, in Sadowara. Restaurant on site and online booking.",
    },
    tags: null,
    features: ["restaurant", "reservation-online"],
    sources: ["https://www.hibiscus-gc.jp/"],
  },
  {
    slug: "miyazaki-lakeside-gc",
    category: ["course"],
    area: "miyazaki-shi",
    name: { ja: "宮崎レイクサイドゴルフ倶楽部", en: "Miyazaki Lakeside Golf Club" },
    address: { ja: "宮崎県宮崎市清武町今泉丙1331-1", en: "1331-1 Imaizumi-hei, Kiyotake-cho, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://www.lakeside-gc.com/facility/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "清武町の18Hコース。練習場、レストランとコンペルーム、プロショップ・ロッカー・浴室あり。",
      en: "18-hole course in Kiyotake. Practice range, restaurant and function room, pro shop, lockers and baths.",
    },
    tags: null,
    features: ["practice-range", "restaurant"],
    sources: ["https://www.lakeside-gc.com/facility/"],
  },
  {
    slug: "umk-cc",
    category: ["course"],
    area: "miyazaki-shi",
    name: { ja: "UMKカントリークラブ", en: "UMK Country Club" },
    address: { ja: "宮崎県宮崎市新名爪坂ノ下2055", en: "2055 Sakanoshita, Niinazume, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://umkcc.jp/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "宮崎市新名爪の18Hコース。アクサレディスの開催コース。練習場とレストランあり。ネット予約可。",
      en: "18-hole course in Niinazume, Miyazaki City. Hosts the AXA Ladies tournament. Practice range, restaurant and online booking.",
    },
    tags: null,
    features: ["practice-range", "restaurant", "reservation-online"],
    sources: ["https://umkcc.jp/"],
  },
  {
    slug: "aoshima-gc",
    category: ["course"],
    area: "miyazaki-shi",
    name: { ja: "青島ゴルフ倶楽部", en: "Aoshima Golf Club" },
    address: { ja: "宮崎県宮崎市折生迫大谷4180", en: "4180 Otani, Orio-zako, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://reserve.accordiagolf.com/golfCourse/miyazaki/aoshima/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "青島の18Hコース。アコーディア・ゴルフ運営。クラブレンタル、練習場とスクール、レストランあり。",
      en: "18-hole course near Aoshima, run by Accordia Golf. Club rental, practice range and school, restaurant, online booking.",
    },
    tags: null,
    features: ["rental-clubs", "practice-range", "lesson", "restaurant", "reservation-online", "english"],
    sources: ["https://reserve.accordiagolf.com/golfCourse/miyazaki/aoshima/"],
  },
  {
    slug: "miyazaki-public-golf",
    category: ["course"],
    area: "miyazaki-shi",
    name: { ja: "宮崎パブリックゴルフ", en: "Miyazaki Public Golf" },
    address: { ja: "宮崎県宮崎市田吉松崎4979-58", en: "4979-58 Matsuzaki, Tayoshi, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://miyazaki-pg.com/",
    google_maps_url: null,
    hours: {
      ja: "受付 7:00〜17:00。食堂 9:00〜14:30",
      en: "Reception 7:00–17:00. Canteen 9:00–14:30.",
    },
    price: null,
    description: {
      ja: "田吉の9Hパブリックコース。5日前までネット予約可。食堂あり。",
      en: "Nine-hole public course in Tayoshi. Online booking up to five days ahead. Canteen on site.",
    },
    tags: null,
    features: ["short-course", "reservation-online", "restaurant"],
    sources: ["https://miyazaki-pg.com/"],
  },
  {
    slug: "miyazaki-airport-cc",
    category: ["course"],
    area: "miyazaki-shi",
    name: { ja: "宮崎国際空港カントリークラブ", en: "Miyazaki Kokusai Airport Country Club" },
    address: { ja: "宮崎県宮崎市田野町乙5030-2", en: "5030-2 Otsu, Tano-cho, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "http://www.mkk-cc.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "田野町の18Hコース。宿泊ロッジ併設で1泊朝食・昼食付の宿泊ゴルフパックあり。レストランと宴会場あり。",
      en: "18-hole course in Tano. On-site lodge with a stay-and-play package including breakfast and lunch. Restaurant and banquet room.",
    },
    tags: null,
    features: ["stay-onsite", "restaurant", "reservation-online"],
    sources: ["http://www.mkk-cc.com/", "http://mkk-cc.com/facility.html"],
  },
  {
    slug: "miyazaki-ohyodo-cc",
    category: ["course"],
    area: "miyazaki-shi",
    name: { ja: "宮崎大淀カントリークラブ", en: "Miyazaki Ohyodo Country Club" },
    address: { ja: "宮崎県宮崎市長嶺唯ヶ迫1021", en: "1021 Nagamine, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://www.m-ohyodo-cc.co.jp/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "宮崎市長嶺の18Hコース。レストランあり。ネット予約可。",
      en: "18-hole course in Nagamine, Miyazaki City. Restaurant on site and online booking.",
    },
    tags: null,
    features: ["restaurant", "reservation-online"],
    sources: ["https://www.m-ohyodo-cc.co.jp/"],
  },
  {
    slug: "miyazaki-sunshine-cc",
    category: ["course"],
    area: "miyazaki-shi",
    name: { ja: "宮崎サンシャインカントリークラブ", en: "Miyazaki Sunshine Country Club" },
    address: { ja: "宮崎県宮崎市佐土原町東上那珂11538-1", en: "11538-1 Higashi-Kaminaka, Sadowara-cho, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://sunshine-cc.jp/",
    google_maps_url: null,
    hours: { ja: "受付 8:00〜17:00（営業日のみ）", en: "Reception 8:00–17:00 on open days." },
    price: { ja: "貸クラブ 1セット 3,300円。", en: "Club rental 3,300 yen per set." },
    description: {
      ja: "佐土原の18Hコース。薄暮ゴルフと9Hプレーあり。貸クラブ、レストラン、テイクアウトあり。",
      en: "18-hole course in Sadowara. Twilight rounds and nine-hole play, club rental, restaurant with takeout.",
    },
    tags: null,
    features: ["rental-clubs", "restaurant", "reservation-online", "english"],
    sources: ["https://sunshine-cc.jp/"],
  },
  {
    slug: "miyazaki-golf-club",
    category: ["course"],
    area: "kunitomi",
    name: { ja: "宮崎ゴルフ倶楽部", en: "Miyazaki Golf Club" },
    address: { ja: "宮崎県東諸県郡国富町三名六ツ野原", en: "Sanmyo, Kunitomi-cho, Higashi-Morokata-gun, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "http://www.miyazakigolfclub.jp/",
    google_maps_url: null,
    hours: { ja: "定休日 1/1", en: "Closed January 1." },
    price: null,
    description: {
      ja: "国富町の18H・パー72・6,648ヤード。1973年開場。練習場あり。クレジットカード可。",
      en: "18-hole par-72 course, 6,648 yards, in Kunitomi. Opened 1973. Practice range on site, credit cards accepted.",
    },
    tags: null,
    features: ["practice-range"],
    sources: ["http://www.miyazakigolfclub.jp/"],
  },
  {
    slug: "miyazaki-kokusai-gc",
    category: ["course"],
    area: "miyazaki-shi",
    name: { ja: "宮崎国際ゴルフ倶楽部", en: "Miyazaki Kokusai Golf Club" },
    address: { ja: "宮崎県宮崎市佐土原町下田島6634-1", en: "6634-1 Shimotajima, Sadowara-cho, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://booking.pacificgolf.co.jp/guide/137.html",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "佐土原の27Hコース（橘・霧島・尾鈴）。PGM運営。レストランあり。ネット予約可。",
      en: "27-hole course in Sadowara with the Tachibana, Kirishima and Ozuzu nines. Run by PGM. Restaurant and online booking.",
    },
    tags: null,
    features: ["restaurant", "reservation-online", "english"],
    sources: ["https://booking.pacificgolf.co.jp/guide/137.html"],
  },
  {
    slug: "miyazaki-kobayashi-cc",
    category: ["course"],
    area: "kobayashi",
    name: { ja: "宮崎小林カントリークラブ", en: "Miyazaki Kobayashi Country Club" },
    address: { ja: "宮崎県小林市南西方1131", en: "1131 Minami-Nishikata, Kobayashi-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://kobayashicc.jp/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "小林市の18Hコース。敷地内にコテージ18棟。1泊＋1ラウンドのゴルフパックあり。24時間ネット予約可。",
      en: "18-hole course in Kobayashi with 18 cottages on site. One-night, one-round golf package. Online booking around the clock.",
    },
    tags: null,
    features: ["stay-onsite", "reservation-online"],
    sources: ["https://kobayashicc.jp/", "https://kobayashicc.jp/stay.html"],
  },
  {
    slug: "regent-miyazaki-cc",
    category: ["course"],
    area: "miyakonojo",
    name: { ja: "リージェント宮崎カントリークラブ", en: "Regent Miyazaki Country Club" },
    address: { ja: "宮崎県都城市山田町中霧島4423-4", en: "4423-4 Nakakirishima, Yamada-cho, Miyakonojo-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://regentmiyazaki.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "都城市山田町のゴルフ場。レストランあり。ネット予約可。",
      en: "Golf course in Yamada, Miyakonojo. Restaurant on site and online booking.",
    },
    tags: null,
    features: ["restaurant", "reservation-online"],
    sources: ["https://regentmiyazaki.com/"],
  },
  {
    slug: "rainbow-sports-land-gc",
    category: ["course"],
    area: "miyakonojo",
    name: { ja: "レインボースポーツランドゴルフクラブ", en: "Rainbow Sports Land Golf Club" },
    address: { ja: "宮崎県都城市高城町石山4474", en: "4474 Ishiyama, Takajo-cho, Miyakonojo-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://reserve.accordiagolf.com/golfCourse/miyazaki/rainbow/",
    google_maps_url: null,
    hours: {
      ja: "クラブハウス 平日 7:30〜、土日祝 7:00〜",
      en: "Clubhouse opens 7:30 on weekdays, 7:00 at weekends and on holidays.",
    },
    price: null,
    description: {
      ja: "都城市高城町の18Hコース。アコーディア・ゴルフ運営。クラブレンタルとレストランあり。",
      en: "18-hole course in Takajo, Miyakonojo, run by Accordia Golf. Club rental, restaurant and online booking.",
    },
    tags: null,
    features: ["rental-clubs", "restaurant", "reservation-online", "english"],
    sources: ["https://reserve.accordiagolf.com/golfCourse/miyazaki/rainbow/"],
  },
  {
    slug: "nichinan-kitago-cc",
    category: ["course"],
    area: "nichinan",
    name: { ja: "日南北郷カントリークラブ", en: "Nichinan Kitago Country Club" },
    address: { ja: "宮崎県日南市北郷町郷之原甲2821-1", en: "2821-1 Ko, Gonohara, Kitago-cho, Nichinan-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://www.nk-resort.co.jp/golf/",
    google_maps_url: null,
    hours: {
      ja: "昼食 11:00〜14:00。温泉 10:00〜22:00。毎週木曜は完全セルフデー",
      en: "Lunch 11:00–14:00. Onsen 10:00–22:00. Full self-play every Thursday.",
    },
    price: null,
    description: {
      ja: "北郷の18H・7,012ヤード・パー72。ホテル併設で宿泊ゴルフパックと日帰りプランあり。温泉とレストランあり。",
      en: "18-hole, 7,012-yard par-72 course in Kitago. Hotel on site with stay-and-play and day plans, hot spring and restaurant.",
    },
    tags: null,
    features: ["stay-onsite", "restaurant", "reservation-online", "english"],
    sources: ["https://www.nk-resort.co.jp/golf/"],
  },
  {
    slug: "nichinan-kushima-golf-course",
    category: ["course"],
    area: "kushima",
    name: { ja: "日南串間ゴルフコース", en: "Nichinan Kushima Golf Course" },
    address: { ja: "宮崎県串間市本城", en: "Honjo, Kushima-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://www.princehotels.co.jp/golf/kushima/",
    google_maps_url: null,
    hours: { ja: "通年営業", en: "Open year round." },
    price: null,
    description: {
      ja: "串間市本城の18H・パー72。西武プリンスホテルズ運営。レストランあり。空き枠検索と予約ができる。",
      en: "18-hole par-72 course in Honjo, Kushima. Run by Seibu Prince Hotels. Restaurant, tee-time search and booking.",
    },
    tags: null,
    features: ["restaurant", "reservation-online", "english"],
    sources: ["https://www.princehotels.co.jp/golf/kushima/"],
  },
  {
    slug: "mimitsu-cc",
    category: ["course"],
    area: "hyuga",
    name: { ja: "美々津カントリークラブ", en: "Mimitsu Country Club" },
    address: { ja: "宮崎県日向市東郷町山陰甲417-94", en: "417-94 Ko, Yamage, Togo-cho, Hyuga-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://mimitsu-cc.jp/",
    google_maps_url: null,
    hours: { ja: "8:00〜17:00", en: "8:00–17:00." },
    price: null,
    description: {
      ja: "日向市東郷町のゴルフ場。レストランあり。外部の予約システムで予約できる。",
      en: "Golf course in Togo, Hyuga. Restaurant on site, booking through an external system.",
    },
    tags: null,
    features: ["restaurant", "reservation-online"],
    sources: ["https://mimitsu-cc.jp/"],
  },
  {
    slug: "cherry-golf-kitakata",
    category: ["course"],
    area: "nobeoka",
    name: { ja: "チェリーゴルフ北方コース", en: "Cherry Golf Kitakata Course" },
    address: { ja: "宮崎県延岡市北方町笠下寅1566", en: "1566 Tora, Kasashita, Kitakata-cho, Nobeoka-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://cherry-group.jp/sp/course_kitakata/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "延岡市北方町の18Hコース。チェリーゴルフグループ運営。レストランあり。ネット予約可。",
      en: "18-hole course in Kitakata, Nobeoka, run by the Cherry Golf group. Restaurant and online booking.",
    },
    tags: null,
    features: ["restaurant", "reservation-online"],
    sources: ["https://cherry-group.jp/sp/course_kitakata/"],
  },
  {
    slug: "cherry-golf-nobeoka",
    category: ["course"],
    area: "nobeoka",
    name: { ja: "チェリーゴルフ延岡コース", en: "Cherry Golf Nobeoka Course" },
    address: { ja: "宮崎県延岡市浦城町1161", en: "1161 Urashiro-cho, Nobeoka-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://cherry-group.jp/course_nobeoka/index.html",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "延岡市浦城町のゴルフ場。チェリーゴルフグループ運営。レストランあり。ネット予約可。",
      en: "Golf course in Urashiro, Nobeoka, run by the Cherry Golf group. Restaurant and online booking.",
    },
    tags: null,
    features: ["restaurant", "reservation-online"],
    sources: ["https://cherry-group.jp/course_nobeoka/index.html"],
  },
  {
    slug: "zaronbai-gc",
    category: ["course"],
    area: "shintomi",
    name: { ja: "宮崎座論梅ゴルフクラブ", en: "Miyazaki Zaronbai Golf Club" },
    address: { ja: "宮崎県児湯郡新富町新田17605", en: "17605 Nyuta, Shintomi-cho, Koyu-gun, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: { ja: "定休日なし", en: "Open every day." },
    price: null,
    description: {
      ja: "新富町新田の18H・パー72。クラブレンタルとレストランあり。練習場は大会時のみ利用できる。",
      en: "18-hole par-72 course in Nyuta, Shintomi. Club rental and restaurant. The practice range opens only for tournaments.",
    },
    tags: null,
    features: ["rental-clubs", "restaurant"],
    sources: ["https://golf-jalan.net/gc02502/"],
  },
  {
    slug: "hitotsuse-kenmin-golf",
    category: ["course"],
    area: "shintomi",
    name: { ja: "一ツ瀬川県民ゴルフ場", en: "Hitotsusegawa Kenmin Golf Course" },
    address: { ja: "宮崎県児湯郡新富町新田2591", en: "2591 Nyuta, Shintomi-cho, Koyu-gun, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: { ja: "定休日 1/1", en: "Closed January 1." },
    price: null,
    description: {
      ja: "新富町の県民ゴルフ場。18H・パー70・5,710ヤード。クラブとシューズのレンタル、練習場とアプローチ練習場あり。",
      en: "Prefectural 18-hole par-70 course, 5,710 yards, in Shintomi. Club and shoe rental, practice range and approach area.",
    },
    tags: null,
    features: ["rental-clubs", "practice-range"],
    sources: ["https://booking.gora.golf.rakuten.co.jp/guide/disp/c_id/450011/"],
  },
  {
    slug: "ohyodogawa-golf",
    category: ["course"],
    area: "miyazaki-shi",
    name: { ja: "大淀川ゴルフ場", en: "Oyodogawa Golf Course" },
    address: { ja: "宮崎県宮崎市跡江385-2", en: "385-2 Atoe, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: { ja: "定休日 毎週金曜・12/31・1/1", en: "Closed Fridays, December 31 and January 1." },
    price: null,
    description: {
      ja: "宮崎市跡江の9Hコース。ティー位置を変えて2周する。全ホール100ヤードのショートコースもある。",
      en: "Nine-hole course in Atoe, Miyazaki City, played twice from different tees. Also a short course with 100-yard holes.",
    },
    tags: null,
    features: ["short-course"],
    sources: ["https://golf-jalan.net/gc02484/"],
  },
  {
    slug: "takaharu-gc",
    category: ["course"],
    area: "takaharu",
    name: { ja: "たかはるゴルフクラブ", en: "Takaharu Golf Club" },
    address: { ja: "宮崎県西諸県郡高原町広原6017", en: "6017 Hirowara, Takaharu-cho, Nishi-Morokata-gun, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: { ja: "定休日なし", en: "Open every day." },
    price: null,
    description: {
      ja: "高原町の9H・パー36のコース。ソフトスパイクのみ。",
      en: "Nine-hole par-36 course in Takaharu. Soft spikes only.",
    },
    tags: null,
    features: ["short-course"],
    sources: ["https://booking.gora.golf.rakuten.co.jp/guide/disp/c_id/6198/"],
  },
  {
    slug: "mochio-cc",
    category: ["course"],
    area: "miyakonojo",
    name: { ja: "都城母智丘カントリークラブ", en: "Miyakonojo Mochio Country Club" },
    address: { ja: "宮崎県都城市関之尾町6328", en: "6328 Sekinoo-cho, Miyakonojo-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: { ja: "定休日なし", en: "Open every day." },
    price: { ja: "レンタルクラブ 3,000円。", en: "Club rental 3,000 yen." },
    description: {
      ja: "都城市関之尾町の18H。関之尾OUT・母智IN。セルフプレーと乗用カート。レンタルクラブと食堂あり。",
      en: "18 holes in Sekinoo, Miyakonojo, played as the Sekinoo and Mochio nines. Self-play with carts, club rental and a canteen.",
    },
    tags: null,
    features: ["rental-clubs", "restaurant"],
    sources: [
      "https://www.city.miyakonojo.miyazaki.jp/site/kanko/31912.html",
      "https://golf-jalan.net/gc02486/",
    ],
  },
  {
    slug: "aiwa-miyazaki-gc",
    category: ["course"],
    area: "miyazaki-shi",
    name: { ja: "愛和宮崎ゴルフクラブ", en: "Aiwa Miyazaki Golf Club" },
    address: { ja: "宮崎県宮崎市佐土原町東上那珂105", en: "105 Higashi-Kaminaka, Sadowara-cho, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: { ja: "定休日なし", en: "Open every day." },
    price: null,
    description: {
      ja: "佐土原の18H・7,093ヤード・パー72。全室バルコニー付のホテル併設。セルフとキャディを選べる。",
      en: "18-hole, 7,093-yard par-72 course in Sadowara. Hotel on site with a balcony in every room. Self-play or caddie.",
    },
    tags: null,
    features: ["stay-onsite", "restaurant"],
    sources: [
      "https://golf-jalan.net/gc02494/info/",
      "https://www.miyazaki-city.tourism.or.jp/spot/12405",
    ],
  },

  // =============================================================
  // DRIVING RANGES / INDOOR
  // =============================================================
  {
    slug: "asahigaoka-golf-resort",
    category: ["range"],
    area: "mimata",
    name: { ja: "旭ヶ丘ゴルフリゾート", en: "Asahigaoka Golf Resort" },
    address: { ja: "宮崎県北諸県郡三股町蓼池5200", en: "5200 Tadeike, Mimata-cho, Kita-Morokata-gun, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://www.asahigaoka-golf-resort.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "三股町の250ヤード練習場。LED照明でナイター可。ショートコース併設。クラブレンタルとスクールあり。",
      en: "250-yard range in Mimata with LED lighting for night play. Short course on site, club rental and lessons.",
    },
    tags: null,
    features: ["night", "rental-clubs", "lesson", "short-course", "restaurant"],
    sources: ["https://www.asahigaoka-golf-resort.com/"],
  },
  {
    slug: "miyazaki-airport-golf-center",
    category: ["range"],
    area: "miyazaki-shi",
    name: { ja: "宮崎空港ゴルフセンター", en: "Miyazaki Airport Golf Center" },
    address: { ja: "宮崎県宮崎市赤江33", en: "33 Akae, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://www.sakura-ga.com/",
    google_maps_url: null,
    hours: {
      ja: "7:00〜21:00（日曜は7:00〜20:00）。定休日 毎月第4木曜（祝日は営業）、12/31、1/1",
      en: "7:00–21:00 (Sundays to 20:00). Closed the fourth Thursday each month (open if a holiday), December 31 and January 1.",
    },
    price: null,
    description: {
      ja: "宮崎市赤江の練習場。入場料制。初心者・一般・ジュニアのゴルフスクールあり。",
      en: "Driving range in Akae, Miyazaki City. Entry-fee system. Golf school for beginners, general players and juniors.",
    },
    tags: null,
    features: ["lesson"],
    sources: ["https://www.sakura-ga.com/"],
  },
  {
    slug: "ikeuchi-golf",
    category: ["range"],
    area: "miyazaki-shi",
    name: { ja: "いけうちゴルフ", en: "Ikeuchi Golf" },
    address: { ja: "宮崎県宮崎市池内町3535", en: "3535 Ikeuchi-cho, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://ikeuchigolf.storeinfo.jp/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "宮崎市池内町の練習場。レッスンあり。",
      en: "Driving range in Ikeuchi, Miyazaki City. Lessons available.",
    },
    tags: null,
    features: ["lesson"],
    sources: ["https://ikeuchigolf.storeinfo.jp/"],
  },
  {
    slug: "nomura-golf",
    category: ["range"],
    area: "miyazaki-shi",
    name: { ja: "野村ゴルフ練習場", en: "Nomura Golf Range" },
    address: { ja: "宮崎県宮崎市佐土原町下那珂8312", en: "8312 Shimonaka, Sadowara-cho, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://www.kobitonomura.co.jp/practiceground",
    google_maps_url: null,
    hours: {
      ja: "月・水・木 8:00〜20:00、火 8:00〜21:00。定休日 1/1〜1/3",
      en: "Mon, Wed, Thu 8:00–20:00; Tue 8:00–21:00. Closed January 1–3.",
    },
    price: { ja: "貸クラブ 無料。", en: "Club rental free." },
    description: {
      ja: "佐土原の22打席（1階16・2階6）の練習場。貸クラブ無料。初心者から競技者までのレッスンあり。",
      en: "22-bay range in Sadowara, 16 on the ground floor and 6 upstairs. Free club rental, lessons from beginner to competitive.",
    },
    tags: null,
    features: ["rental-clubs", "lesson"],
    sources: ["https://www.kobitonomura.co.jp/practiceground"],
  },
  {
    slug: "shintomi-sports-land",
    category: ["range"],
    area: "shintomi",
    name: { ja: "新富スポーツランド", en: "Shintomi Sports Land" },
    address: { ja: "宮崎県児湯郡新富町三納代2185-3", en: "2185-3 Minoshiro, Shintomi-cho, Koyu-gun, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://shintomi-sl.com/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "新富町のゴルフ練習場。パークゴルフ・テニス・バッティング・卓球も併設。",
      en: "Driving range in Shintomi. Park golf, tennis, batting cages and table tennis on the same site.",
    },
    tags: null,
    features: [],
    sources: ["https://shintomi-sl.com/"],
  },
  {
    slug: "golf-partner-miyakonojo-range",
    category: ["range"],
    area: "miyakonojo",
    name: { ja: "ゴルフパートナー 都城練習場店", en: "Golf Partner Miyakonojo Range" },
    address: { ja: "宮崎県都城市若葉町54-7", en: "54-7 Wakaba-cho, Miyakonojo-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://store.golfpartner.jp/39103",
    google_maps_url: null,
    hours: {
      ja: "練習場 平日 6:30〜22:00、土日祝 6:30〜21:00。月曜は早朝枠（6:30〜8:30）休み",
      en: "Range weekdays 6:30–22:00, weekends and holidays 6:30–21:00. No early slot (6:30–8:30) on Mondays.",
    },
    price: null,
    description: {
      ja: "都城市若葉町の練習場。照明あり。ショップ・試打室・弾道測定・工房を併設。レッスン対応。",
      en: "Range in Wakaba, Miyakonojo, with floodlights, a shop, fitting bay, launch monitor and club workshop. Lessons available.",
    },
    tags: null,
    features: ["night", "lesson"],
    sources: ["https://store.golfpartner.jp/39103"],
  },
  {
    slug: "indoor-golf-club-kyushu-fukushima",
    category: ["range"],
    area: "miyazaki-shi",
    name: { ja: "インドアゴルフクラブ九州 福島町店", en: "Indoor Golf Club Kyushu Fukushima-cho" },
    address: { ja: "宮崎県宮崎市福島町3-117-1", en: "3-117-1 Fukushima-cho, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://igc-kyusyu.jp/",
    google_maps_url: null,
    hours: { ja: "24時間営業、年中無休", en: "Open 24 hours, every day." },
    price: null,
    description: {
      ja: "宮崎市福島町のインドア練習場。シミュレーターとパター練習。会員制で月2回のグループレッスンあり。",
      en: "Indoor range in Fukushima-cho, Miyazaki City. Simulator and putting area. Members only, group lessons twice a month.",
    },
    tags: null,
    features: ["lesson"],
    sources: ["https://igc-kyusyu.jp/"],
  },
  {
    slug: "indoor-golf-club-kyushu-aoba",
    category: ["range"],
    area: "miyazaki-shi",
    name: { ja: "インドアゴルフクラブ九州 青葉店", en: "Indoor Golf Club Kyushu Aoba" },
    address: { ja: "宮崎県宮崎市青葉町92-2", en: "92-2 Aoba-cho, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://igc-kyusyu.jp/",
    google_maps_url: null,
    hours: { ja: "24時間営業、年中無休", en: "Open 24 hours, every day." },
    price: null,
    description: {
      ja: "宮崎市青葉町のインドア練習場。シミュレーターとパター練習。会員制。無料体験あり。",
      en: "Indoor range in Aoba-cho, Miyazaki City. Simulator and putting area. Members only, free trial available.",
    },
    tags: null,
    features: ["lesson"],
    sources: ["https://igc-kyusyu.jp/"],
  },
  {
    slug: "hello-golf",
    category: ["range"],
    area: "miyazaki-shi",
    name: { ja: "HELLO GOLF", en: "Hello Golf" },
    address: {
      ja: "宮崎県宮崎市橘通西3-10-32 宮崎ナナイロ東館1F",
      en: "Miyazaki Nanairo East 1F, 3-10-32 Tachibana-dori Nishi, Miyazaki-shi, Miyazaki",
    },
    lat: null, lng: null,
    phone: null,
    website: "https://hellogolf.pro/",
    google_maps_url: null,
    hours: { ja: "9:00〜22:00（最終受付 21:00）", en: "9:00–22:00, last entry 21:00." },
    price: { ja: "貸クラブ 無料。", en: "Club rental free." },
    description: {
      ja: "宮崎市中心部のインドア練習場。全打席に弾道測定。バンカー・アプローチ・パターの練習エリアあり。",
      en: "Indoor range in central Miyazaki. Launch monitors in every bay, with bunker, approach and putting areas.",
    },
    tags: null,
    features: ["lesson", "rental-clubs"],
    sources: ["https://hellogolf.pro/"],
  },
  {
    slug: "aya-golf-studio",
    category: ["range"],
    area: "nobeoka",
    name: { ja: "AYA GOLF STUDIO", en: "Aya Golf Studio" },
    address: { ja: "宮崎県延岡市", en: "Nobeoka-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://aya-gs.jp/",
    google_maps_url: null,
    hours: { ja: "24時間営業", en: "Open 24 hours." },
    price: null,
    description: {
      ja: "延岡市のインドアゴルフスタジオ。個室シミュレーター。スタジオ・練習場・コースのレッスンあり。会員制。",
      en: "Indoor golf studio in Nobeoka with private simulator rooms. Studio, range and on-course lessons. Members only.",
    },
    tags: null,
    features: ["lesson"],
    sources: ["https://aya-gs.jp/"],
  },
  {
    slug: "lien-golf-club",
    category: ["range"],
    area: "miyakonojo",
    name: { ja: "リアンゴルフクラブ", en: "Lien Golf Club" },
    address: { ja: "宮崎県都城市宮丸町3017-10", en: "3017-10 Miyamaru-cho, Miyakonojo-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://www.njcgood.com/",
    google_maps_url: null,
    hours: { ja: "8:00〜23:00", en: "8:00–23:00." },
    price: null,
    description: {
      ja: "都城市の11打席の練習場。GDR・VISIONなどのシミュレーター。プロレッスンあり。会員制。",
      en: "Eleven-bay range in Miyakonojo with GDR and VISION simulators. Pro lessons, members only.",
    },
    tags: null,
    features: ["lesson", "rental-clubs"],
    sources: ["https://www.njcgood.com/"],
  },
  {
    slug: "k-golf-saito",
    category: ["range"],
    area: "saito",
    name: { ja: "K-golf", en: "K-golf" },
    address: { ja: "宮崎県西都市妻町3-43", en: "3-43 Tsuma-cho, Saito-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://k-golf24.stores.jp/reserve/k-golf24",
    google_maps_url: null,
    hours: { ja: "24時間・年中無休", en: "Open 24 hours, every day." },
    price: null,
    description: {
      ja: "西都市妻町の24時間インドア練習場。シミュレーター完備。貸クラブ無料。入会金なしの時間貸し。",
      en: "24-hour indoor range in Tsuma, Saito. Simulators, free club rental, pay by the hour with no joining fee.",
    },
    tags: null,
    features: ["rental-clubs", "reservation-online"],
    sources: ["https://k-golf24.stores.jp/reserve/k-golf24"],
  },
  {
    slug: "golf72-nichinan",
    category: ["range"],
    area: "nichinan",
    name: { ja: "Golf72", en: "Golf72" },
    address: {
      ja: "宮崎県日南市南郷町南町3-1 平成ビル2F",
      en: "Heisei Bldg 2F, 3-1 Minami-machi, Nango-cho, Nichinan-shi, Miyazaki",
    },
    lat: null, lng: null,
    phone: null,
    website: "https://golf72.localinfo.jp/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "日南市南郷町のインドア練習場。完全個室でバーチャルゴルフ100コース。",
      en: "Indoor range in Nango, Nichinan. Fully private rooms with 100 virtual courses.",
    },
    tags: null,
    features: [],
    sources: ["https://golf72.localinfo.jp/"],
  },
  {
    slug: "gst-golf-studio-takayama",
    category: ["range"],
    area: "takanabe",
    name: { ja: "GST Golf Studio Takayama", en: "GST Golf Studio Takayama" },
    address: { ja: "宮崎県児湯郡高鍋町南高鍋7026-1", en: "7026-1 Minami-Takanabe, Takanabe-cho, Koyu-gun, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://www.golfstudiotakayama.jp/concept",
    google_maps_url: null,
    hours: {
      ja: "月〜土 8:00〜21:00、日祝 8:00〜20:00。不定休",
      en: "Mon–Sat 8:00–21:00, Sun and holidays 8:00–20:00. Irregular closing days.",
    },
    price: null,
    description: {
      ja: "高鍋町の全天候型の室内練習場。GOLFZONシミュレーターは240コース超。レッスンとクラブ工房あり。",
      en: "All-weather indoor range in Takanabe. GOLFZON simulator with over 240 courses, lessons and a club workshop.",
    },
    tags: null,
    features: ["lesson"],
    sources: ["https://www.golfstudiotakayama.jp/concept"],
  },
  {
    slug: "lit-golf",
    category: ["range"],
    area: "miyazaki-shi",
    name: { ja: "LIT GOLF", en: "LIT GOLF" },
    address: { ja: "宮崎県宮崎市江平東1-7-2", en: "1-7-2 Ehira-higashi, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://lit-golf.com/",
    google_maps_url: null,
    hours: {
      ja: "インドア 火〜土 8:00〜23:00、日祝 8:00〜20:00。定休日 月曜（祝日は火曜）、不定休あり",
      en: "Indoor bays Tue–Sat 8:00–23:00, Sun and holidays 8:00–20:00. Closed Mondays (Tuesday if Monday is a holiday).",
    },
    price: null,
    description: {
      ja: "宮崎市江平東のインドア練習場。TRACKMANの4打席で左打席あり。レンタルクラブ、ショップと工房を併設。",
      en: "Indoor range in Ehira-higashi, Miyazaki City. Four TRACKMAN bays including a left-handed bay, club rental, shop and workshop.",
    },
    tags: null,
    features: ["lesson", "rental-clubs"],
    sources: ["https://lit-golf.com/"],
  },
  {
    slug: "noa-golf-studio",
    category: ["range"],
    area: "miyazaki-shi",
    name: { ja: "NOA GOLF STUDIO", en: "Noa Golf Studio" },
    address: { ja: "宮崎県宮崎市", en: "Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://noa-golf.jp/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "宮崎市のインドア練習場。ツアー公式シミュレーターとAIスイング診断、専用アプリ。",
      en: "Indoor range in Miyazaki City with a tour-spec simulator, AI swing analysis and its own app.",
    },
    tags: null,
    features: [],
    sources: ["https://noa-golf.jp/"],
  },
  {
    slug: "p-one-under",
    category: ["range"],
    area: "miyazaki-shi",
    name: { ja: "P-One Under INDOOR GOLF BASE", en: "P-One Under Indoor Golf Base" },
    address: { ja: "宮崎県宮崎市橘通東3-1-11 B1F", en: "B1F, 3-1-11 Tachibana-dori Higashi, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://p-oneunder.com/",
    google_maps_url: null,
    hours: { ja: "7:00〜22:00", en: "7:00–22:00." },
    price: null,
    description: {
      ja: "宮崎市橘通東のインドア練習場。弾道測定と1000fpsカメラ。プロレッスンあり。道具のレンタルはなし。",
      en: "Indoor range on Tachibana-dori Higashi, Miyazaki City. Launch monitor and 1000fps camera, pro lessons. No equipment rental.",
    },
    tags: null,
    features: ["lesson"],
    sources: ["https://p-oneunder.com/"],
  },
  {
    slug: "inthegolf-aeon-miyazaki",
    category: ["range"],
    area: "miyazaki-shi",
    name: { ja: "インザゴルフ イオンモール宮崎店", en: "In The Golf Aeon Mall Miyazaki" },
    address: {
      ja: "宮崎県宮崎市新別府町江口862-1 イオンモール宮崎2F",
      en: "Aeon Mall Miyazaki 2F, 862-1 Eguchi, Shinbeppu-cho, Miyazaki-shi, Miyazaki",
    },
    lat: null, lng: null,
    phone: null,
    website: "https://inthegolf.com/list/aeon-miyazaki/",
    google_maps_url: null,
    hours: { ja: "10:00〜21:00。木曜はノーコーチデー", en: "10:00–21:00. No coach on Thursdays." },
    price: { ja: "貸クラブ 無料。", en: "Club rental free." },
    description: {
      ja: "イオンモール宮崎2階のインドア練習場。シミュレーター6打席。レッスン付きの月会費制。貸クラブ無料。",
      en: "Indoor range on the second floor of Aeon Mall Miyazaki. Six simulator bays, monthly membership with lessons, free club rental.",
    },
    tags: null,
    features: ["lesson", "rental-clubs"],
    sources: ["https://inthegolf.com/list/aeon-miyazaki/"],
  },
  {
    slug: "fir-tree-cc",
    category: ["range"],
    area: "nobeoka",
    name: { ja: "ファーツリーカントリークラブ", en: "Fir Tree Country Club" },
    address: { ja: "宮崎県延岡市下伊形町8297-1", en: "8297-1 Shimoigata-cho, Nobeoka-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: {
      ja: "平日 8:00〜22:00、土日祝 7:00〜21:30",
      en: "Weekdays 8:00–22:00, weekends and holidays 7:00–21:30.",
    },
    price: { ja: "貸クラブ 200円／本。", en: "Club rental 200 yen per club." },
    description: {
      ja: "延岡市下伊形町の300ヤード・72打席の練習場。9Hショートコース併設。ナイター照明は無料。左打席あり。",
      en: "300-yard, 72-bay range in Shimoigata, Nobeoka. Nine-hole short course, free floodlights, left-handed bays.",
    },
    tags: null,
    features: ["night", "rental-clubs", "short-course"],
    sources: ["https://golf-medley.com/practice_facilities/1401"],
  },
  {
    slug: "tokai-golf-arena",
    category: ["range"],
    area: "nobeoka",
    name: { ja: "東海ゴルフアリーナ", en: "Tokai Golf Arena" },
    address: { ja: "宮崎県延岡市牧町4740", en: "4740 Maki-machi, Nobeoka-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "延岡市牧町の160ヤード・53打席の練習場。打ち放題あり。ショートコース、バンカー・アプローチ・パター練習場、工房を併設。",
      en: "160-yard, 53-bay range in Maki, Nobeoka. All-you-can-hit option, short course, bunker, approach and putting areas, and a workshop.",
    },
    tags: null,
    features: ["short-course"],
    sources: ["https://dr.golfdigest.co.jp/dr_detail/id=4261"],
  },
  {
    slug: "ichigaoka-golf-garden",
    category: ["range"],
    area: "nobeoka",
    name: { ja: "一ヶ岡ゴルフガーデン", en: "Ichigaoka Golf Garden" },
    address: { ja: "宮崎県延岡市下伊形7217-1", en: "7217-1 Shimoigata, Nobeoka-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: { ja: "6:00〜23:00、年中無休", en: "6:00–23:00, open every day." },
    price: null,
    description: {
      ja: "延岡市下伊形の200ヤード・60打席の練習場。ナイター設備あり。月・木・土にレッスン。",
      en: "200-yard, 60-bay range in Shimoigata, Nobeoka. Floodlit for night play, lessons on Mondays, Thursdays and Saturdays.",
    },
    tags: null,
    features: ["night", "lesson"],
    sources: ["https://golf-jalan.net/gp02500/"],
  },
  {
    slug: "grass-garden-shioji",
    category: ["range"],
    area: "miyazaki-shi",
    name: { ja: "グラスガーデン塩路", en: "Grass Garden Shioji" },
    address: { ja: "宮崎県宮崎市塩路586", en: "586 Shioji, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: { ja: "6:00〜21:30", en: "6:00–21:30." },
    price: { ja: "貸クラブ 300円／本。", en: "Club rental 300 yen per club." },
    description: {
      ja: "宮崎市塩路の220ヤード・64打席の練習場。照明は無料。平日は深夜営業。",
      en: "220-yard, 64-bay range in Shioji, Miyazaki City. Free floodlights and late-night hours on weekdays.",
    },
    tags: null,
    features: ["night", "rental-clubs"],
    sources: ["https://golf-medley.com/practice_facilities/1380"],
  },
  {
    slug: "kosei-golf-arena",
    category: ["range"],
    area: "miyazaki-shi",
    name: { ja: "光成ゴルフアリーナ", en: "Kosei Golf Arena" },
    address: { ja: "宮崎県宮崎市本郷北方2644", en: "2644 Hongo-kitakata, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: {
      ja: "平日 7:30〜21:30、土日祝 7:00〜21:30。定休日なし",
      en: "Weekdays 7:30–21:30, weekends and holidays 7:00–21:30. Open every day.",
    },
    price: null,
    description: {
      ja: "宮崎市本郷北方の210ヤード・144打席の練習場。レンタルクラブはなし。",
      en: "210-yard, 144-bay range in Hongo-kitakata, Miyazaki City. No club rental.",
    },
    tags: null,
    features: [],
    sources: ["https://golf-medley.com/practice_facilities/1383"],
  },
  {
    slug: "kaorusaka-golf",
    category: ["range"],
    area: "miyazaki-shi",
    name: { ja: "薫る坂ゴルフ練習場", en: "Kaoruzaka Golf Range" },
    address: { ja: "宮崎県宮崎市古城町南田6473-2", en: "6473-2 Minamida, Furujo-cho, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: {
      ja: "平日 8:00〜21:30、土日祝 8:00〜21:00。定休日 12/31〜1/2",
      en: "Weekdays 8:00–21:30, weekends and holidays 8:00–21:00. Closed December 31 to January 2.",
    },
    price: { ja: "貸クラブ 200円／本。", en: "Club rental 200 yen per club." },
    description: {
      ja: "宮崎市古城町の200ヤード・76打席の練習場。照明は無料。",
      en: "200-yard, 76-bay range in Furujo, Miyazaki City. Free floodlights.",
    },
    tags: null,
    features: ["night", "rental-clubs"],
    sources: ["https://golf-medley.com/practice_facilities/1384"],
  },
  {
    slug: "takaoka-golf-center",
    category: ["range"],
    area: "miyazaki-shi",
    name: { ja: "高岡ゴルフセンター", en: "Takaoka Golf Center" },
    address: { ja: "宮崎県宮崎市高岡町高浜2569", en: "2569 Takahama, Takaoka-cho, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: {
      ja: "平日 7:30〜22:00、土日祝 7:00〜22:00。定休日なし",
      en: "Weekdays 7:30–22:00, weekends and holidays 7:00–22:00. Open every day.",
    },
    price: null,
    description: {
      ja: "宮崎市高岡町の200ヤード・68打席の練習場。照明は無料。レンタルクラブあり。",
      en: "200-yard, 68-bay range in Takaoka, Miyazaki City. Free floodlights and club rental.",
    },
    tags: null,
    features: ["night", "rental-clubs"],
    sources: ["https://golf-medley.com/practice_facilities/1387"],
  },
  {
    slug: "miyakonojo-sports-garden",
    category: ["range"],
    area: "miyakonojo",
    name: { ja: "都城スポーツガーデン", en: "Miyakonojo Sports Garden" },
    address: { ja: "宮崎県都城市若葉町54-9-2", en: "54-9-2 Wakaba-cho, Miyakonojo-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: {
      ja: "平日 8:00〜22:00、土日祝 7:00〜21:00。年中無休",
      en: "Weekdays 8:00–22:00, weekends and holidays 7:00–21:00. Open every day.",
    },
    price: { ja: "貸クラブ 200円／本。", en: "Club rental 200 yen per club." },
    description: {
      ja: "都城市若葉町の150ヤード・51打席の練習場。ナイターは平日22時・土日21時まで。レッスンあり。",
      en: "150-yard, 51-bay range in Wakaba, Miyakonojo. Night play to 22:00 on weekdays and 21:00 at weekends. Lessons available.",
    },
    tags: null,
    features: ["night", "rental-clubs", "lesson"],
    sources: ["https://golf-jalan.net/gp02559/"],
  },
  {
    slug: "sunpower-golf",
    category: ["range"],
    area: "miyakonojo",
    name: { ja: "サンパワーゴルフ", en: "Sunpower Golf" },
    address: { ja: "宮崎県都城市下長飯2050", en: "2050 Shimonagae, Miyakonojo-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: {
      ja: "平日 8:00〜22:00、日曜 8:00〜21:00。年中無休",
      en: "Weekdays 8:00–22:00, Sundays 8:00–21:00. Open every day.",
    },
    price: null,
    description: {
      ja: "都城市下長飯の200ヤード・60打席の練習場。",
      en: "200-yard, 60-bay range in Shimonagae, Miyakonojo.",
    },
    tags: null,
    features: [],
    sources: ["https://golf-jalan.net/gp02470/"],
  },
  {
    slug: "sunace-golf-center",
    category: ["range"],
    area: "hyuga",
    name: { ja: "サンエースゴルフセンター", en: "Sun Ace Golf Center" },
    address: { ja: "宮崎県日向市富高6236-2", en: "6236-2 Tondaka, Hyuga-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: {
      ja: "平日 7:00〜21:00、土日祝 7:00〜19:00。定休日 月曜・1/1・1/2",
      en: "Weekdays 7:00–21:00, weekends and holidays 7:00–19:00. Closed Mondays, January 1 and 2.",
    },
    price: null,
    description: {
      ja: "日向市富高の260ヤード・40打席の練習場。レンタルクラブあり。",
      en: "260-yard, 40-bay range in Tondaka, Hyuga. Club rental available.",
    },
    tags: null,
    features: ["rental-clubs"],
    sources: ["https://golf-medley.com/practice_facilities/1392"],
  },
  {
    slug: "hontani-green-golf",
    category: ["range"],
    area: "hyuga",
    name: { ja: "本谷グリーンゴルフ", en: "Hontani Green Golf" },
    address: { ja: "宮崎県日向市富高3898-2", en: "3898-2 Tondaka, Hyuga-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "日向市富高の200ヤード・35打席の練習場。駐車場30台。",
      en: "200-yard, 35-bay range in Tondaka, Hyuga. Parking for 30 cars.",
    },
    tags: null,
    features: [],
    sources: ["https://gora.golf.rakuten.co.jp/practice-range/guide/2903"],
  },
  {
    slug: "tsuno-green-golf-center",
    category: ["range"],
    area: "tsuno",
    name: { ja: "都農グリーンゴルフセンター", en: "Tsuno Green Golf Center" },
    address: { ja: "宮崎県児湯郡都農町川北丸溝18886-2", en: "18886-2 Marumizo, Kawakita, Tsuno-cho, Koyu-gun, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: {
      ja: "通常 8:00〜20:00、火・金 8:00〜21:00。年中無休",
      en: "Usually 8:00–20:00; Tuesdays and Fridays 8:00–21:00. Open every day.",
    },
    price: null,
    description: {
      ja: "都農町の250ヤード・22打席の練習場。パターとバンカーの練習場あり。",
      en: "250-yard, 22-bay range in Tsuno. Putting and bunker practice areas.",
    },
    tags: null,
    features: [],
    sources: ["https://golf-jalan.net/gp02560/"],
  },
  {
    slug: "takanabe-golf-sports-center",
    category: ["range"],
    area: "takanabe",
    name: { ja: "高鍋ゴルフスポーツセンター", en: "Takanabe Golf Sports Center" },
    address: { ja: "宮崎県児湯郡高鍋町上江7697-88", en: "7697-88 Uwae, Takanabe-cho, Koyu-gun, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "高鍋町上江の250ヤード・68打席の練習場。駐車場70台。",
      en: "250-yard, 68-bay range in Uwae, Takanabe. Parking for 70 cars.",
    },
    tags: null,
    features: [],
    sources: ["https://gora.golf.rakuten.co.jp/practice-range/guide/2904"],
  },
  {
    slug: "kushima-golf-garden",
    category: ["range"],
    area: "kushima",
    name: { ja: "串間ゴルフガーデン", en: "Kushima Golf Garden" },
    address: { ja: "宮崎県串間市串間980", en: "980 Kushima, Kushima-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "串間市串間の200ヤード・20打席の練習場。",
      en: "200-yard, 20-bay range in Kushima.",
    },
    tags: null,
    features: [],
    sources: ["https://golf-jalan.net/gp02510/"],
  },
  {
    slug: "sankyo-golf-center",
    category: ["range"],
    area: "nichinan",
    name: { ja: "サンキョウゴルフセンター", en: "Sankyo Golf Center" },
    address: { ja: "宮崎県日南市隈谷乙1603", en: "1603 Otsu, Kumatani, Nichinan-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: { ja: "8:00〜21:00。定休日なし", en: "8:00–21:00. Open every day." },
    price: { ja: "貸クラブ 100円／本。", en: "Club rental 100 yen per club." },
    description: {
      ja: "日南市隈谷の200ヤード・23打席の練習場。照明は無料。パター・バンカー・アプローチの練習場あり。",
      en: "200-yard, 23-bay range in Kumatani, Nichinan. Free floodlights, with putting, bunker and approach areas.",
    },
    tags: null,
    features: ["night", "rental-clubs"],
    sources: ["https://golf-medley.com/practice_facilities/1397"],
  },

  // =============================================================
  // GOLF STAYS
  // =============================================================
  {
    slug: "seagaia-ocean-tower",
    category: ["stay"],
    area: "miyazaki-shi",
    name: { ja: "フェニックス・シーガイア・オーシャン・タワー", en: "Phoenix Seagaia Ocean Tower" },
    address: { ja: "宮崎県宮崎市山崎町浜山", en: "Hamayama, Yamazaki-cho, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://seagaia.co.jp/golf/reservation/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "シーガイア内のホテル。フェニックスCCとトム・ワトソンGCの宿泊付きゴルフプランの対象。リゾート内に練習場とアカデミー。",
      en: "Hotel inside the Seagaia resort, included in stay-and-play plans for Phoenix CC and Tom Watson GC. Range and academy on the resort.",
    },
    tags: null,
    features: ["stay-onsite", "practice-range", "lesson"],
    sources: ["https://seagaia.co.jp/golf/reservation/"],
  },
  {
    slug: "seagaia-forest-condominium",
    category: ["stay"],
    area: "miyazaki-shi",
    name: { ja: "シーガイア・フォレスト・コンドミニアム", en: "Seagaia Forest Condominium" },
    address: { ja: "宮崎県宮崎市山崎町浜山", en: "Hamayama, Yamazaki-cho, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://seagaia.co.jp/golf/reservation/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "シーガイア内のコンドミニアム。フェニックスCCとトム・ワトソンGCの宿泊付きゴルフプランの対象施設。",
      en: "Condominium inside the Seagaia resort, listed for stay-and-play plans at Phoenix CC and Tom Watson GC.",
    },
    tags: null,
    features: ["stay-onsite"],
    sources: ["https://seagaia.co.jp/golf/reservation/"],
  },
  {
    slug: "seagaia-forest-cottage",
    category: ["stay"],
    area: "miyazaki-shi",
    name: { ja: "シーガイア・フォレスト・コテージ", en: "Seagaia Forest Cottage" },
    address: { ja: "宮崎県宮崎市山崎町浜山", en: "Hamayama, Yamazaki-cho, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://seagaia.co.jp/golf/reservation/",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "シーガイア内のコテージ。フェニックスCCとトム・ワトソンGCの宿泊付きゴルフプランの対象施設。",
      en: "Cottages inside the Seagaia resort, listed for stay-and-play plans at Phoenix CC and Tom Watson GC.",
    },
    tags: null,
    features: ["stay-onsite"],
    sources: ["https://seagaia.co.jp/golf/reservation/"],
  },
  {
    slug: "hotel-nichinan-kitago-resort",
    category: ["stay"],
    area: "nichinan",
    name: { ja: "ホテル日南北郷リゾート", en: "Hotel Nichinan Kitago Resort" },
    address: { ja: "宮崎県日南市北郷町郷之原甲2821-1", en: "2821-1 Ko, Gonohara, Kitago-cho, Nichinan-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://www.nk-resort.co.jp/",
    google_maps_url: null,
    hours: { ja: "温泉 10:00〜22:00", en: "Onsen 10:00–22:00." },
    price: null,
    description: {
      ja: "日南北郷カントリークラブ併設のホテル。宿泊ゴルフパックと日帰りプラン。展望露天風呂と岩盤浴、バイキングのレストラン。",
      en: "Hotel attached to Nichinan Kitago Country Club. Stay-and-play packages and day plans, open-air baths, stone sauna and a buffet restaurant.",
    },
    tags: null,
    features: ["stay-onsite", "restaurant", "english"],
    sources: ["https://www.nk-resort.co.jp/", "https://www.nk-resort.co.jp/golf/"],
  },
  {
    slug: "kobayashi-cc-cottage",
    category: ["stay"],
    area: "kobayashi",
    name: { ja: "宮崎小林カントリークラブ コテージ", en: "Miyazaki Kobayashi Country Club Cottages" },
    address: { ja: "宮崎県小林市南西方1131", en: "1131 Minami-Nishikata, Kobayashi-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://kobayashicc.jp/stay.html",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "ゴルフ場の敷地内にあるコテージ18棟。1棟4名。1泊＋1ラウンド（昼食付）のパックと宿泊のみプラン。朝食付。",
      en: "Eighteen cottages inside the golf course, sleeping four each. One-night, one-round package with lunch, or room-only. Breakfast included.",
    },
    tags: null,
    features: ["stay-onsite"],
    sources: ["https://kobayashicc.jp/stay.html"],
  },
  {
    slug: "miyazaki-airport-cc-lodge",
    category: ["stay"],
    area: "miyazaki-shi",
    name: { ja: "宮崎国際空港カントリークラブ ロッジ", en: "Miyazaki Kokusai Airport Country Club Lodge" },
    address: { ja: "宮崎県宮崎市田野町乙5030-2", en: "5030-2 Otsu, Tano-cho, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "http://mkk-cc.com/facility.html",
    google_maps_url: null,
    hours: null,
    price: { ja: "宿泊税 200円／人泊（2026年7月〜）。", en: "Accommodation tax 200 yen per person per night from July 2026." },
    description: {
      ja: "ゴルフ場併設のロッジ。1泊朝食・昼食付の宿泊ゴルフパックあり。レストラン・浴室・宴会場あり。",
      en: "Lodge at the golf course. Stay-and-play package with breakfast and lunch, restaurant, bath and a banquet room.",
    },
    tags: null,
    features: ["stay-onsite", "restaurant"],
    sources: ["http://mkk-cc.com/facility.html"],
  },
  {
    slug: "hotel-aoshima-cinqmale",
    category: ["stay"],
    area: "miyazaki-shi",
    name: { ja: "ホテル青島サンクマール", en: "Hotel Aoshima Cinqmale" },
    address: { ja: "宮崎県宮崎市折生迫7408", en: "7408 Orio-zako, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: "https://www.cinqmale.co.jp/page2",
    google_maps_url: null,
    hours: null,
    price: null,
    description: {
      ja: "青島の宿。宮崎カントリークラブの18Hプレー（グリーンフィー・キャディフィー込）と宿泊のゴルフパックあり。4名1組、電話予約のみ。",
      en: "Hotel near Aoshima with a golf package: 18 holes at Miyazaki Country Club including green and caddie fees, plus a night. Four per group, phone booking.",
    },
    tags: null,
    features: [],
    sources: ["https://www.cinqmale.co.jp/page2"],
  },
  {
    slug: "aiwa-miyazaki-resort-hotel",
    category: ["stay"],
    area: "miyazaki-shi",
    name: { ja: "愛和宮崎リゾートホテル", en: "Aiwa Miyazaki Resort Hotel" },
    address: { ja: "宮崎県宮崎市佐土原町東上那珂105", en: "105 Higashi-Kaminaka, Sadowara-cho, Miyazaki-shi, Miyazaki" },
    lat: null, lng: null,
    phone: null,
    website: null,
    google_maps_url: null,
    hours: {
      ja: "チェックイン 15:00、チェックアウト 11:00。朝食 6:30〜9:00",
      en: "Check-in 15:00, check-out 11:00. Breakfast 6:30–9:00.",
    },
    price: null,
    description: {
      ja: "ゴルフ場併設のホテル。ツイン、全室バルコニー付。",
      en: "Hotel attached to the golf course. Twin rooms, each with a balcony.",
    },
    tags: null,
    features: ["stay-onsite"],
    sources: [
      "https://golf-jalan.net/gc02494/info/",
      "https://www.kanko-miyazaki.jp/golf_surfing/1161",
    ],
  },
];

function main(): void {
  fs.mkdirSync(OUT, { recursive: true });
  const failures: { slug: string; issues: string[] }[] = [];
  let ok = 0;
  for (const s of seeds) {
    const full = {
      slug: s.slug,
      genre: "golf",
      category: s.category,
      area: s.area,
      name: s.name,
      address: s.address,
      lat: s.lat,
      lng: s.lng,
      phone: s.phone,
      website: s.website,
      google_maps_url: s.google_maps_url,
      hours: s.hours,
      price: s.price,
      description: s.description,
      tags: s.tags,
      features: s.features ?? [],
      sources: s.sources,
      verified_at: s.verified_at ?? TODAY,
      status: s.status ?? "open",
    };
    const parsed = listingSchema.safeParse(full);
    if (!parsed.success) {
      failures.push({
        slug: s.slug,
        issues: parsed.error.issues.map((i) => `${i.path.join(".")}: ${i.message}`),
      });
      continue;
    }
    const file = path.join(OUT, `${s.slug}.json`);
    fs.writeFileSync(file, JSON.stringify(parsed.data, null, 2) + "\n", "utf8");
    ok += 1;
  }
  console.log(`wrote ${ok} listing(s) to ${OUT}`);
  if (failures.length > 0) {
    console.error(`FAIL - ${failures.length} listing(s) invalid:`);
    for (const f of failures) {
      console.error(`  ${f.slug}:`);
      for (const i of f.issues) console.error(`    - ${i}`);
    }
    process.exit(1);
  }
}

main();
